// vue/src/features/statuses/StatusesPage.vue
<script setup lang="ts">
import { Badge } from '@/components/ui/badge';
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { useQueryClient } from '@tanstack/vue-query';
import type { ColumnDef } from '@tanstack/vue-table';
import {
  useGetApiAdminStatuses,
  usePatchApiAdminStatusesValue,
  useDeleteApiAdminStatusesValue,
  getGetApiStatusesQueryKey,
  getGetApiAdminStatusesQueryKey,
  type StatusAdminItem,
} from '@moamen-ui/pointer-vue';
import { Save, RotateCcw, Tag } from 'lucide-vue-next';
import { DataTable, dataTableFeatures } from '@/components/shared/data-table';
import type { RowActionItem } from '@/components/shared/types';
import { extractMessage } from '@/lib/error';
import { confirm } from '@/composables/useConfirm';
import { toast } from '@/composables/useToast';

const { t } = useI18n();
const queryClient = useQueryClient();

// ── Query ─────────────────────────────────────────────────────────────
const statusesQuery = useGetApiAdminStatuses();

// ── Local edit state (seeded from query; kept separate from query cache) ──
interface EditRow {
  value: number;
  name: string | null | undefined;
  label: string;
  color: string;
  order: number;
  isOverridden: boolean;
  defaultLabel: string | null | undefined;
  defaultColor: string | null | undefined;
  defaultOrder: number;
  saving: boolean;
  resetting: boolean;
}

const rows = ref<EditRow[]>([]);

watch(
  () => statusesQuery.data.value,
  (data) => {
    if (!data) return;
    rows.value = data.map((item: StatusAdminItem) => ({
      value: item.value ?? 0,
      name: item.name,
      label: item.label ?? item.defaultLabel ?? '',
      color: item.color ?? item.defaultColor ?? '#6b7280',
      order: item.order ?? item.defaultOrder ?? 0,
      isOverridden: item.isOverridden ?? false,
      defaultLabel: item.defaultLabel,
      defaultColor: item.defaultColor,
      defaultOrder: item.defaultOrder ?? 0,
      saving: false,
      resetting: false,
    }));
  },
  { immediate: true },
);

// ── Mutations ─────────────────────────────────────────────────────────
const patchMutation = usePatchApiAdminStatusesValue();
const deleteMutation = useDeleteApiAdminStatusesValue();

function invalidateCatalog() {
  void queryClient.invalidateQueries({ queryKey: getGetApiStatusesQueryKey() });
  void queryClient.invalidateQueries({ queryKey: getGetApiAdminStatusesQueryKey() });
}

// ── Save ─────────────────────────────────────────────────────────────
async function saveRow(row: EditRow) {
  row.saving = true;
  try {
    await patchMutation.mutateAsync({
      value: row.value,
      data: { label: row.label, color: row.color, order: row.order },
    });
    toast(t('statuses.savedOk'), 'success');
    invalidateCatalog();
  } catch (e) {
    toast(extractMessage(e), 'danger');
  } finally {
    row.saving = false;
  }
}

// Every in-table control — label, colour, order — is the same slim box: 36px
// tall, 1px border, 6px radius, 8px inline padding, brand border + ring on
// focus, and a borderless transparent inner input at ~0.8rem. Matches the
// Angular statuses table so the row reads as one set of controls.
const fieldClass =
  'flex h-9 items-center gap-1.5 rounded-[6px] border border-input bg-transparent px-2 shadow-sm focus-within:border-brand focus-within:outline-none focus-within:ring-1 focus-within:ring-ring';
const fieldInputClass =
  'w-full min-w-0 border-none bg-transparent p-0 text-[0.8rem] outline-none placeholder:text-muted-foreground';

// ── Reset ─────────────────────────────────────────────────────────────
async function resetRow(row: EditRow) {
  const ok = await confirm({
    message: t('statuses.confirmReset'),
    confirmLabel: t('statuses.reset'),
    confirmVariant: 'destructive',
  });
  if (!ok) return;
  row.resetting = true;
  try {
    await deleteMutation.mutateAsync({ value: row.value });
    toast(t('statuses.resetOk'), 'success');
    invalidateCatalog();
  } catch (e) {
    toast(extractMessage(e), 'danger');
  } finally {
    row.resetting = false;
  }
}

// A computed so headers follow live language switches.
const columns = computed<ColumnDef<typeof dataTableFeatures, EditRow>[]>(() => [
  { accessorKey: 'name', header: t('statuses.colName'), enableSorting: false },
  { accessorKey: 'label', header: t('statuses.colLabel'), enableSorting: false },
  { accessorKey: 'color', header: t('statuses.colColor'), enableSorting: false },
  { accessorKey: 'order', header: t('statuses.colOrder'), enableSorting: false },
]);

function actionsFor(row: EditRow): RowActionItem[] {
  const items: RowActionItem[] = [
    {
      label: t('statuses.save'),
      icon: Save,
      disabled: row.saving || row.resetting,
      onClick: () => void saveRow(row),
    },
  ];
  if (row.isOverridden) {
    items.push({
      label: t('statuses.reset'),
      icon: RotateCcw,
      severity: 'danger',
      disabled: row.saving || row.resetting,
      onClick: () => void resetRow(row),
    });
  }
  return items;
}
// Built-in status values map onto the badge variants that carry their diff hue and glyph.
function badgeVariantForStatus(value: number | undefined) {
  switch (value) {
    case 2: return 'warning' as const;
    case 3: return 'success' as const;
    case 4: return 'archived' as const;
    default: return 'open' as const;
  }
}

</script>

<template>
  <div class="flex flex-col gap-4">
    <h1 class="text-[20px] font-semibold leading-7 tracking-[-0.01em]">{{ t('statuses.title') }}</h1>

    <!-- Loading spinner (only when genuinely no data yet) -->
    <div
      v-if="statusesQuery.isLoading.value && rows.length === 0"
      class="h-0.5 w-full overflow-hidden rounded bg-muted"
    >
      <div class="h-full w-1/3 animate-pulse bg-primary" />
    </div>

    <!-- Error state -->
    <p v-if="statusesQuery.isError.value && rows.length === 0" class="py-6 text-destructive">
      {{ t('statuses.loadError') }}
    </p>

    <!-- Table — kept visible during refetch. Every column but "name" is a live
         inline-edit control bound to local per-row state -- the escape hatch
         this page needs instead of DataTable's plain display-only cells. -->
    <DataTable
      :data="rows"
      :columns="columns"
      :actions="actionsFor"
      :actions-aria-label="t('statuses.colActions')"
      :actions-header="t('statuses.colActions')"
      :loading="statusesQuery.isLoading.value"
      gutter
      :empty-icon="Tag"
      :empty-message="t('statuses.empty')"
      :empty-hint="t('statuses.emptyHint')"
    >
      <template #cell-name="{ row }">
        <Badge :variant="badgeVariantForStatus(row.value)" class="font-medium">
          {{ row.name ?? String(row.value) }}
        </Badge>
      </template>

      <!-- Label — same slim box as the colour control below -->
      <template #cell-label="{ row }">
        <div :class="[fieldClass, 'w-[132px]']">
          <input
            v-model="row.label"
            :maxlength="64"
            :class="fieldInputClass"
            :placeholder="t('statuses.colLabel')"
            :aria-label="t('statuses.colLabel')"
          />
        </div>
      </template>

      <!-- Color: single merged swatch + hex input -->
      <template #cell-color="{ row }">
        <div :class="[fieldClass, 'w-[124px] ps-1.5']">
          <input
            v-model="row.color"
            type="color"
            class="color-swatch h-6 w-6 flex-shrink-0 cursor-pointer rounded border-none bg-transparent p-0"
            :title="row.color"
            :aria-label="t('statuses.colColor')"
          />
          <input
            v-model="row.color"
            type="text"
            :maxlength="7"
            :class="[fieldInputClass, 'font-mono']"
            placeholder="#rrggbb"
          />
        </div>
      </template>

      <!-- Order — same slim box as the colour control above -->
      <template #cell-order="{ row }">
        <div :class="[fieldClass, 'w-16']">
          <input
            v-model.number="row.order"
            type="number"
            :min="0"
            :class="fieldInputClass"
            placeholder="0"
            :aria-label="t('statuses.colOrder')"
          />
        </div>
      </template>
    </DataTable>
  </div>
</template>

<style scoped>
/* Native colour input: drop the browser's chrome so it reads as a plain
   swatch inside the merged colour control. */
.color-swatch {
  appearance: none;
  -webkit-appearance: none;
}
.color-swatch::-webkit-color-swatch-wrapper { padding: 0; }
.color-swatch::-webkit-color-swatch { border: none; border-radius: 3px; }
.color-swatch::-moz-color-swatch { border: none; border-radius: 3px; }
</style>

// react/src/features/statuses/StatusesPage.tsx
// Statuses admin page — edit presentation label / color / order per status,
// or reset a status back to its defaults. Mirrors the Angular sibling.
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useQueryClient } from '@tanstack/react-query';
import {
  useGetApiAdminStatuses,
  usePatchApiAdminStatusesValue,
  useDeleteApiAdminStatusesValue,
  getGetApiAdminStatusesQueryKey,
  getGetApiStatusesQueryKey,
  type StatusAdminItem,
} from '@moamen-ui/pointer-react';
import type { ColumnDef } from '@tanstack/react-table';
import { Save, RotateCcw, Tag } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { DataTable } from '@/components/shared/data-table/DataTable';
import type { RowActionItem } from '@/components/shared/types';
import { ConfirmDialog } from '@/components/ConfirmDialog';
import { useToast } from '@/components/ui/toast';
import { extractMessage } from '@/lib/error';

interface RowState {
  label: string;
  color: string;
  order: number;
}

function initRow(s: StatusAdminItem): RowState {
  return {
    label: s.label ?? s.defaultLabel ?? '',
    color: s.color ?? s.defaultColor ?? '#6b7280',
    order: s.order ?? s.defaultOrder ?? 0,
  };
}

/** Built-in status values map onto the badge variants that carry their diff hue and glyph. */
function badgeVariantForStatus(value: number | undefined) {
  switch (value) {
    case 2: return 'warning' as const;
    case 3: return 'success' as const;
    case 4: return 'archived' as const;
    default: return 'open' as const;
  }
}

export function StatusesPage() {
  const { t } = useTranslation();
  const { toast } = useToast();
  const qc = useQueryClient();

  const { data, isLoading, isError } = useGetApiAdminStatuses();

  // Local edit state — seeded from query data, not mutating the cache.
  const [rows, setRows] = useState<Record<number, RowState>>({});

  useEffect(() => {
    if (data) {
      const next: Record<number, RowState> = {};
      data.forEach((s) => {
        if (s.value != null) next[s.value] = initRow(s);
      });
      setRows(next);
    }
  }, [data]);

  function invalidate() {
    void qc.invalidateQueries({ queryKey: getGetApiAdminStatusesQueryKey() });
    void qc.invalidateQueries({ queryKey: getGetApiStatusesQueryKey() });
  }

  const onError = (e: unknown) => toast(extractMessage(e), 'error');

  // ---- PATCH (save) ----
  const patchMut = usePatchApiAdminStatusesValue({
    mutation: {
      onSuccess: () => {
        toast(t('statuses.saveSuccess'));
        invalidate();
      },
      onError,
    },
  });

  function save(statusValue: number) {
    const row = rows[statusValue];
    if (!row) return;
    patchMut.mutate({
      value: statusValue,
      data: { label: row.label, color: row.color, order: row.order },
    });
  }

  // ---- DELETE (reset) ----
  const [resetTarget, setResetTarget] = useState<StatusAdminItem | null>(null);

  const deleteMut = useDeleteApiAdminStatusesValue({
    mutation: {
      onSuccess: () => {
        setResetTarget(null);
        toast(t('statuses.resetSuccess'));
        invalidate();
      },
      onError: (e) => {
        setResetTarget(null);
        onError(e);
      },
    },
  });

  function confirmReset() {
    if (resetTarget?.value != null) {
      deleteMut.mutate({ value: resetTarget.value });
    }
  }

  // ---- Row field helpers ----
  function setField<K extends keyof RowState>(
    statusValue: number,
    field: K,
    value: RowState[K],
  ) {
    setRows((prev) => ({
      ...prev,
      [statusValue]: { ...prev[statusValue], [field]: value },
    }));
  }

  // ---- Render ----
  if (isLoading && !data) {
    return (
      <div className="flex h-40 items-center justify-center text-sm text-muted-foreground">
        {t('statuses.loading')}
      </div>
    );
  }

  if (isError) {
    return (
      <div className="flex h-40 items-center justify-center text-sm text-destructive">
        {t('statuses.loadError')}
      </div>
    );
  }

  const statuses = data ?? [];
  const isBusy = patchMut.isPending || deleteMut.isPending;

  // Every column but "name" is a live inline-edit control bound to local per-row
  // state -- the escape hatch this page needs instead of DataTable's plain
  // display-only cells.
  const columns: ColumnDef<StatusAdminItem>[] = [
    {
      accessorKey: 'name',
      enableSorting: false,
      header: t('statuses.colName'),
      meta: { mobile: 'primary' },
      cell: ({ row }) => (
        <Badge variant={badgeVariantForStatus(row.original.value)} className="font-medium">
          {row.original.name ?? String(row.original.value)}
        </Badge>
      ),
    },
    {
      id: 'label',
      enableSorting: false,
      header: t('statuses.colLabel'),
      cell: ({ row }) => {
        const val = row.original.value!;
        const r = rows[val] ?? initRow(row.original);
        return (
          // Same slim box as the colour control below, so the row reads as one
          // set of controls.
          <Input
            className="w-[132px] px-2 text-[0.8rem] focus-visible:border-brand focus-visible:ring-1 focus-visible:ring-brand focus-visible:ring-offset-0"
            aria-label={t('statuses.colLabel')}
            value={r.label}
            maxLength={64}
            onChange={(e) => setField(val, 'label', e.target.value)}
          />
        );
      },
    },
    {
      id: 'color',
      enableSorting: false,
      header: t('statuses.colColor'),
      cell: ({ row }) => {
        const val = row.original.value!;
        const r = rows[val] ?? initRow(row.original);
        return (
          // Swatch + hex are one control: a single bordered box that lights up
          // on focus, with the native picker inside it.
          <div className="inline-flex h-9 max-md:h-[38px] w-[124px] items-center gap-1.5 rounded-md border border-input bg-transparent ps-1.5 pe-2 shadow-sm focus-within:border-brand focus-within:ring-1 focus-within:ring-brand">
            <input
              type="color"
              aria-label={t('statuses.colColor')}
              value={r.color}
              onChange={(e) => setField(val, 'color', e.target.value)}
              className="h-6 w-6 max-md:h-[34px] max-md:w-[34px] shrink-0 cursor-pointer appearance-none rounded border-0 bg-transparent p-0 [&::-webkit-color-swatch-wrapper]:p-0 [&::-webkit-color-swatch]:rounded-sm [&::-webkit-color-swatch]:border-0"
            />
            <input
              value={r.color}
              maxLength={7}
              pattern="^#[0-9a-fA-F]{6}$"
              onChange={(e) => setField(val, 'color', e.target.value)}
              className="h-full w-full min-w-0 border-0 bg-transparent p-0 font-mono text-[0.8rem] outline-none"
            />
          </div>
        );
      },
    },
    {
      id: 'order',
      enableSorting: false,
      header: t('statuses.colOrder'),
      cell: ({ row }) => {
        const val = row.original.value!;
        const r = rows[val] ?? initRow(row.original);
        return (
          <Input
            type="number"
            className="w-16 px-2 text-[0.8rem] focus-visible:border-brand focus-visible:ring-1 focus-visible:ring-brand focus-visible:ring-offset-0"
            aria-label={t('statuses.colOrder')}
            min={0}
            value={r.order}
            onChange={(e) => setField(val, 'order', Number(e.target.value))}
          />
        );
      },
    },
  ];

  const actionsFor = (status: StatusAdminItem): RowActionItem[] => {
    const val = status.value!;
    const row = rows[val] ?? initRow(status);
    const items: RowActionItem[] = [
      { label: t('statuses.save'), icon: Save, disabled: isBusy || !row.label.trim(), onClick: () => save(val) },
    ];
    if (status.isOverridden) {
      items.push({ label: t('statuses.reset'), icon: RotateCcw, severity: 'danger', disabled: isBusy, onClick: () => setResetTarget(status) });
    }
    return items;
  };

  return (
    <div className="flex flex-col gap-4">
      <h1 className="text-[20px] font-semibold leading-7 tracking-[-0.01em]">{t('statuses.title')}</h1>

      <DataTable
        data={statuses}
        columns={columns}
        actions={actionsFor}
        actionsAriaLabel={t('statuses.colActions')}
        actionsHeader={t('statuses.colActions')}
        gutter
        emptyIcon={Tag}
        emptyMessage={t('statuses.empty')}
        emptyHint={t('statuses.emptyHint')}
      />

      {/* Reset confirmation */}
      <ConfirmDialog
        open={!!resetTarget}
        message={t('statuses.confirmReset', {
          name: resetTarget?.label ?? resetTarget?.name ?? '',
        })}
        confirmLabel={t('statuses.reset')}
        confirmColor="warn"
        onConfirm={confirmReset}
        onCancel={() => setResetTarget(null)}
      />
    </div>
  );
}
