// vue/src/features/auth/ForgotPasswordPage.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { useI18n } from 'vue-i18n';
// @ts-ignore composable ships in the client version published at deploy (>=1.0.8)
import { usePostApiAuthForgotPassword } from '@moamen-ui/pointer-vue';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

const { t } = useI18n();
const router = useRouter();

const forgotMutation = usePostApiAuthForgotPassword();

const email = ref('');
const loading = ref(false);
const submitted = ref(false);

async function onSubmit() {
  if (!email.value) return;
  loading.value = true;
  try {
    await forgotMutation.mutateAsync({ data: { email: email.value } });
  } catch {
    // Always show success — never reveal whether the email exists.
  } finally {
    loading.value = false;
    submitted.value = true;
  }
}
</script>

<template>
  <div class="flex min-h-screen items-center justify-center bg-secondary p-4">
    <Card class="w-[380px] max-w-[92vw]">
      <CardContent class="flex flex-col gap-5 p-6">
        <h1 class="text-center text-xl font-bold">{{ t('auth.forgotTitle') }}</h1>

        <!-- Success state — always shown after submit -->
        <div v-if="submitted" class="flex flex-col gap-4 text-center">
          <p class="text-sm text-muted-foreground">{{ t('auth.forgotSent') }}</p>
          <Button variant="outline" @click="router.push('/login')">
            {{ t('auth.backToLogin') }}
          </Button>
        </div>

        <!-- Request form -->
        <form v-else class="flex flex-col gap-4" @submit.prevent="onSubmit">
          <div class="flex flex-col gap-2">
            <Label for="forgot-email">{{ t('login.email') }}</Label>
            <Input
              id="forgot-email"
              v-model="email"
              type="email"
              autocomplete="email"
              required
            />
          </div>
          <Button
            type="submit"
            class="mt-1"
            :disabled="loading || !email"
          >
            {{ t('auth.forgotSubmit') }}
          </Button>
          <Button variant="ghost" size="sm" @click="router.push('/login')">
            {{ t('auth.backToLogin') }}
          </Button>
        </form>
      </CardContent>
    </Card>
  </div>
</template>

// react/src/features/auth/ForgotPasswordPage.tsx
// ForgotPasswordPage — collects an email and calls POST /api/auth/forgot-password.
// Always shows the same neutral confirmation to avoid email enumeration.
import { useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { usePostApiAuthForgotPassword } from '@moamen-ui/pointer-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

export function ForgotPasswordPage() {
  const { t } = useTranslation();
  const [email, setEmail] = useState('');
  const [done, setDone] = useState(false);

  const forgotMut = usePostApiAuthForgotPassword();

  function onSubmit(e: FormEvent) {
    e.preventDefault();
    if (!email.trim()) return;
    forgotMut.mutate(
      { data: { email: email.trim() } },
      {
        onSuccess: () => setDone(true),
        // Always show the same confirmation on success OR error to avoid leaking
        // whether the address is registered.
        onError: () => setDone(true),
      },
    );
  }

  return (
    <div className="flex min-h-screen items-center justify-center bg-secondary p-4">
      <Card className="w-[380px] max-w-[92vw]">
        <CardContent className="flex flex-col gap-5 p-6">
          <h1 className="text-center text-xl font-bold">{t('auth.forgotTitle')}</h1>

          {done ? (
            <>
              <p className="text-center text-sm text-muted-foreground">{t('auth.forgotSent')}</p>
              <Link to="/login" className="text-center text-sm text-brand hover:underline">
                {t('auth.backToLogin')}
              </Link>
            </>
          ) : (
            <form onSubmit={onSubmit} className="flex flex-col gap-4">
              <div className="flex flex-col gap-2">
                <Label htmlFor="forgot-email">{t('login.email')}</Label>
                <Input
                  id="forgot-email"
                  type="email"
                  autoComplete="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                  autoFocus
                />
              </div>
              <Button
                type="submit"
                className="mt-1"
                disabled={forgotMut.isPending || !email.trim()}
              >
                {t('auth.forgotSubmit')}
              </Button>
              <Link to="/login" className="text-center text-sm text-muted-foreground hover:underline">
                {t('auth.backToLogin')}
              </Link>
            </form>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
