// vue/src/features/auth/ResetPasswordPage.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import { useI18n } from 'vue-i18n';
// @ts-ignore composable ships in the client version published at deploy (>=1.0.8)
import { usePostApiAuthResetPassword } from '@moamen-ui/pointer-vue';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { PasswordInput } from '@/components/ui/password-input';
import { Label } from '@/components/ui/label';
import { extractMessage } from '@/lib/error';

const { t } = useI18n();
const router = useRouter();
const route = useRoute();

const resetMutation = usePostApiAuthResetPassword();

const token = computed(() => (route.query.token as string | undefined) ?? '');

const newPassword = ref('');
const confirmPassword = ref('');
const loading = ref(false);
const error = ref<string | null>(null);
const done = ref(false);

const canSubmit = computed(
  () =>
    !!token.value &&
    newPassword.value.length >= 8 &&
    newPassword.value === confirmPassword.value,
);

async function onSubmit() {
  if (!canSubmit.value) return;
  loading.value = true;
  error.value = null;
  try {
    await resetMutation.mutateAsync({ data: { token: token.value, newPassword: newPassword.value } });
    done.value = true;
    await router.replace('/login');
  } catch (err) {
    error.value = extractMessage(err) || t('auth.resetInvalid');
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <div class="flex min-h-screen items-center justify-center bg-secondary p-4">
    <Card class="w-[380px] max-w-[92vw]">
      <CardContent class="flex flex-col gap-5 p-6">
        <h1 class="text-center text-xl font-bold">{{ t('auth.resetTitle') }}</h1>

        <!-- No token in URL -->
        <div v-if="!token" class="flex flex-col gap-4 text-center">
          <p class="text-sm text-destructive">{{ t('auth.resetInvalid') }}</p>
          <Button variant="outline" @click="router.push('/login')">
            {{ t('auth.backToLogin') }}
          </Button>
        </div>

        <!-- Success flash (briefly shown before router.replace fires) -->
        <div v-else-if="done" class="flex flex-col gap-4 text-center">
          <p class="text-sm text-green-600 dark:text-green-400">{{ t('auth.resetDone') }}</p>
        </div>

        <!-- Reset form -->
        <form v-else class="flex flex-col gap-4" @submit.prevent="onSubmit">
          <div class="flex flex-col gap-2">
            <Label for="new-password">{{ t('auth.newPassword') }}</Label>
            <PasswordInput
              id="new-password"
              v-model="newPassword"
              autocomplete="new-password"
              minlength="8"
              required
            />
          </div>
          <div class="flex flex-col gap-2">
            <Label for="confirm-password">{{ t('auth.confirmPassword') }}</Label>
            <PasswordInput
              id="confirm-password"
              v-model="confirmPassword"
              autocomplete="new-password"
              minlength="8"
              required
            />
          </div>
          <p v-if="error" class="text-sm text-destructive">{{ error }}</p>
          <Button
            type="submit"
            class="mt-1"
            :disabled="loading || !canSubmit"
          >
            {{ t('auth.resetSubmit') }}
          </Button>
          <Button variant="ghost" size="sm" @click="router.push('/login')">
            {{ t('auth.backToLogin') }}
          </Button>
        </form>
      </CardContent>
    </Card>
  </div>
</template>

// react/src/features/auth/ResetPasswordPage.tsx
// ResetPasswordPage — reads ?token= from the URL, collects a new password,
// and calls POST /api/auth/reset-password. On success redirects to /login with
// a state message; on error shows the API message.
import { useState, type FormEvent } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { usePostApiAuthResetPassword } from '@moamen-ui/pointer-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { PasswordInput } from '@/components/ui/password-input';
import { Label } from '@/components/ui/label';
import { extractMessage } from '@/lib/error';

const MIN_PASSWORD_LENGTH = 8;

export function ResetPasswordPage() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const token = searchParams.get('token') ?? '';

  const [newPassword, setNewPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [validationError, setValidationError] = useState<string | null>(null);
  const [apiError, setApiError] = useState<string | null>(null);

  const resetMut = usePostApiAuthResetPassword();

  // If no token in URL, show invalid link message immediately.
  if (!token) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-secondary p-4">
        <Card className="w-[380px] max-w-[92vw]">
          <CardContent className="flex flex-col gap-5 p-6">
            <h1 className="text-center text-xl font-bold">{t('auth.resetTitle')}</h1>
            <p className="text-center text-sm text-destructive">{t('auth.resetInvalid')}</p>
            <Link to="/login" className="text-center text-sm text-brand hover:underline">
              {t('auth.backToLogin')}
            </Link>
          </CardContent>
        </Card>
      </div>
    );
  }

  function onSubmit(e: FormEvent) {
    e.preventDefault();
    setValidationError(null);
    setApiError(null);

    if (newPassword.length < MIN_PASSWORD_LENGTH) {
      setValidationError(`Password must be at least ${MIN_PASSWORD_LENGTH} characters.`);
      return;
    }
    if (newPassword !== confirmPassword) {
      setValidationError('Passwords do not match.');
      return;
    }

    resetMut.mutate(
      { data: { token, newPassword } },
      {
        onSuccess: () => {
          navigate('/login', {
            replace: true,
            state: { message: t('auth.resetDone') },
          });
        },
        onError: (err: unknown) => {
          setApiError(extractMessage(err));
        },
      },
    );
  }

  return (
    <div className="flex min-h-screen items-center justify-center bg-secondary p-4">
      <Card className="w-[380px] max-w-[92vw]">
        <CardContent className="flex flex-col gap-5 p-6">
          <h1 className="text-center text-xl font-bold">{t('auth.resetTitle')}</h1>

          <form onSubmit={onSubmit} className="flex flex-col gap-4">
            <div className="flex flex-col gap-2">
              <Label htmlFor="new-password">{t('auth.newPassword')}</Label>
              <PasswordInput
                id="new-password"
                autoComplete="new-password"
                value={newPassword}
                onChange={(e) => {
                  setNewPassword(e.target.value);
                  setValidationError(null);
                }}
                required
                autoFocus
              />
            </div>
            <div className="flex flex-col gap-2">
              <Label htmlFor="confirm-password">{t('auth.confirmPassword')}</Label>
              <PasswordInput
                id="confirm-password"
                autoComplete="new-password"
                value={confirmPassword}
                onChange={(e) => {
                  setConfirmPassword(e.target.value);
                  setValidationError(null);
                }}
                required
              />
            </div>
            {validationError && (
              <p className="text-sm text-destructive">{validationError}</p>
            )}
            {apiError && <p className="text-sm text-destructive">{apiError}</p>}
            <Button
              type="submit"
              className="mt-1"
              disabled={resetMut.isPending || !newPassword || !confirmPassword}
            >
              {t('auth.resetSubmit')}
            </Button>
            <Link to="/login" className="text-center text-sm text-muted-foreground hover:underline">
              {t('auth.backToLogin')}
            </Link>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
