// vue/src/features/projects/ProjectsPage.vue
<script setup lang="ts">
import { computed, reactive, ref } from 'vue';
import { useI18n } from 'vue-i18n';
import { useQueryClient } from '@tanstack/vue-query';
import {
  useGetApiAdminProjects,
  usePostApiAdminProjects,
  usePatchApiAdminProjectsId,
  getGetApiAdminProjectsQueryKey,
  getApiProjectsKeyExport,
  usePostApiProjectsKeyImport,
  AXIOS_INSTANCE,
  type ProjectResponse,
  type ImportResultDto,
  type PredefinedActionResponse,
} from '@moamen-ui/pointer-vue';
import { Plus, Ban, CheckCircle2, Download, Upload, Trash2, PlusCircle, Pencil } from 'lucide-vue-next';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { extractMessage } from '@/lib/error';
import { cn } from '@/lib/utils';
import { confirm } from '@/composables/useConfirm';
import { toast } from '@/composables/useToast';
import { useAuth } from '@/composables/useAuth';

const { t } = useI18n();

const queryClient = useQueryClient();

const { isSuperAdmin } = useAuth();

const { data, isLoading } = useGetApiAdminProjects();
const projects = computed<ProjectResponse[]>(() => data.value ?? []);
const busy = ref(false);
const loading = computed(() => isLoading.value || busy.value);

const createProject = usePostApiAdminProjects();
const updateProject = usePatchApiAdminProjectsId();

function fail(e: unknown) {
  busy.value = false;
  toast(extractMessage(e));
}
function reload() {
  void queryClient.invalidateQueries({ queryKey: getGetApiAdminProjectsQueryKey() });
}

// ── Add project ───────────────────────────────────────────────────────
const addOpen = ref(false);
const addForm = reactive({ key: '', name: '' });
const addInvalid = computed(() => !addForm.key.trim() || !addForm.name.trim());
const addActions = ref<Array<{ text: string; prompt: string }>>([]);

function openAdd() {
  addForm.key = '';
  addForm.name = '';
  addActions.value = [];
  addOpen.value = true;
}

function addActionRow() {
  addActions.value.push({ text: '', prompt: '' });
}

function removeActionRow(index: number) {
  addActions.value.splice(index, 1);
}

async function addProject() {
  if (addInvalid.value) return;
  busy.value = true;
  try {
    await createProject.mutateAsync({
      data: {
        ...addForm,
        predefinedActions: addActions.value.map((a, i) => ({
          text: a.text,
          prompt: a.prompt,
          sortOrder: i,
          isActive: true,
        })),
      },
    });
    busy.value = false;
    addOpen.value = false;
    reload();
  } catch (e) {
    fail(e);
  }
}

// ── Active toggle ─────────────────────────────────────────────────────
async function toggleActive(project: ProjectResponse) {
  if (!project.isActive) {
    await patchActive(project, true);
    return;
  }
  const ok = await confirm({
    message: t('common.confirmDisable', { name: project.key }),
    confirmLabel: t('common.disable'),
    confirmVariant: 'destructive',
  });
  if (ok) await patchActive(project, false);
}

async function patchActive(project: ProjectResponse, isActive: boolean) {
  busy.value = true;
  try {
    await updateProject.mutateAsync({ id: project.id!, data: { isActive } });
    busy.value = false;
    reload();
  } catch (e) {
    fail(e);
  }
}

// ── Export ────────────────────────────────────────────────────────────
async function exportProject(project: ProjectResponse) {
  try {
    const exportData = await getApiProjectsKeyExport(project.key!);
    const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `pointer-comments-${project.key}.json`;
    a.click();
    URL.revokeObjectURL(url);
    toast(t('exportImport.exported'));
  } catch (e) {
    fail(e);
  }
}

// ── Import ────────────────────────────────────────────────────────────
const importDialogOpen = ref(false);
const importTargetProject = ref<ProjectResponse | null>(null);
const importFile = ref<File | null>(null);
const importResult = ref<ImportResultDto | null>(null);

// usePostApiProjectsKeyImport is used for lifecycle management; body must be
// forwarded via AXIOS_INSTANCE because the generated function's signature
// does not accept a request body (orval emitted no body parameter for this endpoint).
const importMutation = usePostApiProjectsKeyImport({
  mutation: {
    mutationFn: async ({ key }: { key: string }) => {
      const text = await importFile.value!.text();
      const body = JSON.parse(text);
      const res = await AXIOS_INSTANCE.post(
        `/api/projects/${key}/import`,
        body,
        { headers: { 'Content-Type': 'application/json' } },
      );
      const result: ImportResultDto = res.data?.data ?? res.data;
      return result as ImportResultDto;
    },
  },
});

function openImport(project: ProjectResponse) {
  importTargetProject.value = project;
  importFile.value = null;
  importResult.value = null;
  importDialogOpen.value = true;
}

async function submitImport() {
  if (!importFile.value || !importTargetProject.value) return;
  busy.value = true;
  try {
    const result = await importMutation.mutateAsync({ key: importTargetProject.value.key! });
    importResult.value = result;
    const msg = t('exportImport.importCounts', {
      comments: result.importedComments ?? 0,
      replies: result.importedReplies ?? 0,
    });
    toast(`${t('exportImport.imported')} ${msg}`);
    if (result.warnings?.length) {
      result.warnings.forEach((w) => toast(w));
    }
    importDialogOpen.value = false;
    reload();
  } catch (e) {
    fail(e);
  } finally {
    busy.value = false;
  }
}

// ── Edit project ──────────────────────────────────────────────────────
interface EditableAction {
  id?: number;
  text: string;
  prompt: string;
}

const editOpen = ref(false);
const editProject = ref<ProjectResponse | null>(null);
const editName = ref('');
const editActions = ref<EditableAction[]>([]);
const editInvalid = computed(() => !editName.value.trim());

const patchProject = usePatchApiAdminProjectsId();

function openEdit(project: ProjectResponse) {
  editProject.value = project;
  editName.value = project.name ?? '';
  editActions.value = (project.predefinedActions ?? []).map((a: PredefinedActionResponse) => ({
    id: a.id,
    text: a.text ?? '',
    prompt: a.prompt ?? '',
  }));
  editOpen.value = true;
}

function addEditActionRow() {
  editActions.value.push({ text: '', prompt: '' });
}

function removeEditActionRow(index: number) {
  editActions.value.splice(index, 1);
}

async function saveEdit() {
  if (editInvalid.value || !editProject.value) return;
  busy.value = true;
  try {
    await patchProject.mutateAsync({
      id: editProject.value.id!,
      data: {
        name: editName.value,
        predefinedActions: editActions.value.map((a, i) => ({
          ...(a.id != null ? { id: a.id } : {}),
          text: a.text,
          prompt: a.prompt,
          sortOrder: i,
          isActive: true,
        })),
      },
    });
    busy.value = false;
    editOpen.value = false;
    toast(t('projects.saved'));
    reload();
  } catch (e) {
    fail(e);
  }
}
</script>

<template>
  <div class="flex flex-col gap-4">
    <div class="flex items-center justify-between gap-3">
      <h2 class="text-lg font-semibold">{{ t('projects.title') }}</h2>
      <Button @click="openAdd">
        <Plus class="h-4 w-4" /> {{ t('projects.addProject') }}
      </Button>
    </div>

    <div v-if="loading" class="h-0.5 w-full overflow-hidden rounded bg-muted">
      <div class="h-full w-1/3 animate-pulse bg-primary" />
    </div>

    <Card>
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>{{ t('projects.key') }}</TableHead>
            <TableHead>{{ t('projects.name') }}</TableHead>
            <TableHead>{{ t('projects.status') }}</TableHead>
            <TableHead>{{ t('projects.actions') }}</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          <TableRow v-for="project in projects" :key="project.id">
            <TableCell>
              <code class="rounded bg-muted px-1.5 py-0.5 text-xs">{{ project.key }}</code>
            </TableCell>
            <TableCell>{{ project.name }}</TableCell>
            <TableCell>
              <span :class="cn('chip', project.isActive ? 'chip-active' : 'chip-disabled')">
                {{ t(project.isActive ? 'common.active' : 'common.disabled') }}
              </span>
            </TableCell>
            <TableCell class="flex flex-wrap items-center gap-2">
              <Button
                :variant="project.isActive ? 'destructive' : 'default'"
                size="sm"
                :disabled="loading"
                @click="toggleActive(project)"
              >
                <component :is="project.isActive ? Ban : CheckCircle2" class="h-4 w-4" />
                {{ project.isActive ? t('common.disable') : t('common.enable') }}
              </Button>
              <Button variant="outline" size="sm" :disabled="loading" @click="openEdit(project)">
                <Pencil class="h-4 w-4" /> {{ t('projects.edit') }}
              </Button>
              <Button variant="outline" size="sm" :disabled="loading" @click="exportProject(project)">
                <Download class="h-4 w-4" /> {{ t('exportImport.export') }}
              </Button>
              <Button v-if="isSuperAdmin" variant="outline" size="sm" :disabled="loading" @click="openImport(project)">
                <Upload class="h-4 w-4" /> {{ t('exportImport.import') }}
              </Button>
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </Card>
  </div>

  <!-- Add project dialog -->
  <Dialog v-model:open="addOpen">
    <DialogContent class="max-w-[440px]">
      <DialogHeader>
        <DialogTitle>{{ t('projects.addProject') }}</DialogTitle>
      </DialogHeader>
      <form class="flex flex-col gap-3 pt-2" @submit.prevent="addProject">
        <div class="flex flex-col gap-2">
          <Label for="p-key">{{ t('projects.key') }}</Label>
          <Input id="p-key" v-model="addForm.key" />
        </div>
        <div class="flex flex-col gap-2">
          <Label for="p-name">{{ t('projects.name') }}</Label>
          <Input id="p-name" v-model="addForm.name" />
        </div>

        <!-- Predefined actions section -->
        <div class="flex flex-col gap-2">
          <p class="text-xs text-muted-foreground">{{ t('predefined.projectHelp') }}</p>
          <div class="flex items-center justify-between">
            <span class="text-sm font-medium">{{ t('predefined.section') }}</span>
            <Button type="button" variant="outline" size="sm" @click="addActionRow">
              <PlusCircle class="h-4 w-4" /> {{ t('predefined.add') }}
            </Button>
          </div>
          <p v-if="addActions.length === 0" class="text-xs text-muted-foreground italic">{{ t('predefined.empty') }}</p>
          <div v-for="(action, idx) in addActions" :key="idx" class="flex flex-col gap-1 rounded-md border p-2">
            <div class="flex items-center justify-between">
              <span class="text-xs text-muted-foreground">#{{ idx + 1 }}</span>
              <Button type="button" variant="ghost" size="icon" @click="removeActionRow(idx)">
                <Trash2 class="h-4 w-4 text-destructive" />
              </Button>
            </div>
            <Label :for="'add-act-text-' + idx">{{ t('predefined.text') }}</Label>
            <Input :id="'add-act-text-' + idx" v-model="action.text" />
            <Label :for="'add-act-prompt-' + idx">{{ t('predefined.prompt') }}</Label>
            <textarea
              :id="'add-act-prompt-' + idx"
              v-model="action.prompt"
              rows="2"
              class="flex w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm resize-none"
            />
          </div>
        </div>
      </form>
      <DialogFooter>
        <Button variant="outline" @click="addOpen = false">{{ t('common.cancel') }}</Button>
        <Button :disabled="addInvalid || loading" @click="addProject">
          <Plus class="h-4 w-4" /> {{ t('projects.addProject') }}
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>

  <!-- Edit project dialog -->
  <Dialog v-model:open="editOpen">
    <DialogContent class="max-w-[440px]">
      <DialogHeader>
        <DialogTitle>{{ t('projects.editTitle') }}</DialogTitle>
      </DialogHeader>
      <form class="flex flex-col gap-3 pt-2" @submit.prevent="saveEdit">
        <div class="flex flex-col gap-2">
          <Label for="edit-name">{{ t('projects.name') }}</Label>
          <Input id="edit-name" v-model="editName" />
        </div>

        <!-- Predefined actions section -->
        <div class="flex flex-col gap-2">
          <p class="text-xs text-muted-foreground">{{ t('predefined.projectHelp') }}</p>
          <div class="flex items-center justify-between">
            <span class="text-sm font-medium">{{ t('predefined.section') }}</span>
            <Button type="button" variant="outline" size="sm" @click="addEditActionRow">
              <PlusCircle class="h-4 w-4" /> {{ t('predefined.add') }}
            </Button>
          </div>
          <p v-if="editActions.length === 0" class="text-xs text-muted-foreground italic">{{ t('predefined.empty') }}</p>
          <div v-for="(action, idx) in editActions" :key="idx" class="flex flex-col gap-1 rounded-md border p-2">
            <div class="flex items-center justify-between">
              <span class="text-xs text-muted-foreground">#{{ idx + 1 }}</span>
              <Button type="button" variant="ghost" size="icon" @click="removeEditActionRow(idx)">
                <Trash2 class="h-4 w-4 text-destructive" />
              </Button>
            </div>
            <Label :for="'edit-act-text-' + idx">{{ t('predefined.text') }}</Label>
            <Input :id="'edit-act-text-' + idx" v-model="action.text" />
            <Label :for="'edit-act-prompt-' + idx">{{ t('predefined.prompt') }}</Label>
            <textarea
              :id="'edit-act-prompt-' + idx"
              v-model="action.prompt"
              rows="2"
              class="flex w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm resize-none"
            />
          </div>
        </div>
      </form>
      <DialogFooter>
        <Button variant="outline" @click="editOpen = false">{{ t('common.cancel') }}</Button>
        <Button :disabled="editInvalid || loading" @click="saveEdit">
          {{ t('common.save') }}
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>

  <!-- Import dialog -->
  <Dialog v-model:open="importDialogOpen">
    <DialogContent class="max-w-[440px]">
      <DialogHeader>
        <DialogTitle>{{ t('exportImport.importTitle') }}</DialogTitle>
      </DialogHeader>
      <p class="text-sm text-muted-foreground">{{ t('exportImport.importHint') }}</p>
      <form class="flex flex-col gap-3 pt-2" @submit.prevent="submitImport">
        <div class="flex flex-col gap-2">
          <Label for="import-file">{{ t('exportImport.import') }}</Label>
          <input
            id="import-file"
            type="file"
            accept=".json"
            class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm"
            @change="(e) => { importFile = (e.target as HTMLInputElement).files?.[0] ?? null; }"
          />
        </div>
      </form>
      <DialogFooter>
        <Button variant="outline" @click="importDialogOpen = false">{{ t('common.cancel') }}</Button>
        <Button :disabled="!importFile || loading" @click="submitImport">
          {{ t('exportImport.import') }}
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>

// react/src/features/projects/ProjectsPage.tsx
// Projects admin page. React port of angular/.../projects/projects.component.ts.
// list (key, name, status) + add project + enable/disable (disable confirmed).
// Phase B additions: export/import comments, predefined actions in add/edit forms.
import { useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useQueryClient } from '@tanstack/react-query';
import {
  useGetApiAdminProjects,
  usePostApiAdminProjects,
  usePatchApiAdminProjectsId,
  usePostApiProjectsKeyImport,
  getGetApiAdminProjectsQueryKey,
  getApiProjectsKeyExport,
  type ProjectResponse,
  type PredefinedActionInput,
  type ExportFileDto,
} from '@moamen-ui/pointer-react';
import { Plus, Ban, CheckCircle2, Download, Upload, Trash2 } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { ConfirmDialog } from '@/components/ConfirmDialog';
import { useToast } from '@/components/ui/toast';
import { cn } from '@/lib/utils';
import { extractMessage } from '@/lib/error';
import { useAuth } from '@/lib/auth';

// Local row type for predefined actions in the form
interface PredefinedActionRow {
  _localId: number;
  id?: number;
  text: string;
  prompt: string;
}

let _nextLocalId = 1;
function nextLocalId() {
  return _nextLocalId++;
}

function emptyRow(): PredefinedActionRow {
  return { _localId: nextLocalId(), text: '', prompt: '' };
}

export function ProjectsPage() {
  const { t } = useTranslation();
  const { toast } = useToast();
  const qc = useQueryClient();
  const { isSuperAdmin } = useAuth();

  const { data: projects = [] } = useGetApiAdminProjects();

  const reload = () =>
    qc.invalidateQueries({ queryKey: getGetApiAdminProjectsQueryKey() });
  const onError = (e: unknown) => toast(extractMessage(e), 'error');

  // ---- Add project ----
  const [addOpen, setAddOpen] = useState(false);
  const [key, setKey] = useState('');
  const [name, setName] = useState('');
  const [addActions, setAddActions] = useState<PredefinedActionRow[]>([]);

  const addMut = usePostApiAdminProjects({
    mutation: {
      onSuccess: () => {
        setAddOpen(false);
        setKey('');
        setName('');
        setAddActions([]);
        reload();
      },
      onError,
    },
  });

  function openAdd() {
    setKey('');
    setName('');
    setAddActions([]);
    setAddOpen(true);
  }

  function addProject() {
    if (!key.trim() || !name.trim()) return;
    const predefinedActions: PredefinedActionInput[] = addActions.map((row, idx) => ({
      text: row.text,
      prompt: row.prompt,
      sortOrder: idx,
      isActive: true,
    }));
    addMut.mutate({
      data: {
        key: key.trim(),
        name: name.trim(),
        predefinedActions: predefinedActions.length > 0 ? predefinedActions : null,
      },
    });
  }

  // ---- Edit project (name + predefined actions) ----
  const [editOpen, setEditOpen] = useState(false);
  const [editProject, setEditProject] = useState<ProjectResponse | null>(null);
  const [editName, setEditName] = useState('');
  const [editActions, setEditActions] = useState<PredefinedActionRow[]>([]);

  const patchMut = usePatchApiAdminProjectsId({
    mutation: {
      onSuccess: () => {
        setEditOpen(false);
        toast(t('projects.saved'));
        reload();
      },
      onError,
    },
  });

  function openEdit(project: ProjectResponse) {
    setEditProject(project);
    setEditName(project.name ?? '');
    setEditActions(
      (project.predefinedActions ?? []).map((a) => ({
        _localId: nextLocalId(),
        id: a.id,
        text: a.text ?? '',
        prompt: a.prompt ?? '',
      })),
    );
    setEditOpen(true);
  }

  function saveEdit() {
    if (!editProject || !editName.trim()) return;
    const predefinedActions: PredefinedActionInput[] = editActions.map((row, idx) => ({
      id: row.id ?? null,
      text: row.text,
      prompt: row.prompt,
      sortOrder: idx,
      isActive: true,
    }));
    patchMut.mutate({
      id: editProject.id!,
      data: {
        name: editName.trim(),
        predefinedActions: predefinedActions,
      },
    });
  }

  // ---- Enable / disable ----
  const toggleMut = usePatchApiAdminProjectsId({
    mutation: {
      onSuccess: () => reload(),
      onError,
    },
  });

  const [confirmProject, setConfirmProject] = useState<ProjectResponse | null>(null);

  function toggleActive(project: ProjectResponse) {
    if (!project.isActive) {
      toggleMut.mutate({ id: project.id!, data: { isActive: true } });
      return;
    }
    setConfirmProject(project);
  }
  function confirmDisable() {
    const p = confirmProject;
    setConfirmProject(null);
    if (p) toggleMut.mutate({ id: p.id!, data: { isActive: false } });
  }

  // ---- Export ----
  async function handleExport(project: ProjectResponse) {
    try {
      const exportData = await getApiProjectsKeyExport(project.key!);
      const blob = new Blob([JSON.stringify(exportData, null, 2)], {
        type: 'application/json',
      });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `pointer-comments-${project.key}.json`;
      a.click();
      URL.revokeObjectURL(url);
      toast(t('exportImport.exported'));
    } catch (e) {
      toast(extractMessage(e), 'error');
    }
  }

  // ---- Import ----
  const [importOpen, setImportOpen] = useState(false);
  const [importProject, setImportProject] = useState<ProjectResponse | null>(null);
  const [importFile, setImportFile] = useState<File | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const importMut = usePostApiProjectsKeyImport({
    mutation: {
      onSuccess: (result) => {
        const countMsg = t('exportImport.importCounts', {
          comments: result.importedComments ?? 0,
          replies: result.importedReplies ?? 0,
        });
        toast(`${t('exportImport.imported')} ${countMsg}`);
        if (result.warnings && result.warnings.length > 0) {
          result.warnings.forEach((w) => toast(w, 'error'));
        }
        setImportOpen(false);
        setImportFile(null);
        reload();
      },
      onError,
    },
  });

  function openImport(project: ProjectResponse) {
    setImportProject(project);
    setImportFile(null);
    if (fileInputRef.current) fileInputRef.current.value = '';
    setImportOpen(true);
  }

  async function handleImport() {
    if (!importFile || !importProject) return;
    const text = await importFile.text();
    const payload = JSON.parse(text) as ExportFileDto;
    importMut.mutate({ key: importProject.key!, data: payload });
  }

  // ---- Predefined actions helpers ----
  function addActionRow(
    rows: PredefinedActionRow[],
    setRows: (r: PredefinedActionRow[]) => void,
  ) {
    setRows([...rows, emptyRow()]);
  }

  function updateActionRow(
    rows: PredefinedActionRow[],
    setRows: (r: PredefinedActionRow[]) => void,
    localId: number,
    field: 'text' | 'prompt',
    value: string,
  ) {
    setRows(rows.map((r) => (r._localId === localId ? { ...r, [field]: value } : r)));
  }

  function removeActionRow(
    rows: PredefinedActionRow[],
    setRows: (r: PredefinedActionRow[]) => void,
    localId: number,
  ) {
    setRows(rows.filter((r) => r._localId !== localId));
  }

  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-center justify-between gap-3">
        <h2 className="text-lg font-semibold">{t('projects.title')}</h2>
        <Button onClick={openAdd}>
          <Plus className="h-4 w-4" />
          {t('projects.addProject')}
        </Button>
      </div>

      <Card>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>{t('projects.key')}</TableHead>
              <TableHead>{t('projects.name')}</TableHead>
              <TableHead>{t('projects.status')}</TableHead>
              <TableHead>{t('projects.actions')}</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {projects.map((project) => (
              <TableRow key={project.id}>
                <TableCell>
                  <code className="rounded bg-muted px-1.5 py-0.5 text-xs">{project.key}</code>
                </TableCell>
                <TableCell>{project.name}</TableCell>
                <TableCell>
                  <span className={cn('chip', project.isActive ? 'chip-active' : 'chip-disabled')}>
                    {t(project.isActive ? 'common.active' : 'common.disabled')}
                  </span>
                </TableCell>
                <TableCell>
                  <div className="flex flex-wrap items-center gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => openEdit(project)}
                    >
                      {t('projects.edit')}
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => toggleActive(project)}
                      disabled={toggleMut.isPending}
                    >
                      {project.isActive ? <Ban className="h-4 w-4" /> : <CheckCircle2 className="h-4 w-4" />}
                      {t(project.isActive ? 'common.disable' : 'common.enable')}
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleExport(project)}
                    >
                      <Download className="h-4 w-4" />
                      {t('exportImport.export')}
                    </Button>
                    {isSuperAdmin && (
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => openImport(project)}
                      >
                        <Upload className="h-4 w-4" />
                        {t('exportImport.import')}
                      </Button>
                    )}
                  </div>
                </TableCell>
              </TableRow>
            ))}
            {projects.length === 0 && (
              <TableRow>
                <TableCell colSpan={4} className="py-10 text-center text-muted-foreground">
                  {t('projects.empty')}
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </Card>

      {/* Add project dialog */}
      <Dialog open={addOpen} onOpenChange={setAddOpen}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle>{t('projects.addProject')}</DialogTitle>
          </DialogHeader>
          <div className="flex flex-col gap-4 pt-1">
            <div className="flex flex-col gap-2">
              <Label htmlFor="project-key">{t('projects.key')}</Label>
              <Input
                id="project-key"
                value={key}
                onChange={(e) => setKey(e.target.value)}
                autoFocus
              />
            </div>
            <div className="flex flex-col gap-2">
              <Label htmlFor="project-name">{t('projects.name')}</Label>
              <Input
                id="project-name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && addProject()}
              />
            </div>

            {/* Predefined actions */}
            <div className="flex flex-col gap-2">
              <h4 className="text-sm font-semibold">{t('predefined.section')}</h4>
              <p className="text-xs text-muted-foreground">{t('predefined.projectHelp')}</p>
              {addActions.length === 0 && (
                <p className="text-xs text-muted-foreground">{t('predefined.empty')}</p>
              )}
              {addActions.map((row) => (
                <div key={row._localId} className="flex flex-col gap-1 rounded-md border border-border p-3">
                  <div className="flex items-center gap-2">
                    <div className="flex-1">
                      <Label className="text-xs">{t('predefined.text')}</Label>
                      <Input
                        value={row.text}
                        onChange={(e) =>
                          updateActionRow(addActions, setAddActions, row._localId, 'text', e.target.value)
                        }
                        className="mt-1"
                      />
                    </div>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="mt-5 h-7 w-7 shrink-0 text-destructive"
                      onClick={() => removeActionRow(addActions, setAddActions, row._localId)}
                      type="button"
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                  <Label className="text-xs">{t('predefined.prompt')}</Label>
                  <textarea
                    value={row.prompt}
                    onChange={(e) =>
                      updateActionRow(addActions, setAddActions, row._localId, 'prompt', e.target.value)
                    }
                    rows={2}
                    className="w-full resize-none rounded-md border border-input bg-background px-3 py-1.5 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                  />
                </div>
              ))}
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => addActionRow(addActions, setAddActions)}
              >
                <Plus className="h-4 w-4" />
                {t('predefined.add')}
              </Button>
            </div>
          </div>
          <DialogFooter className="gap-2">
            <Button variant="outline" onClick={() => setAddOpen(false)}>
              {t('common.cancel')}
            </Button>
            <Button
              disabled={!key.trim() || !name.trim() || addMut.isPending}
              onClick={addProject}
            >
              <Plus className="h-4 w-4" />
              {t('projects.addProject')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Edit project dialog */}
      <Dialog open={editOpen} onOpenChange={setEditOpen}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle>{t('projects.editTitle')}</DialogTitle>
          </DialogHeader>
          <div className="flex flex-col gap-4 pt-1">
            <div className="flex flex-col gap-2">
              <Label htmlFor="edit-project-name">{t('projects.name')}</Label>
              <Input
                id="edit-project-name"
                value={editName}
                onChange={(e) => setEditName(e.target.value)}
                autoFocus
              />
            </div>

            {/* Predefined actions */}
            <div className="flex flex-col gap-2">
              <h4 className="text-sm font-semibold">{t('predefined.section')}</h4>
              <p className="text-xs text-muted-foreground">{t('predefined.projectHelp')}</p>
              {editActions.length === 0 && (
                <p className="text-xs text-muted-foreground">{t('predefined.empty')}</p>
              )}
              {editActions.map((row) => (
                <div key={row._localId} className="flex flex-col gap-1 rounded-md border border-border p-3">
                  <div className="flex items-center gap-2">
                    <div className="flex-1">
                      <Label className="text-xs">{t('predefined.text')}</Label>
                      <Input
                        value={row.text}
                        onChange={(e) =>
                          updateActionRow(editActions, setEditActions, row._localId, 'text', e.target.value)
                        }
                        className="mt-1"
                      />
                    </div>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="mt-5 h-7 w-7 shrink-0 text-destructive"
                      onClick={() => removeActionRow(editActions, setEditActions, row._localId)}
                      type="button"
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                  <Label className="text-xs">{t('predefined.prompt')}</Label>
                  <textarea
                    value={row.prompt}
                    onChange={(e) =>
                      updateActionRow(editActions, setEditActions, row._localId, 'prompt', e.target.value)
                    }
                    rows={2}
                    className="w-full resize-none rounded-md border border-input bg-background px-3 py-1.5 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                  />
                </div>
              ))}
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => addActionRow(editActions, setEditActions)}
              >
                <Plus className="h-4 w-4" />
                {t('predefined.add')}
              </Button>
            </div>
          </div>
          <DialogFooter className="gap-2">
            <Button variant="outline" onClick={() => setEditOpen(false)}>
              {t('common.cancel')}
            </Button>
            <Button
              disabled={!editName.trim() || patchMut.isPending}
              onClick={saveEdit}
            >
              {t('common.save')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Import dialog — super-admin only */}
      {isSuperAdmin && (
        <Dialog open={importOpen} onOpenChange={setImportOpen}>
          <DialogContent className="max-w-md">
            <DialogHeader>
              <DialogTitle>{t('exportImport.importTitle')}</DialogTitle>
            </DialogHeader>
            <p className="text-sm text-muted-foreground">{t('exportImport.importHint')}</p>
            <div className="flex flex-col gap-2 pt-1">
              <Label htmlFor="import-file">{importProject?.name ?? ''}</Label>
              <input
                id="import-file"
                ref={fileInputRef}
                type="file"
                accept=".json"
                className="block w-full text-sm text-muted-foreground file:mr-3 file:rounded file:border file:border-border file:bg-background file:px-3 file:py-1 file:text-sm file:font-medium"
                onChange={(e) => setImportFile(e.target.files?.[0] ?? null)}
              />
            </div>
            <DialogFooter className="gap-2">
              <Button variant="outline" onClick={() => setImportOpen(false)}>
                {t('common.cancel')}
              </Button>
              <Button
                disabled={!importFile || importMut.isPending}
                onClick={handleImport}
              >
                <Upload className="h-4 w-4" />
                {t('exportImport.import')}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}

      {/* Disable confirmation */}
      <ConfirmDialog
        open={!!confirmProject}
        message={t('common.confirmDisable', { name: confirmProject?.key })}
        confirmLabel={t('common.disable')}
        confirmColor="warn"
        onConfirm={confirmDisable}
        onCancel={() => setConfirmProject(null)}
      />
    </div>
  );
}
