// react/src/components/shared/data-table/DataTable.tsx
import { useMemo, useState, type ReactNode } from 'react';
import {
  flexRender,
  getCoreRowModel,
  getFilteredRowModel,
  getPaginationRowModel,
  getSortedRowModel,
  useReactTable,
  type ColumnDef,
  type SortingState,
} from '@tanstack/react-table';
import {
  ArrowDown,
  ArrowUp,
  ArrowUpDown,
  ChevronLeft,
  ChevronRight,
  Search,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { useTranslation } from 'react-i18next';
import { RowActionsMenu } from '@/components/shared/RowActionsMenu';
import type { RowActionItem } from '@/components/shared/types';

export type DataTableProps<TData> = {
  data: TData[];
  /**
   * TanStack column defs — a column's native `cell` render fn is the per-column
   * custom-render slot (no separate template mechanism needed).
   */
  columns: ColumnDef<TData>[];
  /** Per-row actions; the callback is fully in charge of permission/feature gating
   *  (return [] to hide the menu for that row). Appended as a trailing column. */
  actions?: (row: TData) => RowActionItem[];
  /** aria-label for each row's kebab trigger — pass the page's translated actions
   *  key (e.g. t('roles.actions')), mirroring angular's actionsColumn.ariaLabel. */
  actionsAriaLabel?: string;
  /** Header label over the trailing actions column (blank when omitted) —
   *  angular's actionsColumn.header equivalent. */
  actionsHeader?: string;
  /** Renders a built-in search input above the table, wired to the global filter. */
  searchable?: boolean;
  searchPlaceholder?: string;
  /** Renders a small pagination footer under the table. */
  paginated?: boolean;
  /** When true, adds a gutter column (w-10, 1-based row numbers, mono, muted). */
  gutter?: boolean;
  emptyIcon?: React.ComponentType<{ className?: string }>;
  emptyMessage?: string;
  emptyHint?: string;
  /** Optional action (e.g. an "Add" button) rendered inside the empty state. */
  emptyAction?: ReactNode;
};

/**
 * The shared table shell every list page renders: TanStack Table supplies the
 * state/models only (headless) — the markup comes from the existing ui/ table
 * primitives. Sorting, global search and pagination are wired in as needed based
 * on the props, and an empty `data` array swaps the whole table for an empty state.
 */
export function DataTable<TData>({
  data,
  columns,
  actions,
  actionsAriaLabel,
  actionsHeader,
  searchable = false,
  searchPlaceholder,
  paginated = false,
  gutter = false,
  emptyMessage = '',
  emptyAction,
}: DataTableProps<TData>) {
  const { t } = useTranslation();
  const [sorting, setSorting] = useState<SortingState>([]);
  const [globalFilter, setGlobalFilter] = useState('');

  // Leading gutter column (row numbers, 1-based) if enabled.
  // Trailing synthetic actions column — right-aligned, never sortable.
  const effectiveColumns = useMemo<ColumnDef<TData>[]>(() => {
    const cols: ColumnDef<TData>[] = [];

    if (gutter) {
      cols.push({
        id: '__gutter__',
        enableSorting: false,
        enableGlobalFilter: false,
        header: () => '',
        cell: ({ row }) => (
          <div className="w-10 text-end font-mono text-[12px] text-faint-foreground">
            {row.index + 1}
          </div>
        ),
      });
    }

    cols.push(...columns);

    if (actions) {
      cols.push({
        id: '__actions__',
        enableSorting: false,
        enableGlobalFilter: false,
        header: () => actionsHeader ?? '',
        cell: ({ row }) => (
          <div className="flex justify-end">
            <RowActionsMenu
              items={actions(row.original)}
              ariaLabel={actionsAriaLabel}
            />
          </div>
        ),
      });
    }

    return cols;
  }, [columns, actions, actionsAriaLabel, actionsHeader, gutter]);

  const table = useReactTable({
    data,
    columns: effectiveColumns,
    state: { sorting, globalFilter },
    onSortingChange: setSorting,
    onGlobalFilterChange: setGlobalFilter,
    globalFilterFn: 'includesString',
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    ...(paginated ? { getPaginationRowModel: getPaginationRowModel<TData>() } : {}),
    initialState: { pagination: { pageSize: 10 } },
  });

  // When data is empty, render ghost rows in the table (§3 empty state grammar)
  if (data.length === 0) {
    return (
      <div className="flex flex-col gap-3">
        {searchable && (
          <div className="relative w-full max-w-sm">
            <Search className="pointer-events-none absolute start-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              value={globalFilter}
              onChange={(e) => setGlobalFilter(e.target.value)}
              placeholder={searchPlaceholder ?? t('common.search')}
              className="ps-9"
            />
          </div>
        )}

        <Card className="overflow-hidden">
          <Table>
            <TableHeader>
              {table.getHeaderGroups().map((headerGroup) => (
                <TableRow key={headerGroup.id}>
                  {headerGroup.headers.map((header) => (
                    <TableHead
                      key={header.id}
                      className={
                        header.id === '__gutter__'
                          ? 'w-10'
                          : header.id === '__actions__'
                            ? actionsHeader
                              ? 'text-right'
                              : 'w-12'
                            : undefined
                      }
                    >
                      {flexRender(
                        header.column.columnDef.header,
                        header.getContext(),
                      )}
                    </TableHead>
                  ))}
                </TableRow>
              ))}
            </TableHeader>
            <TableBody>
              {/* Three ghost rows (dashed borders) */}
              {[0, 1, 2].map((idx) => (
                <TableRow key={`ghost-${idx}`} className="border-dashed">
                  {effectiveColumns.map((col, colIdx) => (
                    <TableCell key={col.id ?? ('accessorKey' in col ? String(col.accessorKey) : colIdx)}>
                      {idx === 0 && col.id === '__actions__' ? (
                        <div className="flex justify-end">
                          {emptyAction}
                        </div>
                      ) : idx === 0 && emptyMessage && col.id !== '__gutter__' && col.id !== '__actions__' ? (
                        <span className="text-[14px] text-muted-foreground">{emptyMessage}</span>
                      ) : null}
                    </TableCell>
                  ))}
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </Card>
      </div>
    );
  }

  const rows = table.getRowModel().rows;
  const pageCount = Math.max(table.getPageCount(), 1);

  return (
    <div className="flex flex-col gap-3">
      {searchable && (
        <div className="relative w-full max-w-sm">
          <Search className="pointer-events-none absolute start-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            value={globalFilter}
            onChange={(e) => setGlobalFilter(e.target.value)}
            placeholder={searchPlaceholder ?? t('common.search')}
            className="ps-9"
          />
        </div>
      )}

      <Card className="overflow-hidden">
        <Table>
          <TableHeader>
            {table.getHeaderGroups().map((headerGroup) => (
              <TableRow key={headerGroup.id}>
                {headerGroup.headers.map((header) => {
                  const sortable = header.column.getCanSort();
                  const dir = header.column.getIsSorted();
                  return (
                    <TableHead
                      key={header.id}
                      className={
                        header.id === '__gutter__'
                          ? 'w-10'
                          : header.id === '__actions__'
                            ? actionsHeader
                              ? 'text-right'
                              : 'w-12'
                            : undefined
                      }
                      aria-sort={
                        dir === 'asc'
                          ? 'ascending'
                          : dir === 'desc'
                            ? 'descending'
                            : undefined
                      }
                    >
                      {sortable ? (
                        <button
                          type="button"
                          onClick={header.column.getToggleSortingHandler()}
                          className="inline-flex items-center gap-1 transition-colors hover:text-foreground"
                        >
                          {flexRender(
                            header.column.columnDef.header,
                            header.getContext(),
                          )}
                          {dir === 'asc' ? (
                            <ArrowUp className="h-3.5 w-3.5" />
                          ) : dir === 'desc' ? (
                            <ArrowDown className="h-3.5 w-3.5" />
                          ) : (
                            <ArrowUpDown className="h-3.5 w-3.5 opacity-40" />
                          )}
                        </button>
                      ) : (
                        flexRender(
                          header.column.columnDef.header,
                          header.getContext(),
                        )
                      )}
                    </TableHead>
                  );
                })}
              </TableRow>
            ))}
          </TableHeader>
          <TableBody>
            {rows.length === 0 ? (
              <TableRow>
                <TableCell
                  colSpan={effectiveColumns.length}
                  className="p-4 text-center text-muted-foreground"
                >
                  No matching rows
                </TableCell>
              </TableRow>
            ) : (
              rows.map((row) => (
                <TableRow key={row.id} className="h-11">
                  {row.getVisibleCells().map((cell) => (
                    <TableCell
                      key={cell.id}
                      className={cell.column.id === '__gutter__' ? 'w-10' : undefined}
                    >
                      {flexRender(cell.column.columnDef.cell, cell.getContext())}
                    </TableCell>
                  ))}
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>

        {paginated && pageCount > 1 && (
          <div className="h-11 border-t border-border bg-background px-3 flex items-center justify-between text-[13px] text-muted-foreground">
            <span>
              {t('table.rowsOf', { shown: rows.length, total: data.length })}
            </span>
            <div className="flex items-center gap-2">
              <Button
                variant="secondary"
                size="sm"
                aria-label={t('table.previousPage')}
                onClick={() => table.previousPage()}
                disabled={!table.getCanPreviousPage()}
              >
                <ChevronLeft className="h-4 w-4 rtl:rotate-180" />
              </Button>
              <span>
                {t('table.pageOf', { page: table.getState().pagination.pageIndex + 1, pages: pageCount })}
              </span>
              <Button
                variant="secondary"
                size="sm"
                aria-label={t('table.nextPage')}
                onClick={() => table.nextPage()}
                disabled={!table.getCanNextPage()}
              >
                <ChevronRight className="h-4 w-4 rtl:rotate-180" />
              </Button>
            </div>
          </div>
        )}
      </Card>
    </div>
  );
}

// vue/src/components/shared/data-table/DataTable.vue
<script setup lang="ts" generic="TData extends RowData">
import type { Component } from 'vue';
import { computed, h, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import {
  FlexRender,
  useTable,
  type Column,
  type ColumnDef,
  type Header,
  type PaginationState,
  type RowData,
} from '@tanstack/vue-table';
import {
  ArrowDown,
  ArrowUp,
  ArrowUpDown,
  ChevronLeft,
  ChevronRight,
  Search,
} from 'lucide-vue-next';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import RowActionsMenu from '@/components/shared/RowActionsMenu.vue';
import type { RowActionItem } from '@/components/shared/types';
import { dataTableFeatures } from './features';

const PAGE_SIZE = 10;
// Non-paginated tables still run the pagination row model (the shared feature
// set registers it) — one enormous page makes it a no-op pass-through.
const MAX_PAGE_SIZE = 1_000_000;

interface Props<TData extends RowData> {
  data: TData[];
  /** TanStack column defs. Keys double as scoped-slot names: `#cell-<id>`. */
  columns: ColumnDef<typeof dataTableFeatures, TData>[];
  /** Trailing actions column. Permission gating stays inside this callback. */
  actions?: (row: TData) => RowActionItem[];
  actionsAriaLabel?: string;
  searchable?: boolean;
  searchPlaceholder?: string;
  paginated?: boolean;
  /** When true, adds a gutter column (w-10, 1-based row numbers, mono, muted). */
  gutter?: boolean;
  /** lucide icon for the empty state. */
  emptyIcon?: Component;
  emptyMessage?: string;
  emptyHint?: string;
  /** While true the empty state is suppressed (initial load in flight). */
  loading?: boolean;
  /** Optional action (e.g. an "Add" button) rendered in the empty state. */
  emptyAction?: any;
  /** Header label over the trailing actions column (blank when omitted). */
  actionsHeader?: string;
}

const props = defineProps<Props<TData>>();
const { t } = useI18n();

// ── Column defs: gutter (if enabled) + caller's + actions (if enabled) ───
const columns = computed<ColumnDef<typeof dataTableFeatures, TData>[]>(() => {
  const cols: ColumnDef<typeof dataTableFeatures, TData>[] = [];

  // Leading gutter column (row numbers, 1-based) if enabled
  if (props.gutter) {
    cols.push({
      id: '__gutter__',
      enableSorting: false,
      enableGlobalFilter: false,
      header: () => '',
      cell: ({ row }) =>
        h('div', { class: 'w-10 text-end font-mono text-[12px] text-faint-foreground' }, String(row.index + 1)),
    });
  }

  cols.push(...props.columns);

  // Trailing actions column if enabled
  if (props.actions) {
    cols.push({
      id: '__actions__',
      header: () => props.actionsHeader ?? '',
      enableSorting: false,
      enableGlobalFilter: false,
      cell: ({ row }) =>
        h('div', { class: 'flex justify-end' }, [
          h(RowActionsMenu, {
            items: props.actions!(row.original),
            ariaLabel: props.actionsAriaLabel ?? 'Actions',
          }),
        ]),
    });
  }
  return cols;
});

// ── Controlled state slices ────────────────────────────────────────────
const globalFilter = ref('');
const pagination = ref<PaginationState>({ pageIndex: 0, pageSize: PAGE_SIZE });

watch(
  () => props.paginated,
  (paginated) => {
    pagination.value = {
      pageIndex: 0,
      pageSize: paginated ? PAGE_SIZE : MAX_PAGE_SIZE,
    };
  },
  { immediate: true },
);

// Refetches (add/rename/delete) shrink the data — snap back to page 1 rather
// than stranding the user on an out-of-range page.
watch(
  () => props.data,
  () => {
    pagination.value = { ...pagination.value, pageIndex: 0 };
  },
);

const state = computed(() => ({
  globalFilter: globalFilter.value,
  pagination: pagination.value,
}));

function resolve<T>(updater: T | ((old: T) => T), old: T): T {
  return typeof updater === 'function' ? (updater as (old: T) => T)(old) : updater;
}

// ── The table ──────────────────────────────────────────────────────────
// Computed refs (not getters) for every reactive option — the documented
// MaybeRef contract the Vue adapter watches and unwraps.
const table = useTable<typeof dataTableFeatures, TData>({
  features: dataTableFeatures,
  data: computed(() => props.data),
  columns,
  state,
  globalFilterFn: 'includesString',
  onGlobalFilterChange: (updater) => {
    globalFilter.value = resolve(updater, globalFilter.value);
  },
  onPaginationChange: (updater) => {
    pagination.value = resolve(updater, pagination.value);
  },
});

const rows = computed(() => table.getRowModel().rows);
const pageCount = computed(() => table.getPageCount());
const pageIndex = computed(() => table.atoms.pagination.get().pageIndex);

// ── Per-column presentation helpers ───────────────────────────────────
const isActionsColumn = (column: Column<typeof dataTableFeatures, TData>) =>
  column.id === '__actions__';

function headerClass(header: Header<typeof dataTableFeatures, TData>): string {
  const classes = [];
  // The gutter needs an explicit width or auto table layout hands it slack on narrow tables.
  if (header.column.id === '__gutter__') {
    classes.push('w-10');
  }
  if (isActionsColumn(header.column)) {
    classes.push(props.actionsHeader ? 'text-right' : 'w-12');
  }
  if (header.column.getCanSort()) {
    classes.push('cursor-pointer select-none');
  }
  return classes.filter(Boolean).join(' ');
}

function sortIcon(column: Column<typeof dataTableFeatures, TData>): Component {
  return column.getIsSorted() === 'asc' ? ArrowUp : column.getIsSorted() === 'desc' ? ArrowDown : ArrowUpDown;
}
</script>

<template>
  <div class="flex flex-col gap-3">
    <!-- Global search (§3 grammar: 240px wide, h-8) -->
    <div v-if="searchable" class="relative max-w-sm">
      <Search
        class="pointer-events-none absolute start-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"
      />
      <Input
        v-model="globalFilter"
        class="ps-9"
        :placeholder="searchPlaceholder ?? t('common.search')"
      />
    </div>

    <!-- Empty state (when data.length === 0): three ghost rows with dashed borders -->
    <template v-if="data.length === 0">
      <Card class="overflow-hidden">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead
                v-for="header in table.getHeaderGroups()[0]?.headers ?? []"
                :key="header.id"
                :class="headerClass(header)"
              >
                <template v-if="!header.isPlaceholder">
                  <FlexRender :header="header" />
                </template>
              </TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <!-- Three ghost rows (dashed borders) per §3 -->
            <TableRow v-for="idx in 3" :key="`ghost-${idx}`" class="border-dashed">
              <TableCell
                v-for="col in columns"
                :key="col.id"
              >
                <!-- Empty message in first row, first data column (not gutter/actions) -->
                <template v-if="idx === 0 && col.id !== '__gutter__' && col.id !== '__actions__' && emptyMessage">
                  <span class="text-[14px] text-muted-foreground">{{ emptyMessage }}</span>
                </template>
                <!-- Empty action button at the end of the first row -->
                <template v-if="idx === 0 && col.id === '__actions__' && emptyAction">
                  <div class="flex justify-end">
                    <component :is="emptyAction" />
                  </div>
                </template>
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </Card>
    </template>

    <!-- Normal table (when data.length > 0) -->
    <template v-else-if="!loading">
      <Card class="overflow-hidden">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead
                v-for="header in table.getHeaderGroups()[0]?.headers ?? []"
                :key="header.id"
                :class="headerClass(header)"
                :aria-sort="
                  header.column.getIsSorted() === 'asc'
                    ? 'ascending'
                    : header.column.getIsSorted() === 'desc'
                      ? 'descending'
                      : undefined
                "
                @click="header.column.getToggleSortingHandler()?.($event)"
              >
                <template v-if="!header.isPlaceholder">
                  <button
                    v-if="header.column.getCanSort()"
                    type="button"
                    class="inline-flex items-center gap-1 transition-colors hover:text-foreground"
                  >
                    <FlexRender :header="header" />
                    <component
                      :is="sortIcon(header.column)"
                      class="h-3.5 w-3.5"
                      :class="
                        header.column.getIsSorted() === false
                          ? 'opacity-40'
                          : ''
                      "
                    />
                  </button>
                  <template v-else>
                    <FlexRender :header="header" />
                  </template>
                </template>
              </TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <!-- Data rows -->
            <template v-if="rows.length > 0">
              <TableRow v-for="row in rows" :key="row.id">
                <TableCell
                  v-for="cell in row.getAllCells()"
                  :key="cell.id"
                  :class="isActionsColumn(cell.column) ? 'flex justify-end' : ''"
                >
                  <!-- Named scoped slot per column key (`#cell-<id>`), falling back
                       to the column def's own TanStack cell template. -->
                  <slot :name="`cell-${cell.column.id}`" :row="row.original" :cell="cell">
                    <FlexRender :cell="cell" />
                  </slot>
                </TableCell>
              </TableRow>
            </template>
            <!-- No matching rows after filter -->
            <TableRow v-else>
              <TableCell
                :colspan="columns.length"
                class="p-4 text-center text-muted-foreground"
              >
                {{ t('common.noResults') }}
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>

        <!-- Pagination footer (§3 grammar: h-11, border-t, flex justify-between) -->
        <div
          v-if="paginated && pageCount > 1"
          class="h-11 border-t border-border bg-background px-3 flex items-center justify-between text-[13px] text-muted-foreground"
        >
          <span>
            {{ t('table.rowsOf', { shown: rows.length, total: data.length }) }}
          </span>
          <div class="flex items-center gap-2">
            <Button
              variant="secondary"
              size="sm"
              :aria-label="t('table.previousPage')"
              :disabled="!table.getCanPreviousPage()"
              @click="table.previousPage()"
            >
              <ChevronLeft class="h-4 w-4 rtl:-scale-x-100" />
            </Button>
            <span>
              {{ t('table.pageOf', { page: pageIndex + 1, pages: pageCount }) }}
            </span>
            <Button
              variant="secondary"
              size="sm"
              :aria-label="t('table.nextPage')"
              :disabled="!table.getCanNextPage()"
              @click="table.nextPage()"
            >
              <ChevronRight class="h-4 w-4 rtl:-scale-x-100" />
            </Button>
          </div>
        </div>
      </Card>
    </template>

    <!-- Loading skeleton (when loading: true) -->
    <template v-else>
      <Card class="overflow-hidden">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead
                v-for="header in table.getHeaderGroups()[0]?.headers ?? []"
                :key="header.id"
                :class="headerClass(header)"
              >
                <template v-if="!header.isPlaceholder">
                  <FlexRender :header="header" />
                </template>
              </TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <!-- Skeleton rows (h-11 with animated bg-gutter bar) -->
            <TableRow v-for="idx in 5" :key="`skeleton-${idx}`">
              <TableCell v-for="col in columns" :key="col.id">
                <div class="h-3 w-[40%] rounded bg-gutter animate-pulse" />
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </Card>
    </template>
  </div>
</template>
