// vue/src/features/signup/SignupPage.vue
<script setup lang="ts">
import { computed, ref, watchEffect } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import { useI18n } from 'vue-i18n';
import {
  useGetApiAuthSignupEnabled,
  usePostApiAuthRegisterAdmin,
  useGetApiPlans,
} from '@moamen-ui/pointer-vue';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { PasswordInput } from '@/components/ui/password-input';
import { Label } from '@/components/ui/label';
import { extractMessage } from '@/lib/error';
import { cn } from '@/lib/utils';

const { t } = useI18n();
const router = useRouter();
const route = useRoute();

// Signup availability comes from the typed SignupEnabledResponse { enabled }.
const { data: signupData, isPending: checking } = useGetApiAuthSignupEnabled();
const signupOpen = computed(() => signupData.value?.enabled === true);
const signupClosed = computed(() => !checking.value && !signupOpen.value);

// Public plans list — anonymous endpoint, ordered by sortOrder.
// Visible (displayState 0) are selectable; ComingSoon (1) shown greyed & disabled; Hidden (2) excluded.
const { data: plansRaw } = useGetApiPlans();

interface PlanPublicResponse {
  slug?: string | null;
  name?: string | null;
  priceMonthly?: number;
  currency?: string | null;
  interval?: number;
  featureBullets?: string[] | null;
  displayState?: number; // 0=Visible, 1=ComingSoon, 2=Hidden
  sortOrder?: number;
}

const allPlans = computed<PlanPublicResponse[]>(
  () => (plansRaw.value as unknown as PlanPublicResponse[] | undefined) ?? [],
);

// Filter out Hidden (2), sort by sortOrder.
const selectablePlans = computed(() =>
  allPlans.value
    .filter((p) => p.displayState !== 2)
    .slice()
    .sort((a, b) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0)),
);

// Honor ?plan=<slug>: preselect if Visible (displayState 0). Default null = Free.
const planSlugFromQuery = computed<string | null>(() => {
  const q = route.query.plan;
  return typeof q === 'string' ? q : null;
});

const selectedSlug = ref<string | null>(null);
// Whether we've already applied the query-param preselection (run once when plans load).
const preselected = ref(false);

watchEffect(() => {
  if (preselected.value) return;
  const slug = planSlugFromQuery.value;
  if (!slug) { preselected.value = true; return; }
  const plans = selectablePlans.value;
  if (plans.length === 0) return; // wait for plans to load
  const match = plans.find((p) => p.slug === slug && p.displayState === 0);
  selectedSlug.value = match?.slug ?? null;
  preselected.value = true;
});

function formatPlanPrice(plan: PlanPublicResponse): string {
  if (!plan.priceMonthly) return t('signup.plan.free');
  const interval = plan.interval === 1 ? '/yr' : '/mo';
  return `${plan.priceMonthly} ${plan.currency ?? 'USD'}${interval}`;
}

const registerAdmin = usePostApiAuthRegisterAdmin();

const email = ref('');
const password = ref('');
const displayName = ref('');
const loading = ref(false);
const error = ref<string | null>(null);
const submitted = ref(false);

async function onSubmit() {
  if (!email.value || !password.value || !displayName.value) return;
  loading.value = true;
  error.value = null;
  try {
    // INTENTIONAL: planId is always sent as null (undefined) here.
    //
    // The public /api/plans endpoint returns PlanPublicResponse which has no `id` field,
    // only `slug`. Resolving a slug to an integer planId would require either:
    //   (a) the admin /api/admin/plans endpoint (requires super-admin auth), or
    //   (b) an id-bearing public endpoint that does not yet exist.
    //
    // The spec decision: treat the plan selector as display-only marketing UI.
    // When payment integration + an id-bearing public endpoint exist, replace
    // `planId: undefined` below with the resolved integer.
    //
    // See monetization-ui-spec.md §4 "Submit selected plan's id?"
    await registerAdmin.mutateAsync({
      data: {
        email: email.value,
        password: password.value,
        displayName: displayName.value,
        // planId: null — intentionally omitted until payment integration
      },
    });
    submitted.value = true;
  } catch (err) {
    error.value = extractMessage(err) || t('signup.failed');
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <div class="flex min-h-screen items-center justify-center bg-secondary p-4">
    <Card class="w-[440px] max-w-[92vw]">
      <CardContent class="flex flex-col gap-5 p-6">
        <h1 class="text-center text-xl font-bold">{{ t('signup.title') }}</h1>

        <!-- Loading check -->
        <div v-if="checking" class="text-center text-sm text-muted-foreground">
          {{ t('signup.checking') }}
        </div>

        <!-- Signup closed -->
        <div v-else-if="signupClosed" class="flex flex-col gap-4 text-center">
          <p class="text-sm text-muted-foreground">{{ t('signup.closed') }}</p>
          <Button variant="outline" @click="router.push('/login')">
            {{ t('signup.backToLogin') }}
          </Button>
        </div>

        <!-- Success state -->
        <div v-else-if="submitted" class="flex flex-col gap-4 text-center">
          <p class="text-sm">{{ t('signup.pendingApproval') }}</p>
          <Button variant="outline" @click="router.push('/login')">
            {{ t('signup.backToLogin') }}
          </Button>
        </div>

        <!-- Signup form -->
        <form v-else-if="signupOpen" class="flex flex-col gap-4" @submit.prevent="onSubmit">
          <div class="flex flex-col gap-2">
            <Label for="signup-name">{{ t('signup.displayName') }}</Label>
            <Input id="signup-name" v-model="displayName" autocomplete="name" required />
          </div>
          <div class="flex flex-col gap-2">
            <Label for="signup-email">{{ t('signup.email') }}</Label>
            <Input id="signup-email" v-model="email" type="email" autocomplete="email" required />
          </div>
          <div class="flex flex-col gap-2">
            <Label for="signup-password">{{ t('signup.password') }}</Label>
            <PasswordInput
              id="signup-password"
              v-model="password"
              autocomplete="new-password"
              required
            />
          </div>

          <!-- Plan selector (marketing display only) -->
          <div v-if="selectablePlans.length > 0" class="flex flex-col gap-2">
            <Label class="text-sm font-medium">{{ t('signup.plan.choosePlan') }}</Label>
            <div class="flex flex-col gap-2">
              <button
                v-for="plan in selectablePlans"
                :key="plan.slug ?? plan.name ?? ''"
                type="button"
                :disabled="plan.displayState === 1"
                :class="cn(
                  'flex w-full flex-col gap-1 rounded-lg border px-3 py-3 text-start transition-colors',
                  selectedSlug === plan.slug
                    ? 'border-brand bg-brand-tint text-brand'
                    : 'border-border bg-card text-card-foreground hover:border-brand/50',
                  plan.displayState === 1 && 'cursor-not-allowed opacity-50',
                )"
                @click="plan.displayState !== 1 && (selectedSlug = plan.slug ?? null)"
              >
                <div class="flex items-center justify-between gap-2">
                  <span class="text-sm font-semibold">{{ plan.name }}</span>
                  <span class="text-xs font-medium">{{ formatPlanPrice(plan) }}</span>
                </div>
                <span v-if="plan.displayState === 1" class="chip chip-neutral text-[10px]">
                  {{ t('signup.plan.comingSoon') }}
                </span>
                <ul v-if="plan.featureBullets && plan.featureBullets.length > 0" class="mt-1 flex flex-col gap-0.5">
                  <li
                    v-for="(bullet, i) in plan.featureBullets.slice(0, 3)"
                    :key="i"
                    class="text-xs text-muted-foreground"
                  >
                    · {{ bullet }}
                  </li>
                </ul>
              </button>
            </div>
            <p class="text-xs text-muted-foreground">{{ t('signup.plan.marketingNote') }}</p>
          </div>

          <p v-if="error" class="text-sm text-destructive">{{ error }}</p>
          <Button
            type="submit"
            class="mt-1"
            :disabled="loading || !email || !password || !displayName"
          >
            {{ t('signup.submit') }}
          </Button>
          <Button variant="ghost" size="sm" @click="router.push('/login')">
            {{ t('signup.backToLogin') }}
          </Button>
        </form>
      </CardContent>
    </Card>
  </div>
</template>

// react/src/features/signup/SignupPage.tsx
// Public self-signup page — shown only when scopedAdminSignupEnabled is true.
// Posts to /api/auth/register-admin; on success shows a "pending approval" message.
// Disabled state → "signup closed" notice.
// v2: Renders a plan selector from the public GET /api/plans endpoint.
//     Honors ?plan=<slug> query param to preselect a plan.
import { useState, type FormEvent } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import {
  useGetApiAuthSignupEnabled,
  usePostApiAuthRegisterAdmin,
  useGetApiPlans,
  type PlanPublicResponse,
  PlanDisplayState,
  BillingInterval,
} from '@moamen-ui/pointer-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { PasswordInput } from '@/components/ui/password-input';
import { Label } from '@/components/ui/label';
import { extractMessage } from '@/lib/error';
import { cn } from '@/lib/utils';

// Helper: format plan price for display
function formatPlanPrice(plan: PlanPublicResponse): string {
  if (!plan.priceMonthly) return 'Free';
  const interval = plan.interval === BillingInterval.NUMBER_1 ? '/yr' : '/mo';
  return `${plan.priceMonthly} ${plan.currency ?? 'USD'}${interval}`;
}

// Plan card for the selector
function PlanCard({
  plan,
  selected,
  disabled,
  onClick,
}: {
  plan: PlanPublicResponse;
  selected: boolean;
  disabled: boolean;
  onClick: () => void;
}) {
  const { t } = useTranslation();
  return (
    <button
      type="button"
      disabled={disabled}
      onClick={onClick}
      className={cn(
        'flex w-full flex-col gap-1 rounded-lg border px-3 py-3 text-start transition-colors',
        selected
          ? 'border-brand bg-brand-tint text-brand'
          : 'border-border bg-card text-card-foreground hover:border-brand/50',
        disabled && 'cursor-not-allowed opacity-50',
      )}
    >
      <div className="flex items-center justify-between gap-2">
        <span className="font-semibold text-sm">{plan.name}</span>
        <span className="text-xs font-medium">{formatPlanPrice(plan)}</span>
      </div>
      {plan.displayState === PlanDisplayState.NUMBER_1 && (
        <span className="chip chip-neutral text-[10px]">{t('signup.plan.comingSoon')}</span>
      )}
      {plan.featureBullets && plan.featureBullets.length > 0 && (
        <ul className="mt-1 flex flex-col gap-0.5">
          {plan.featureBullets.slice(0, 3).map((b, i) => (
            <li key={i} className="text-xs text-muted-foreground">
              · {b}
            </li>
          ))}
        </ul>
      )}
    </button>
  );
}

export function SignupPage() {
  const { t } = useTranslation();
  const [searchParams] = useSearchParams();
  const planSlugFromQuery = searchParams.get('plan');

  // Use the typed enabled field from SignupEnabledResponse.
  const { data: signupData, isLoading: checkingEnabled } =
    useGetApiAuthSignupEnabled();
  const signupEnabled = signupData?.enabled === true;

  // Public plans list — anonymous, ordered by sortOrder.
  // Visible (0) + ComingSoon (1) shown; Hidden (2) excluded.
  const { data: plansRaw } = useGetApiPlans();
  const allPlans: PlanPublicResponse[] =
    (plansRaw as unknown as { data?: PlanPublicResponse[] })?.data ??
    (Array.isArray(plansRaw) ? (plansRaw as PlanPublicResponse[]) : []);

  const selectablePlans = allPlans
    .filter((p) => p.displayState !== PlanDisplayState.NUMBER_2)
    .sort((a, b) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0));

  // Honor ?plan=<slug>: preselect that slug if it's Visible when plans load.
  // If no query param, default to null (Free / no plan selected).
  const initialSlug =
    planSlugFromQuery &&
    selectablePlans.some(
      (p) =>
        p.slug === planSlugFromQuery &&
        p.displayState === PlanDisplayState.NUMBER_0,
    )
      ? planSlugFromQuery
      : null;

  const [selectedSlug, setSelectedSlug] = useState<string | null>(initialSlug);

  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [displayName, setDisplayName] = useState('');
  const [done, setDone] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const registerMut = usePostApiAuthRegisterAdmin({
    mutation: {
      onSuccess: () => {
        setDone(true);
      },
      onError: (e: unknown) => {
        setError(extractMessage(e));
      },
    },
  });

  function onSubmit(e: FormEvent) {
    e.preventDefault();
    if (!email || !password || !displayName.trim()) return;
    setError(null);

    // INTENTIONAL: planId is always sent as null (undefined) here.
    //
    // The public /api/plans endpoint returns PlanPublicResponse which has no `id` field,
    // only `slug`. Resolving a slug to an integer planId would require either:
    //   (a) the admin /api/admin/plans endpoint (requires super-admin auth), or
    //   (b) an id-bearing public endpoint that does not yet exist.
    //
    // The spec decision: treat the plan selector as display-only marketing UI.
    // When payment integration + an id-bearing public endpoint exist, replace
    // `planId: undefined` below with the resolved integer.
    //
    // See monetization-ui-spec.md §4 "Submit selected plan's id?"
    registerMut.mutate({
      data: {
        email: email.trim(),
        password,
        displayName: displayName.trim(),
        // planId: null — intentionally omitted until payment integration
      },
    });
  }

  if (checkingEnabled) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-secondary p-4">
        <p className="text-sm text-muted-foreground">{t('signup.checking')}</p>
      </div>
    );
  }

  return (
    <div className="flex min-h-screen items-center justify-center bg-secondary p-4">
      <Card className="w-[440px] max-w-[92vw]">
        <CardContent className="flex flex-col gap-5 p-6">
          <h1 className="text-center text-xl font-bold">{t('signup.title')}</h1>

          {!signupEnabled ? (
            <>
              <p className="text-center text-sm text-muted-foreground">{t('signup.closed')}</p>
              <Link to="/login" className="text-center text-sm text-brand hover:underline">
                {t('signup.backToLogin')}
              </Link>
            </>
          ) : done ? (
            <>
              <p className="text-center text-sm text-muted-foreground">
                {t('signup.pending')}
              </p>
              <Link to="/login" className="text-center text-sm text-brand hover:underline">
                {t('signup.backToLogin')}
              </Link>
            </>
          ) : (
            <form onSubmit={onSubmit} className="flex flex-col gap-4">
              <div className="flex flex-col gap-2">
                <Label htmlFor="signup-name">{t('signup.displayName')}</Label>
                <Input
                  id="signup-name"
                  value={displayName}
                  onChange={(e) => setDisplayName(e.target.value)}
                  autoFocus
                />
              </div>
              <div className="flex flex-col gap-2">
                <Label htmlFor="signup-email">{t('signup.email')}</Label>
                <Input
                  id="signup-email"
                  type="email"
                  autoComplete="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                />
              </div>
              <div className="flex flex-col gap-2">
                <Label htmlFor="signup-password">{t('signup.password')}</Label>
                <PasswordInput
                  id="signup-password"
                  autoComplete="new-password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                />
              </div>

              {/* Plan selector — shown when public plans are available */}
              {selectablePlans.length > 0 && (
                <div className="flex flex-col gap-2">
                  <Label>{t('signup.plan.chooseLabel')}</Label>
                  <div className="flex flex-col gap-2">
                    {selectablePlans.map((plan) => (
                      <PlanCard
                        key={plan.slug}
                        plan={plan}
                        selected={selectedSlug === plan.slug}
                        disabled={plan.displayState === PlanDisplayState.NUMBER_1}
                        onClick={() =>
                          setSelectedSlug(
                            selectedSlug === plan.slug ? null : (plan.slug ?? null),
                          )
                        }
                      />
                    ))}
                  </div>
                  <p className="text-xs text-muted-foreground">{t('signup.plan.hint')}</p>
                </div>
              )}

              {error && <p className="text-sm text-destructive">{error}</p>}
              <Button
                type="submit"
                className="mt-1"
                disabled={registerMut.isPending || !email || !password || !displayName.trim()}
              >
                {t('signup.submit')}
              </Button>
              <Link to="/login" className="text-center text-sm text-muted-foreground hover:underline">
                {t('signup.backToLogin')}
              </Link>
            </form>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
