// react/src/features/comments/CommentDetail.tsx
// Comment detail — a wide dialog (mirrors ProjectsPage's edit-dialog pattern, the
// closest "row detail" convention already in this app; there is no Sheet/Drawer
// component here to reuse instead). Renders the full comment: body, element capture,
// applied/deploy state with verify, replies, and the status/visibility/delete actions.
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useQueryClient } from '@tanstack/react-query';
import {
  useGetApiCommentsId,
  usePatchApiCommentsId,
  usePostApiCommentsIdVerify,
  usePostApiCommentsIdReplies,
  usePatchApiCommentsIdVisibility,
  useDeleteApiCommentsId,
  getGetApiCommentsIdQueryKey,
  CommentStatus,
  type CommentResponse,
} from '@moamen-ui/pointer-react';
import {
  Lock,
  Unlock,
  ExternalLink,
  ThumbsUp,
  ThumbsDown,
  Trash2,
  Rocket,
} from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { ConfirmDialog } from '@/components/ConfirmDialog';
import { useToast } from '@/components/ui/toast';
import { useAuth } from '@/lib/auth';
import { extractMessage } from '@/lib/error';
import { formatRelativeTime } from '@/lib/format';
import { useStatusCatalog } from '@/lib/status-catalog';
import { badgeVariantForStatus, environmentLabelKey } from './comment-format';

const TEXTAREA_CLASS =
  'w-full resize-none rounded-md border border-input bg-background px-3 py-1.5 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring';

function commitShort(sha: string | null | undefined): string {
  return sha ? sha.slice(0, 7) : '';
}

export function CommentDetail({
  commentId,
  onClose,
  onChanged,
}: {
  commentId: number;
  onClose: () => void;
  onChanged: () => void;
}) {
  const { t } = useTranslation();
  const { toast } = useToast();
  const qc = useQueryClient();
  const { isAdmin, user } = useAuth();
  const catalog = useStatusCatalog();

  const { data: comment, isLoading } = useGetApiCommentsId(commentId);

  const [replyBody, setReplyBody] = useState('');
  const [verifyNote, setVerifyNote] = useState('');
  const [showVerifyNote, setShowVerifyNote] = useState(false);
  const [deleteOpen, setDeleteOpen] = useState(false);

  useEffect(() => {
    setReplyBody('');
    setVerifyNote('');
    setShowVerifyNote(false);
  }, [commentId]);

  function reloadDetail() {
    void qc.invalidateQueries({ queryKey: getGetApiCommentsIdQueryKey(commentId) });
    onChanged();
  }
  const onError = (e: unknown) => toast(extractMessage(e), 'error');

  const patchStatusMut = usePatchApiCommentsId({
    mutation: {
      onSuccess: () => {
        toast(t('comments.statusUpdated'));
        reloadDetail();
      },
      onError,
    },
  });

  const verifyMut = usePostApiCommentsIdVerify({
    mutation: {
      onSuccess: () => {
        toast(t('comments.verified'));
        setShowVerifyNote(false);
        setVerifyNote('');
        reloadDetail();
      },
      onError,
    },
  });

  const replyMut = usePostApiCommentsIdReplies({
    mutation: {
      onSuccess: () => {
        toast(t('comments.replyAdded'));
        setReplyBody('');
        reloadDetail();
      },
      onError,
    },
  });

  const visibilityMut = usePatchApiCommentsIdVisibility({
    mutation: {
      onSuccess: () => {
        toast(t('comments.visibilityUpdated'));
        reloadDetail();
      },
      onError,
    },
  });

  const deleteMut = useDeleteApiCommentsId({
    mutation: {
      onSuccess: () => {
        toast(t('comments.deleted'));
        setDeleteOpen(false);
        onChanged();
        onClose();
      },
      onError,
    },
  });

  const isAuthor = !!(user?.id && comment?.authorId && user.id === comment.authorId);
  const canDelete = isAdmin || isAuthor;
  // Verifying a fix is the original reporter's call (or an admin's, on their behalf) —
  // same "admin or author" rule the work order gives Delete.
  const canVerify = (isAdmin || isAuthor) && !!comment?.appliedAt && !comment?.verifiedAt;

  function submitReply() {
    const body = replyBody.trim();
    if (!body) return;
    replyMut.mutate({ id: commentId, data: { body } });
  }

  function submitVerify(ok: boolean) {
    if (ok) {
      verifyMut.mutate({ id: commentId, data: { ok: true } });
      return;
    }
    if (!showVerifyNote) {
      setShowVerifyNote(true);
      return;
    }
    verifyMut.mutate({ id: commentId, data: { ok: false, note: verifyNote.trim() || undefined } });
  }

  return (
    <>
      <Dialog open onOpenChange={(o) => !o && onClose()}>
        <DialogContent className="max-w-lg sm:max-w-2xl max-h-[85vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>{t('comments.detail.title')}</DialogTitle>
          </DialogHeader>

          {isLoading || !comment ? (
            <p className="text-sm text-muted-foreground">{t('common.loading')}</p>
          ) : (
            <CommentDetailBody
              comment={comment}
              canDelete={canDelete}
              canVerify={canVerify}
              replyBody={replyBody}
              setReplyBody={setReplyBody}
              onSubmitReply={submitReply}
              replyPending={replyMut.isPending}
              showVerifyNote={showVerifyNote}
              verifyNote={verifyNote}
              setVerifyNote={setVerifyNote}
              onVerify={submitVerify}
              verifyPending={verifyMut.isPending}
              onStatusChange={(status) => patchStatusMut.mutate({ id: commentId, data: { status } })}
              statusPending={patchStatusMut.isPending}
              isAuthor={isAuthor}
              onToggleVisibility={() =>
                visibilityMut.mutate({ id: commentId, data: { isPrivate: !comment.isPrivate } })
              }
              visibilityPending={visibilityMut.isPending}
              onDelete={() => setDeleteOpen(true)}
              catalog={catalog}
              t={t}
            />
          )}

          <DialogFooter className="gap-2">
            <Button variant="secondary" onClick={onClose}>
              {t('common.close')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <ConfirmDialog
        open={deleteOpen}
        message={t('comments.detail.confirmDelete')}
        confirmLabel={t('common.delete')}
        confirmColor="warn"
        onConfirm={() => deleteMut.mutate({ id: commentId })}
        onCancel={() => setDeleteOpen(false)}
      />
    </>
  );
}

type Translate = (key: string, opts?: Record<string, unknown>) => string;

function CommentDetailBody({
  comment,
  canDelete,
  canVerify,
  replyBody,
  setReplyBody,
  onSubmitReply,
  replyPending,
  showVerifyNote,
  verifyNote,
  setVerifyNote,
  onVerify,
  verifyPending,
  onStatusChange,
  statusPending,
  isAuthor,
  onToggleVisibility,
  visibilityPending,
  onDelete,
  catalog,
  t,
}: {
  comment: CommentResponse;
  canDelete: boolean;
  canVerify: boolean;
  replyBody: string;
  setReplyBody: (v: string) => void;
  onSubmitReply: () => void;
  replyPending: boolean;
  showVerifyNote: boolean;
  verifyNote: string;
  setVerifyNote: (v: string) => void;
  onVerify: (ok: boolean) => void;
  verifyPending: boolean;
  onStatusChange: (status: CommentStatus) => void;
  statusPending: boolean;
  isAuthor: boolean;
  onToggleVisibility: () => void;
  visibilityPending: boolean;
  onDelete: () => void;
  catalog: ReturnType<typeof useStatusCatalog>;
  t: Translate;
}) {
  const el = comment.element;
  const statusItem = catalog.items.find((s) => s.value === comment.status);

  return (
    <div className="flex flex-col gap-5 py-1">
      {/* Header meta */}
      <div className="flex flex-col gap-2">
        <div className="flex flex-wrap items-center gap-1.5">
          <Badge variant={badgeVariantForStatus(comment.status)}>
            {statusItem ? catalog.displayLabel(statusItem) : '—'}
          </Badge>
          <Badge variant="neutral" hideGlyph>
            {t(environmentLabelKey(comment.environment))}
          </Badge>
          {comment.isPrivate && (
            <Badge variant="neutral" hideGlyph>
              <Lock className="h-3 w-3" aria-hidden="true" />
              {t('comments.privateTooltip')}
            </Badge>
          )}
          {comment.isBugReport && <Badge variant="neutral" hideGlyph>{t('comments.bugBadge')}</Badge>}
          {comment.hasPayloadFlag && (
            <Badge variant="destructive">{t('comments.flaggedBadge')}</Badge>
          )}
        </div>
        <p className="text-[14px] whitespace-pre-wrap">{comment.body || '—'}</p>
        <p className="text-[12px] text-muted-foreground">
          {t('comments.detail.by', { name: comment.authorName || '—' })}
          {' · '}
          {t('comments.detail.createdAt', { date: formatRelativeTime(t, comment.createdAt) })}
          {comment.editedAt && (
            <>
              {' · '}
              {t('comments.detail.editedAt', { date: formatRelativeTime(t, comment.editedAt) })}
            </>
          )}
        </p>
        {comment.hasPayloadFlag && comment.payloadFlags && comment.payloadFlags.length > 0 && (
          <div className="flex flex-wrap items-center gap-1.5">
            <span className="text-[12px] text-muted-foreground">{t('comments.detail.payloadFlags')}:</span>
            {comment.payloadFlags.map((f) => (
              <Badge key={f} variant="neutral" hideGlyph>
                {f}
              </Badge>
            ))}
          </div>
        )}
        {comment.pickedActionTexts && comment.pickedActionTexts.length > 0 && (
          <div className="flex flex-col gap-1">
            <span className="text-[12px] font-medium text-muted-foreground">
              {t('comments.detail.pickedActions')}
            </span>
            <div className="flex flex-wrap gap-1.5">
              {comment.pickedActionTexts.map((a, i) => (
                <Badge key={i} variant="neutral" hideGlyph>
                  {a}
                </Badge>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Element */}
      {el && (
        <div className="flex flex-col gap-2 border-t border-border-muted pt-4">
          <h3 className="text-[16px] font-semibold leading-6">{t('comments.detail.elementSection')}</h3>
          <dl className="grid grid-cols-1 gap-x-4 gap-y-1.5 text-[13px] sm:grid-cols-2">
            {el.route && (
              <div className="flex flex-col gap-0.5">
                <dt className="text-muted-foreground">{t('comments.detail.route')}</dt>
                <dd className="font-mono break-all">{el.route}</dd>
              </div>
            )}
            {el.pageTitle && (
              <div className="flex flex-col gap-0.5">
                <dt className="text-muted-foreground">{t('comments.detail.pageTitle')}</dt>
                <dd className="break-words">{el.pageTitle}</dd>
              </div>
            )}
            {el.pageUrl && (
              <div className="flex flex-col gap-0.5">
                <dt className="text-muted-foreground">{t('comments.detail.pageUrl')}</dt>
                <dd>
                  <a
                    href={el.pageUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="inline-flex items-center gap-1 text-primary underline-offset-4 hover:underline break-all"
                  >
                    {el.pageUrl}
                    <ExternalLink className="h-3 w-3 shrink-0" aria-hidden="true" />
                  </a>
                </dd>
              </div>
            )}
            {el.selector && (
              <div className="flex flex-col gap-0.5">
                <dt className="text-muted-foreground">{t('comments.detail.selector')}</dt>
                <dd className="font-mono break-all">{el.selector}</dd>
              </div>
            )}
            {el.sourcePath && (
              <div className="flex flex-col gap-0.5">
                <dt className="text-muted-foreground">{t('comments.detail.sourcePath')}</dt>
                <dd className="font-mono break-all">{el.sourcePath}</dd>
              </div>
            )}
            {(el.deviceType || el.viewportWidth) && (
              <div className="flex flex-col gap-0.5">
                <dt className="text-muted-foreground">{t('comments.detail.device')}</dt>
                <dd>
                  {el.deviceType ?? '—'}
                  {el.viewportWidth && el.viewportHeight
                    ? ` · ${el.viewportWidth}×${el.viewportHeight}`
                    : ''}
                </dd>
              </div>
            )}
          </dl>
          {el.screenshotUrl && (
            <div className="flex flex-col gap-1">
              <span className="text-[13px] text-muted-foreground">{t('comments.detail.screenshot')}</span>
              <a href={el.screenshotUrl} target="_blank" rel="noreferrer" className="inline-block w-fit">
                <img
                  src={el.screenshotUrl}
                  alt={t('comments.detail.screenshot')}
                  className="max-h-[160px] rounded-md border border-border"
                />
              </a>
            </div>
          )}
        </div>
      )}

      {/* Applied / deploy / verify */}
      {comment.appliedAt && (
        <div className="flex flex-col gap-2 border-t border-border-muted pt-4">
          <h3 className="text-[16px] font-semibold leading-6">{t('comments.detail.appliedSection')}</h3>
          <p className="text-[13px] text-muted-foreground">
            {t('comments.detail.appliedBy', { name: comment.appliedByLabel || '—' })}
            {' · '}
            {t('comments.detail.appliedAt', { date: formatRelativeTime(t, comment.appliedAt) })}
          </p>
          {comment.commitUrl && (
            <a
              href={comment.commitUrl}
              target="_blank"
              rel="noreferrer"
              className="inline-flex w-fit items-center gap-1 font-mono text-[13px] text-primary underline-offset-4 hover:underline"
            >
              {t('comments.detail.commit')}: {commitShort(comment.commitSha) || comment.commitUrl}
              <ExternalLink className="h-3 w-3 shrink-0" aria-hidden="true" />
            </a>
          )}
          <div className="flex items-center gap-2">
            {comment.deployedAt ? (
              <Badge variant="success" title={comment.deployedSha ? commitShort(comment.deployedSha) : undefined}>
                <Rocket className="h-3 w-3" aria-hidden="true" />
                {t('comments.detail.deployLiveSince', { date: formatRelativeTime(t, comment.deployedAt) })}
              </Badge>
            ) : (
              <Badge variant="neutral" hideGlyph>{t('comments.detail.deployNotYetLive')}</Badge>
            )}
          </div>

          {comment.verifiedAt ? (
            <p className="text-[13px] text-muted-foreground">
              {t('comments.detail.verifiedAt', { date: formatRelativeTime(t, comment.verifiedAt) })}
            </p>
          ) : canVerify ? (
            <div className="flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  disabled={verifyPending}
                  onClick={() => onVerify(true)}
                >
                  <ThumbsUp className="h-4 w-4" />
                  {t('comments.detail.verifyWorks')}
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  disabled={verifyPending}
                  onClick={() => onVerify(false)}
                >
                  <ThumbsDown className="h-4 w-4" />
                  {t('comments.detail.verifyNotFixed')}
                </Button>
              </div>
              {showVerifyNote && (
                <div className="flex flex-col gap-2">
                  <textarea
                    value={verifyNote}
                    onChange={(e) => setVerifyNote(e.target.value)}
                    rows={2}
                    placeholder={t('comments.detail.verifyNotePlaceholder')}
                    className={TEXTAREA_CLASS}
                  />
                  <div className="flex justify-end">
                    <Button
                      type="button"
                      variant="destructive"
                      size="sm"
                      disabled={verifyPending}
                      onClick={() => onVerify(false)}
                    >
                      {t('comments.detail.verifyNotFixed')}
                    </Button>
                  </div>
                </div>
              )}
            </div>
          ) : null}
        </div>
      )}

      {/* Replies */}
      <div className="flex flex-col gap-2 border-t border-border-muted pt-4">
        <h3 className="text-[16px] font-semibold leading-6">{t('comments.detail.repliesSection')}</h3>
        {comment.replies && comment.replies.length > 0 ? (
          <ul className="flex flex-col gap-2">
            {comment.replies.map((r) => (
              <li key={r.id} className="rounded-md border border-border-muted p-2">
                <p className="text-[13px] whitespace-pre-wrap">{r.body}</p>
                <p className="mt-1 text-[12px] text-muted-foreground">
                  {r.authorName || '—'} · {formatRelativeTime(t, r.createdAt)}
                </p>
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-[13px] text-muted-foreground">{t('comments.detail.noReplies')}</p>
        )}
        <div className="flex flex-col gap-2">
          <textarea
            value={replyBody}
            onChange={(e) => setReplyBody(e.target.value)}
            rows={2}
            placeholder={t('comments.detail.replyPlaceholder')}
            className={TEXTAREA_CLASS}
          />
          <div className="flex justify-end">
            <Button
              type="button"
              size="sm"
              disabled={!replyBody.trim() || replyPending}
              onClick={onSubmitReply}
            >
              {t('comments.detail.addReply')}
            </Button>
          </div>
        </div>
      </div>

      {/* Actions */}
      <div className="flex flex-col gap-3 border-t border-border-muted pt-4">
        <h3 className="text-[16px] font-semibold leading-6">{t('comments.detail.statusSection')}</h3>
        <div className="flex flex-wrap items-center gap-3">
          <Select
            value={comment.status != null ? String(comment.status) : undefined}
            onValueChange={(v) => onStatusChange(Number(v) as CommentStatus)}
          >
            <SelectTrigger className="h-8 w-[180px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {catalog.items.map((s) => (
                <SelectItem key={s.value} value={String(s.value)}>
                  {catalog.displayLabel(s)}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {statusPending && <span className="text-[12px] text-muted-foreground">{t('common.loading')}</span>}
        </div>

        <div className="flex flex-wrap items-center gap-2">
          {isAuthor && (
            <Button type="button" variant="outline" size="sm" disabled={visibilityPending} onClick={onToggleVisibility}>
              {comment.isPrivate ? <Unlock className="h-4 w-4" /> : <Lock className="h-4 w-4" />}
              {t(comment.isPrivate ? 'comments.detail.makePublic' : 'comments.detail.makePrivate')}
            </Button>
          )}
          {canDelete && (
            <Button type="button" variant="destructive" size="sm" onClick={onDelete}>
              <Trash2 className="h-4 w-4" />
              {t('comments.detail.delete')}
            </Button>
          )}
        </div>
      </div>
    </div>
  );
}

// vue/src/features/comments/CommentDetail.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { useQueryClient } from '@tanstack/vue-query';
import {
  useGetApiCommentsId,
  usePatchApiCommentsId,
  usePostApiCommentsIdVerify,
  usePostApiCommentsIdReplies,
  usePatchApiCommentsIdVisibility,
  useDeleteApiCommentsId,
  getGetApiCommentsIdQueryKey,
  getGetApiProjectsKeyCommentsQueryKey,
  CommentStatus,
} from '@moamen-ui/pointer-vue';
import {
  ExternalLink,
  Lock,
  LockOpen,
  ThumbsUp,
  ThumbsDown,
  Trash2,
  Smartphone,
  Monitor,
} from 'lucide-vue-next';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { extractMessage } from '@/lib/error';
import { formatRelativeTime } from '@/lib/relativeTime';
import { commentStatusLabel, commentStatusVariant, commentEnvironmentLabel, shortSha } from '@/lib/commentLabels';
import { confirm } from '@/composables/useConfirm';
import { toast } from '@/composables/useToast';
import { useAuth } from '@/composables/useAuth';

const props = defineProps<{
  open: boolean;
  id: number | null;
  /** The project key the list is scoped to — used only to invalidate the list query. */
  projectKey: string;
}>();

const emit = defineEmits<{
  (e: 'update:open', value: boolean): void;
  (e: 'deleted'): void;
}>();

const { t } = useI18n();
const { user, isAdmin } = useAuth();
const queryClient = useQueryClient();

const idOrZero = computed(() => props.id ?? 0);
const { data: comment, isLoading } = useGetApiCommentsId(idOrZero, {
  query: { enabled: () => props.open && props.id != null },
});

function close() {
  emit('update:open', false);
}

function reloadAll() {
  if (props.id != null) {
    void queryClient.invalidateQueries({ queryKey: getGetApiCommentsIdQueryKey(props.id) });
  }
  void queryClient.invalidateQueries({ queryKey: getGetApiProjectsKeyCommentsQueryKey(props.projectKey) });
}

function fail(e: unknown) {
  toast(extractMessage(e), 'danger');
}

// ── Permissions (mirrors the API's own gates — hides controls that would 403) ──
const isAuthor = computed(() => !!comment.value && !!user.value && comment.value.authorId === user.value.id);
const isQuickAccess = computed(() => !!user.value?.isQuickAccess);
const canManageStatus = computed(() => !isQuickAccess.value);
const canVerify = computed(
  () => comment.value?.status === CommentStatus.NUMBER_3 && (isAdmin.value || isAuthor.value),
);
const canDelete = computed(() => isAdmin.value || isAuthor.value);
const canToggleVisibility = computed(() => isAuthor.value);

// ── Labels ──────────────────────────────────────────────────────────────
function statusLabel(status: number | undefined): string {
  return commentStatusLabel(t, status);
}
function statusVariant(status: number | undefined) {
  return commentStatusVariant(status);
}
function envLabel(env: number | undefined): string {
  return commentEnvironmentLabel(t, env);
}
function deviceLabel(): string {
  const el = comment.value?.element;
  const dims = el?.viewportWidth && el?.viewportHeight ? `${el.viewportWidth}×${el.viewportHeight}` : null;
  const parts = [el?.deviceType, dims].filter(Boolean);
  return parts.length ? parts.join(' · ') : '—';
}

// ── Status change ─────────────────────────────────────────────────────
const updateStatus = usePatchApiCommentsId();
const savingStatus = ref(false);

async function changeStatus(value: unknown) {
  const status = Number(value) as (typeof CommentStatus)[keyof typeof CommentStatus];
  if (!props.id || !status || status === comment.value?.status) return;
  savingStatus.value = true;
  try {
    await updateStatus.mutateAsync({ id: props.id, data: { status } });
    toast(t('comments.updated'), 'success');
    reloadAll();
  } catch (e) {
    fail(e);
  } finally {
    savingStatus.value = false;
  }
}

// ── Verify (👍 / 👎) ────────────────────────────────────────────────────
const verifyMutation = usePostApiCommentsIdVerify();
const showNotFixedNote = ref(false);
const notFixedNote = ref('');
const verifying = ref(false);

async function verifyOk() {
  if (!props.id) return;
  verifying.value = true;
  try {
    await verifyMutation.mutateAsync({ id: props.id, data: { ok: true } });
    toast(t('comments.verified'), 'success');
    reloadAll();
  } catch (e) {
    fail(e);
  } finally {
    verifying.value = false;
  }
}

function openNotFixed() {
  notFixedNote.value = '';
  showNotFixedNote.value = true;
}

async function submitNotFixed() {
  if (!props.id || !notFixedNote.value.trim()) return;
  verifying.value = true;
  try {
    await verifyMutation.mutateAsync({ id: props.id, data: { ok: false, note: notFixedNote.value.trim() } });
    toast(t('comments.reopened'), 'success');
    showNotFixedNote.value = false;
    reloadAll();
  } catch (e) {
    fail(e);
  } finally {
    verifying.value = false;
  }
}

// ── Replies ───────────────────────────────────────────────────────────
const addReplyMutation = usePostApiCommentsIdReplies();
const replyBody = ref('');
const addingReply = ref(false);

async function addReply() {
  if (!props.id || !replyBody.value.trim()) return;
  addingReply.value = true;
  try {
    await addReplyMutation.mutateAsync({ id: props.id, data: { body: replyBody.value.trim() } });
    replyBody.value = '';
    toast(t('comments.replyAdded'), 'success');
    reloadAll();
  } catch (e) {
    fail(e);
  } finally {
    addingReply.value = false;
  }
}

// ── Visibility (author-only) ───────────────────────────────────────────
const visibilityMutation = usePatchApiCommentsIdVisibility();
const togglingVisibility = ref(false);

async function toggleVisibility() {
  if (!props.id || !comment.value) return;
  togglingVisibility.value = true;
  try {
    await visibilityMutation.mutateAsync({ id: props.id, data: { isPrivate: !comment.value.isPrivate } });
    toast(t('comments.visibilityUpdated'), 'success');
    reloadAll();
  } catch (e) {
    fail(e);
  } finally {
    togglingVisibility.value = false;
  }
}

// ── Delete ──────────────────────────────────────────────────────────────
const deleteMutation = useDeleteApiCommentsId();

async function onDelete() {
  if (!props.id) return;
  const ok = await confirm({
    message: t('comments.deleteConfirm'),
    confirmLabel: t('comments.delete'),
    confirmVariant: 'destructive',
  });
  if (!ok) return;
  try {
    await deleteMutation.mutateAsync({ id: props.id });
    toast(t('comments.deleted'), 'success');
    void queryClient.invalidateQueries({ queryKey: getGetApiProjectsKeyCommentsQueryKey(props.projectKey) });
    emit('deleted');
    close();
  } catch (e) {
    fail(e);
  }
}

// Reset transient UI state whenever a different comment opens.
watch(
  () => props.id,
  () => {
    showNotFixedNote.value = false;
    notFixedNote.value = '';
    replyBody.value = '';
  },
);
</script>

<template>
  <Dialog :open="open" @update:open="(o: boolean) => emit('update:open', o)">
    <DialogContent class="max-w-[440px] sm:max-w-[720px] max-h-[90vh] overflow-y-auto">
      <DialogHeader>
        <DialogTitle class="flex items-center gap-2">
          {{ t('comments.detailTitle') }}
          <Badge v-if="comment" :variant="statusVariant(comment.status)">{{ statusLabel(comment.status) }}</Badge>
        </DialogTitle>
      </DialogHeader>

      <div v-if="isLoading || !comment" class="flex flex-col gap-3 py-4">
        <div class="h-4 w-2/3 rounded bg-gutter animate-pulse" />
        <div class="h-4 w-full rounded bg-gutter animate-pulse" />
        <div class="h-4 w-1/2 rounded bg-gutter animate-pulse" />
      </div>

      <div v-else class="flex flex-col gap-5 py-1">
        <!-- Body + badges -->
        <div class="flex flex-col gap-2">
          <div class="flex flex-wrap items-center gap-2">
            <Badge :variant="statusVariant(comment.status)">{{ statusLabel(comment.status) }}</Badge>
            <Badge variant="neutral">{{ envLabel(comment.environment) }}</Badge>
            <Badge v-if="comment.hasPayloadFlag" variant="danger">{{ t('comments.flaggedBadge') }}</Badge>
            <Badge v-if="comment.isBugReport" variant="neutral">{{ t('comments.bugBadge') }}</Badge>
            <span
              v-if="comment.isPrivate"
              class="inline-flex items-center gap-1 text-[12px] text-muted-foreground"
              :title="t('comments.privateTooltip')"
            >
              <Lock class="h-3 w-3" /> {{ t('comments.privateTooltip') }}
            </span>
          </div>
          <p class="whitespace-pre-wrap text-[14px] text-foreground">{{ comment.body }}</p>
          <p class="text-[12px] text-muted-foreground">
            {{ t('comments.by', { name: comment.authorName ?? '—' }) }}
            · {{ formatRelativeTime(comment.createdAt, t) }}
            <template v-if="comment.editedAt"> · {{ t('comments.edited') }}</template>
          </p>
          <ul v-if="comment.payloadFlags?.length" class="flex flex-col gap-0.5 text-[12px] text-state-danger">
            <li v-for="flag in comment.payloadFlags" :key="flag">{{ flag }}</li>
          </ul>
          <div v-if="comment.pickedActionTexts?.length" class="flex flex-wrap gap-1.5">
            <Badge v-for="(action, idx) in comment.pickedActionTexts" :key="idx" variant="default">
              {{ action }}
            </Badge>
          </div>
        </div>

        <!-- Element -->
        <div v-if="comment.element" class="flex flex-col gap-2 border-t border-border-muted pt-4">
          <span class="text-sm font-medium">{{ t('comments.element') }}</span>
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div class="flex flex-col gap-0.5">
              <span class="text-[12px] text-muted-foreground">{{ t('comments.route') }}</span>
              <code class="font-mono text-[13px] break-all">{{ comment.element.route ?? '—' }}</code>
            </div>
            <div class="flex flex-col gap-0.5">
              <span class="text-[12px] text-muted-foreground">{{ t('comments.pageTitle') }}</span>
              <span class="text-[14px] break-words">{{ comment.element.pageTitle ?? '—' }}</span>
            </div>
            <div class="flex flex-col gap-0.5 sm:col-span-2">
              <span class="text-[12px] text-muted-foreground">{{ t('comments.pageUrl') }}</span>
              <a
                v-if="comment.element.pageUrl"
                :href="comment.element.pageUrl"
                target="_blank"
                rel="noopener noreferrer"
                class="inline-flex items-center gap-1 text-[14px] text-brand hover:underline break-all"
              >
                {{ comment.element.pageUrl }} <ExternalLink class="h-3 w-3 shrink-0" />
              </a>
              <span v-else class="text-[14px] text-muted-foreground">—</span>
            </div>
            <div class="flex flex-col gap-0.5">
              <span class="text-[12px] text-muted-foreground">{{ t('comments.selector') }}</span>
              <code class="font-mono text-[13px] break-all">{{ comment.element.selector ?? '—' }}</code>
            </div>
            <div class="flex flex-col gap-0.5">
              <span class="text-[12px] text-muted-foreground">{{ t('comments.sourcePath') }}</span>
              <code class="font-mono text-[13px] break-all">{{ comment.element.sourcePath ?? '—' }}</code>
            </div>
            <div class="flex flex-col gap-0.5">
              <span class="text-[12px] text-muted-foreground">{{ t('comments.device') }}</span>
              <span class="inline-flex items-center gap-1.5 text-[14px]">
                <Smartphone v-if="comment.element.deviceType === 'mobile'" class="h-3.5 w-3.5 text-muted-foreground" />
                <Monitor v-else class="h-3.5 w-3.5 text-muted-foreground" />
                {{ deviceLabel() }}
              </span>
            </div>
          </div>
          <img
            v-if="comment.element.screenshotUrl"
            :src="comment.element.screenshotUrl"
            :alt="t('comments.screenshot')"
            class="mt-1 max-h-48 w-auto rounded-md border border-border object-contain"
          />
        </div>

        <!-- Applied -->
        <div v-if="comment.appliedAt" class="flex flex-col gap-2 border-t border-border-muted pt-4">
          <span class="text-sm font-medium">{{ t('comments.applied') }}</span>
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div class="flex flex-col gap-0.5">
              <span class="text-[12px] text-muted-foreground">{{ t('comments.appliedBy') }}</span>
              <span class="text-[14px]">{{ comment.appliedByLabel ?? '—' }}</span>
            </div>
            <div class="flex flex-col gap-0.5">
              <span class="text-[12px] text-muted-foreground">{{ t('comments.appliedAt') }}</span>
              <span class="text-[14px]">{{ formatRelativeTime(comment.appliedAt, t) }}</span>
            </div>
            <div v-if="comment.commitUrl" class="flex flex-col gap-0.5">
              <span class="text-[12px] text-muted-foreground">{{ t('comments.commit') }}</span>
              <a
                :href="comment.commitUrl"
                target="_blank"
                rel="noopener noreferrer"
                class="inline-flex items-center gap-1 font-mono text-[13px] text-brand hover:underline"
              >
                {{ shortSha(comment.commitSha) || comment.commitUrl }} <ExternalLink class="h-3 w-3 shrink-0" />
              </a>
            </div>
            <div class="flex flex-col gap-0.5">
              <span class="text-[12px] text-muted-foreground">{{ t('comments.deployState') }}</span>
              <Badge v-if="comment.deployedAt" variant="completed" :title="shortSha(comment.deployedSha)">
                {{ t('comments.liveSince', { date: formatRelativeTime(comment.deployedAt, t) }) }}
              </Badge>
              <Badge v-else variant="neutral">{{ t('comments.notYetLive') }}</Badge>
            </div>
          </div>

          <!-- Verify -->
          <div v-if="canVerify || comment.verifiedAt" class="flex flex-col gap-2 pt-1">
            <p v-if="comment.verifiedAt" class="text-[13px] text-state-completed">
              {{ t('comments.verifiedAt', { date: formatRelativeTime(comment.verifiedAt, t) }) }}
            </p>
            <div v-if="canVerify && !showNotFixedNote" class="flex items-center gap-2">
              <Button type="button" size="sm" variant="secondary" :disabled="verifying" @click="verifyOk">
                <ThumbsUp class="h-4 w-4" /> {{ t('comments.worksButton') }}
              </Button>
              <Button type="button" size="sm" variant="outline" :disabled="verifying" @click="openNotFixed">
                <ThumbsDown class="h-4 w-4" /> {{ t('comments.notFixedButton') }}
              </Button>
            </div>
            <div v-if="showNotFixedNote" class="flex flex-col gap-2">
              <textarea
                v-model="notFixedNote"
                rows="2"
                :placeholder="t('comments.notFixedNotePlaceholder')"
                class="flex w-full rounded-md border border-input bg-transparent px-3 py-1.5 text-sm shadow-sm resize-none"
              />
              <div class="flex items-center gap-2">
                <Button type="button" size="sm" variant="outline" @click="showNotFixedNote = false">
                  {{ t('common.cancel') }}
                </Button>
                <Button
                  type="button"
                  size="sm"
                  variant="destructive"
                  :disabled="!notFixedNote.trim() || verifying"
                  @click="submitNotFixed"
                >
                  {{ t('comments.notFixedButton') }}
                </Button>
              </div>
            </div>
          </div>
        </div>

        <!-- Replies -->
        <div class="flex flex-col gap-2 border-t border-border-muted pt-4">
          <span class="text-sm font-medium">{{ t('comments.replies') }}</span>
          <p v-if="!comment.replies?.length" class="text-[13px] text-muted-foreground italic">
            {{ t('comments.noReplies') }}
          </p>
          <div v-else class="flex flex-col gap-2">
            <div
              v-for="reply in comment.replies"
              :key="reply.id"
              class="flex flex-col gap-0.5 rounded-md bg-gutter px-3 py-2"
            >
              <p class="whitespace-pre-wrap text-[14px]">{{ reply.body }}</p>
              <p class="text-[12px] text-muted-foreground">
                {{ reply.authorName ?? '—' }} · {{ formatRelativeTime(reply.createdAt, t) }}
              </p>
            </div>
          </div>
          <div class="flex flex-col gap-2 pt-1">
            <textarea
              v-model="replyBody"
              rows="2"
              :placeholder="t('comments.replyPlaceholder')"
              class="flex w-full rounded-md border border-input bg-transparent px-3 py-1.5 text-sm shadow-sm resize-none"
            />
            <Button
              type="button"
              size="sm"
              variant="secondary"
              class="self-start"
              :disabled="!replyBody.trim() || addingReply"
              @click="addReply"
            >
              {{ t('comments.addReply') }}
            </Button>
          </div>
        </div>
      </div>

      <DialogFooter class="flex sm:justify-between items-center gap-2">
        <div v-if="comment" class="flex items-center gap-2">
          <Select :model-value="String(comment.status)" :disabled="!canManageStatus || savingStatus" @update:model-value="changeStatus">
            <SelectTrigger class="h-8 w-[9.5rem]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="1">{{ t('comments.statusOpen') }}</SelectItem>
              <SelectItem value="2">{{ t('comments.statusReadyToApply') }}</SelectItem>
              <SelectItem value="3">{{ t('comments.statusApplied') }}</SelectItem>
              <SelectItem value="4">{{ t('comments.statusArchived') }}</SelectItem>
            </SelectContent>
          </Select>
          <Button
            v-if="canToggleVisibility"
            type="button"
            variant="outline"
            size="sm"
            :disabled="togglingVisibility"
            @click="toggleVisibility"
          >
            <LockOpen v-if="comment.isPrivate" class="h-4 w-4" />
            <Lock v-else class="h-4 w-4" />
            {{ t(comment.isPrivate ? 'comments.makePublic' : 'comments.makePrivate') }}
          </Button>
          <Button v-if="canDelete" type="button" variant="outline" size="sm" class="text-destructive" @click="onDelete">
            <Trash2 class="h-4 w-4" /> {{ t('comments.delete') }}
          </Button>
        </div>
        <Button variant="secondary" @click="close">{{ t('common.close') }}</Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>
