// react/src/features/profile/ProfilePage.tsx
// User profile page.
// • /profile           → self-profile (authenticated, any role)
// • /users/:id/profile → admin view of another user (admin only)
//
// Query gating:
//   isAdmin && id != null  → useGetApiAdminUsersIdProfile (enabled)
//   otherwise              → useGetApiMeProfile            (enabled)
import { Fragment, useState } from 'react';
import { useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import {
  useGetApiMeProfile,
  useGetApiAdminUsersIdProfile,
  useGetApiMeApiKey,
  usePostApiMeApiKeyRegenerate,
  type ProfileProject,
  type ProfileEnvironment,
} from '@moamen-ui/pointer-react';
import {
  ChevronDown,
  ChevronRight,
  RefreshCw,
  Key,
  Eye,
  EyeOff,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { cn } from '@/lib/utils';
import { useAuth } from '@/lib/auth';
import { useStatusCatalog } from '@/lib/status-catalog';
import { useToast } from '@/components/ui/toast';
import { ConfirmDialog } from '@/components/ConfirmDialog';
import { CountCell, DiffstatLine, statusTone, toneHeaderClass, toneTextClass } from '@/components/shared/CountCell';
import { useMediaQuery, MOBILE_QUERY } from '@/lib/useMediaQuery';

const ENV_LABEL: Record<number, string> = {
  1: 'Local',
  2: 'Staging',
  3: 'Production',
};

function envLabel(env: number | undefined): string {
  if (env == null) return '—';
  return ENV_LABEL[env] ?? String(env);
}

// ---- Expandable environment row ----
function EnvRows({ environments, catalog }: { environments: ProfileEnvironment[]; catalog: ReturnType<typeof useStatusCatalog> }) {
  return (
    <>
      {environments.map((env) => (
        <TableRow key={env.environment} className="h-11 border-t border-border-muted bg-gutter/30">
          <TableCell className="w-10 px-3" />
          <TableCell className="ps-12 text-[14px] text-muted-foreground italic">
            {envLabel(env.environment)}
          </TableCell>
          <TableCell className="font-mono text-[14px]">{env.comments ?? 0}</TableCell>
          <TableCell className="font-mono text-[14px]">{env.replies ?? 0}</TableCell>
          {catalog.items.map((s) => (
            <TableCell
              key={s.value}
              className={cn(
                'font-mono text-[14px]',
                getEnvStatusCount(env, s.value) > 0
                  ? toneTextClass(statusTone(s.value))
                  : 'text-faint-foreground',
              )}
            >
              {getEnvStatusCount(env, s.value)}
            </TableCell>
          ))}
        </TableRow>
      ))}
    </>
  );
}

export function ProfilePage() {
  const { t } = useTranslation();
  const { id } = useParams<{ id?: string }>();
  const { isAdmin } = useAuth();
  const catalog = useStatusCatalog();
  const { toast } = useToast();
  const isMobile = useMediaQuery(MOBILE_QUERY);

  // Parse numeric id from route params
  const numericId = id != null && id !== '' ? Number(id) : null;
  const showAdmin = isAdmin && numericId != null;

  // Gate queries with `enabled` per the task spec
  const meQuery = useGetApiMeProfile({ query: { enabled: !showAdmin } });
  const adminQuery = useGetApiAdminUsersIdProfile(numericId ?? 0, {
    query: { enabled: showAdmin },
  });

  const { data, isFetching, refetch } = showAdmin ? adminQuery : meQuery;

  // API key state
  const keyQuery = useGetApiMeApiKey();
  const [revealKey, setRevealKey] = useState(false);
  const [confirmRegenerate, setConfirmRegenerate] = useState(false);
  const regenerateMut = usePostApiMeApiKeyRegenerate({
    mutation: {
      onSuccess: () => {
        // Reveal the new key immediately: user just asked for it, old value is dead
        setRevealKey(true);
        keyQuery.refetch();
        toast(t('profile.apiKeyRegenerated'), 'success');
      },
      onError: () => {
        toast(t('profile.error'), 'error');
      },
    },
  });

  const profileUser = data?.user;
  const totals = data?.totals;
  const projects = data?.projects ?? [];

  // API key helpers
  const apiKey = keyQuery.data?.apiKey;
  const maskedKey = (() => {
    if (!apiKey) return '';
    // Use server's prefix when it exists, otherwise first 12 chars
    const prefix = keyQuery.data?.prefix || apiKey.slice(0, 12);
    return `${prefix}${'•'.repeat(24)}`;
  })();

  const lastUsedLabel = (() => {
    const value = keyQuery.data?.lastUsedAt;
    if (!value) return t('profile.apiKeyNeverUsed');
    return new Date(value).toLocaleString();
  })();

  async function copyKey(text: string) {
    try {
      await navigator.clipboard.writeText(text);
      toast(t('profile.copied'), 'success');
    } catch {
      toast(t('demo.copyFailed'), 'error');
    }
  }

  function handleRegenerateClick() {
    setConfirmRegenerate(true);
  }

  function handleRegenerateConfirm() {
    setConfirmRegenerate(false);
    regenerateMut.mutate();
  }

  // Expandable env state: set of expanded project ids
  const [expanded, setExpanded] = useState<Set<number>>(new Set());
  function toggleExpand(id: number) {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  // Build diffstat items: projects · comments · replies · open · ready · completed · archived
  const diffstatItems = [
    { label: t('profile.projects'), count: totals?.projectsInvolved ?? 0 },
    { label: t('profile.comments'), count: totals?.comments ?? 0 },
    { label: t('profile.replies'), count: totals?.replies ?? 0 },
    ...[
      [1, totals?.open ?? 0],
      [2, totals?.readyToApply ?? 0],
      [3, totals?.applied ?? 0],
      [4, totals?.archived ?? 0],
    ].map(([value, count]) => {
      const status = catalog.items.find((x) => x.value === value);
      return {
        label: status ? catalog.displayLabel(status) : t(`overview.${['open', 'pending', 'completed', 'archived'][(value as number) - 1]}`),
        count: count as number,
        tone: statusTone(value as number),
      };
    }),
  ];

  return (
    <div className="flex flex-col gap-8">
      {/* API key section — first, because it is the one thing on this page a person comes here to copy.
           Masked by default: it is a bearer credential, and this page is as likely to be open on a
           shared screen as any other. */}
      <section className="rounded-lg border border-border bg-card p-4">
        <div className="flex items-start justify-between gap-3">
          <div className="flex items-center gap-2">
            <Key className="h-4 w-4 text-muted-foreground" />
            <h2 className="text-[15px] font-semibold leading-6">{t('profile.apiKey')}</h2>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={handleRegenerateClick}
            disabled={keyQuery.isPending || !apiKey || regenerateMut.isPending}
          >
            {regenerateMut.isPending ? (
              <RefreshCw className="h-4 w-4 animate-spin" />
            ) : null}
            {t('profile.regenerateApiKey')}
          </Button>
        </div>

        <p className="mt-1 text-[13px] text-muted-foreground">{t('profile.apiKeyHint')}</p>

        {keyQuery.isPending ? (
          <p className="mt-3 text-[13px] text-muted-foreground">{t('profile.loading')}</p>
        ) : apiKey ? (
          <>
            <div className="mt-3 flex flex-wrap items-center gap-2">
              <code className="flex-1 min-w-[16rem] rounded-md border border-border bg-gutter px-3 py-2 font-mono text-[13px] break-all">
                {revealKey ? apiKey : maskedKey}
              </code>

              <Button
                variant="ghost"
                size="sm"
                onClick={() => setRevealKey(!revealKey)}
              >
                {revealKey ? (
                  <>
                    <EyeOff className="h-4 w-4" />
                    {t('install.wizard.hide')}
                  </>
                ) : (
                  <>
                    <Eye className="h-4 w-4" />
                    {t('install.wizard.reveal')}
                  </>
                )}
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={() => copyKey(apiKey)}
              >
                {t('profile.copyApiKey')}
              </Button>
            </div>

            <p className="mt-2 text-[12px] text-muted-foreground">
              {t('profile.apiKeyLastUsed')}:
              <span className="font-mono"> {lastUsedLabel}</span>
            </p>
          </>
        ) : (
          <p className="mt-3 text-[13px] text-muted-foreground">{t('profile.apiKeyUnavailable')}</p>
        )}
      </section>

      {/* Header with title and refresh */}
      <div className="flex items-center justify-between gap-3">
        <div>
          <h1 className="text-[20px] font-semibold">
            {profileUser?.displayName ?? t('profile.title')}
          </h1>
          {profileUser?.email && (
            <p className="mt-0.5 text-[14px] text-muted-foreground">
              {profileUser.email}
              {profileUser.roleName ? ` · ${profileUser.roleName}` : ''}
            </p>
          )}
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={() => refetch()}
          disabled={isFetching}
        >
          <RefreshCw className={cn('h-4 w-4', isFetching && 'animate-spin')} />
          {t('common.refresh')}
        </Button>
      </div>

      {/* Diffstat line: projects · comments · replies · open · ready · completed · archived */}
      <DiffstatLine items={diffstatItems} />

      {/* Projects section */}
      <div className="space-y-3">
        <h2 className="text-[16px] font-semibold leading-6">{t('overview.projects')}</h2>
        {isMobile ? (
          // Below `md` this list is never a horizontally-scrolling table (DESIGN.md
          // target 1): one bordered card per project, name as the title, comments/
          // replies/status counts as a compact label/value list, environments (when
          // present) expand into nested mini-cards under the same toggle.
          <div className="flex flex-col gap-2">
            {projects.map((proj: ProfileProject) => {
              const projId = proj.projectId ?? 0;
              const hasEnvs = (proj.environments?.length ?? 0) > 0;
              const isOpen = expanded.has(projId);
              return (
                <div key={projId} className="rounded-md border border-border bg-card p-3 flex flex-col gap-2">
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex min-w-0 items-center gap-2">
                      {hasEnvs ? (
                        <button
                          type="button"
                          onClick={() => toggleExpand(projId)}
                          className="flex h-11 w-11 shrink-0 -m-2 items-center justify-center text-muted-foreground hover:text-foreground"
                          aria-label={isOpen ? 'Collapse environments' : 'Expand environments'}
                        >
                          {isOpen ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}
                        </button>
                      ) : (
                        <span className="w-4 shrink-0" />
                      )}
                      <span className="min-w-0 break-words text-[14px] font-medium">{proj.name ?? proj.key}</span>
                    </div>
                    {proj.key && proj.name && (
                      <code className="shrink-0 rounded bg-gutter px-1.5 py-0.5 font-mono text-[13px]">
                        {proj.key}
                      </code>
                    )}
                  </div>
                  <div className="grid grid-cols-2 gap-x-3 gap-y-1 text-[13px]">
                    <span className="text-muted-foreground">{t('overview.comments')}</span>
                    <span className="text-end font-mono">{proj.comments ?? 0}</span>
                    <span className="text-muted-foreground">{t('profile.replies')}</span>
                    <span className="text-end font-mono">{proj.replies ?? 0}</span>
                    {catalog.items.map((s) => (
                      <Fragment key={s.value}>
                        <span className="text-muted-foreground">{catalog.displayLabel(s)}</span>
                        <span className="text-end">
                          <CountCell count={getProjectStatusCount(proj, s.value)} tone={statusTone(s.value)} />
                        </span>
                      </Fragment>
                    ))}
                  </div>

                  {isOpen && hasEnvs && (
                    <div className="flex flex-col gap-2 border-t border-border-muted pt-2">
                      {(proj.environments ?? []).map((env) => (
                        <div key={env.environment} className="rounded-md bg-gutter/40 p-2 flex flex-col gap-1">
                          <span className="text-[13px] italic text-muted-foreground">{envLabel(env.environment)}</span>
                          <div className="grid grid-cols-2 gap-x-3 gap-y-1 text-[12px]">
                            <span className="text-muted-foreground">{t('overview.comments')}</span>
                            <span className="text-end font-mono">{env.comments ?? 0}</span>
                            <span className="text-muted-foreground">{t('profile.replies')}</span>
                            <span className="text-end font-mono">{env.replies ?? 0}</span>
                            {catalog.items.map((s) => (
                              <Fragment key={s.value}>
                                <span className="text-muted-foreground">{catalog.displayLabel(s)}</span>
                                <span
                                  className={cn(
                                    'text-end font-mono',
                                    getEnvStatusCount(env, s.value) > 0
                                      ? toneTextClass(statusTone(s.value))
                                      : 'text-faint-foreground',
                                  )}
                                >
                                  {getEnvStatusCount(env, s.value)}
                                </span>
                              </Fragment>
                            ))}
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              );
            })}
            {projects.length === 0 && !isFetching && (
              <p className="rounded-md border border-dashed border-border-muted p-3 text-[14px] text-muted-foreground">
                {t('profile.noProjects')}
              </p>
            )}
          </div>
        ) : (
        <div className="rounded-md border border-border overflow-hidden">
          <Table>
            <TableHeader className="[&_tr]:bg-gutter [&_tr]:border-0">
              <TableRow className="h-10 bg-gutter">
                <TableHead className="text-[13px] font-medium text-muted-foreground" />
                <TableHead className="text-[13px] font-medium text-muted-foreground">{t('overview.name')}</TableHead>
                <TableHead className="text-[13px] font-medium text-muted-foreground">{t('overview.comments')}</TableHead>
                <TableHead className="text-[13px] font-medium text-muted-foreground">{t('profile.replies')}</TableHead>
                {catalog.items.map((s) => (
                  <TableHead key={s.value} className={cn('text-[13px] font-medium', toneHeaderClass(statusTone(s.value)))}>
                    {catalog.displayLabel(s)}
                  </TableHead>
                ))}
              </TableRow>
            </TableHeader>
            <TableBody className="[&_tr]:border-b-0">
              {projects.map((proj: ProfileProject, idx: number) => {
                const projId = proj.projectId ?? 0;
                const hasEnvs = (proj.environments?.length ?? 0) > 0;
                const isOpen = expanded.has(projId);

                return [
                  <TableRow key={projId} className="h-11 border-t border-border-muted">
                    <TableCell className="w-10 text-end font-mono text-[12px] text-faint-foreground">
                      {idx + 1}
                    </TableCell>
                    <TableCell className="px-3">
                      <div className="flex items-center gap-2">
                        {hasEnvs ? (
                          <button
                            type="button"
                            onClick={() => toggleExpand(projId)}
                            className="text-muted-foreground hover:text-foreground"
                            aria-label={isOpen ? 'Collapse environments' : 'Expand environments'}
                          >
                            {isOpen ? (
                              <ChevronDown className="h-4 w-4" />
                            ) : (
                              <ChevronRight className="h-4 w-4" />
                            )}
                          </button>
                        ) : (
                          <span className="w-4" />
                        )}
                        <span className="text-[14px] font-medium">{proj.name ?? proj.key}</span>
                        {proj.key && proj.name && (
                          <code className="rounded bg-gutter px-1.5 py-0.5 font-mono text-[13px]">
                            {proj.key}
                          </code>
                        )}
                      </div>
                    </TableCell>
                    <TableCell className="font-mono text-[14px]">{proj.comments ?? 0}</TableCell>
                    <TableCell className="font-mono text-[14px]">{proj.replies ?? 0}</TableCell>
                    {catalog.items.map((s) => {
                      const count = getProjectStatusCount(proj, s.value);
                      return (
                        <TableCell key={s.value} className="text-end">
                          <CountCell count={count} tone={statusTone(s.value)} />
                        </TableCell>
                      );
                    })}
                  </TableRow>,
                  ...(isOpen && hasEnvs
                    ? [
                        <EnvRows
                          key={`env-${projId}`}
                          environments={proj.environments ?? []}
                          catalog={catalog}
                        />,
                      ]
                    : []),
                ];
              })}
              {projects.length === 0 && !isFetching && (
                <TableRow className="h-11 border-t border-border-muted">
                  <TableCell
                    colSpan={4 + catalog.items.length}
                    className="px-3 text-center text-[14px] text-muted-foreground"
                  >
                    {t('profile.noProjects')}
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </div>
        )}
      </div>

      <ConfirmDialog
        open={confirmRegenerate}
        message={t('profile.regenerateApiKeyConfirm')}
        confirmLabel={t('profile.regenerateApiKey')}
        confirmColor="warn"
        onConfirm={handleRegenerateConfirm}
        onCancel={() => setConfirmRegenerate(false)}
      />
    </div>
  );
}

// ---- helpers ----
function getProjectStatusCount(proj: ProfileProject, value: number | undefined): number {
  switch (value) {
    case 1: return proj.open ?? 0;
    case 2: return proj.readyToApply ?? 0;
    case 3: return proj.applied ?? 0;
    case 4: return proj.archived ?? 0;
    default: return 0;
  }
}

function getEnvStatusCount(env: ProfileEnvironment, value: number | undefined): number {
  switch (value) {
    case 1: return env.open ?? 0;
    case 2: return env.readyToApply ?? 0;
    case 3: return env.applied ?? 0;
    case 4: return env.archived ?? 0;
    default: return 0;
  }
}

// vue/src/features/profile/ProfilePage.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { useRoute } from 'vue-router';
import { useI18n } from 'vue-i18n';
import {
  useGetApiMeProfile,
  useGetApiAdminUsersIdProfile,
  useGetApiMeApiKey,
  usePostApiMeApiKeyRegenerate,
  type ProfileProject,
  type ProfileEnvironment,
} from '@moamen-ui/pointer-vue';
import {
  ChevronDown,
  ChevronRight,
  Key,
  Copy,
  Loader2,
  Eye,
  EyeOff,
} from 'lucide-vue-next';
import { Button } from '@/components/ui/button';
import { useAuth } from '@/composables/useAuth';
import { statusTone, toneHeaderClass, toneTextClass } from '@/lib/statusTone';
import { useStatusCatalog } from '@/composables/useStatusCatalog';
import { toast } from '@/composables/useToast';
import { confirm } from '@/composables/useConfirm';
import Diffstat from '@/components/shared/Diffstat.vue';
import CountCell from '@/components/shared/CountCell.vue';

const { t } = useI18n();
const route = useRoute();
const { isAdmin } = useAuth();
const { items: statusItems, displayLabelFor: statusLabel } = useStatusCatalog();

// API key state
const apiKeyQuery = useGetApiMeApiKey();
const apiKeyMutation = usePostApiMeApiKeyRegenerate({
  mutation: {
    onSuccess: () => {
      revealKey.value = true;
      apiKeyQuery.refetch();
      toast(t('profile.apiKeyRegenerated'), 'success');
    },
    onError: () => {
      toast(t('profile.error'), 'danger');
    },
  },
});
const revealKey = ref(false);
const isRegenerating = computed(() => apiKeyMutation.isPending.value);

const apiKeyValue = computed(() => apiKeyQuery.data.value?.apiKey ?? null);
const apiKeyPrefix = computed(() => apiKeyQuery.data.value?.prefix);
const apiKeyLastUsedAt = computed(() => apiKeyQuery.data.value?.lastUsedAt);

const maskedApiKey = computed(() => {
  const key = apiKeyValue.value;
  if (!key) return '';
  // Use the server-sent prefix if available, otherwise the first 12 chars of the key
  const prefix = apiKeyPrefix.value || key.slice(0, 12);
  return `${prefix}${'•'.repeat(24)}`;
});

const lastUsedLabel = computed(() => {
  if (!apiKeyLastUsedAt.value) {
    return t('profile.apiKeyNeverUsed');
  }
  return new Date(apiKeyLastUsedAt.value).toLocaleString();
});

async function handleRegenerateKey() {
  const ok = await confirm({
    message: t('profile.regenerateApiKeyConfirm'),
    confirmLabel: t('profile.regenerateApiKey'),
    confirmVariant: 'destructive',
  });
  if (ok) {
    apiKeyMutation.mutate();
  }
}

function copyApiKey() {
  const key = apiKeyValue.value;
  if (!key) return;
  navigator.clipboard?.writeText(key).then(
    () => toast(t('profile.copied'), 'success'),
    () => toast(t('demo.copyFailed'), 'danger'),
  );
}

// Determine if this is an admin viewing another user's profile.
const routeId = computed(() => {
  const raw = route.params.id;
  const n = Number(Array.isArray(raw) ? raw[0] : raw);
  return Number.isFinite(n) && n > 0 ? n : null;
});

// Fire exactly one query via reactive `enabled`.
const isAdminView = computed(() => isAdmin.value && routeId.value != null);

// Admin query: GET /api/admin/users/{id}/profile
const adminQuery = useGetApiAdminUsersIdProfile(
  computed(() => routeId.value ?? 0),
  { query: { enabled: computed(() => isAdminView.value) } },
);

// Me query: GET /api/me/profile
const meQuery = useGetApiMeProfile(
  { query: { enabled: computed(() => !isAdminView.value) } },
);

const data = computed(() => isAdminView.value ? adminQuery.data.value : meQuery.data.value);
const isLoading = computed(() => isAdminView.value ? adminQuery.isLoading.value : meQuery.isLoading.value);
const isError = computed(() => isAdminView.value ? adminQuery.isError.value : meQuery.isError.value);

const profileUser = computed(() => data.value?.user);
const totals = computed(() => data.value?.totals);
const projects = computed<ProfileProject[]>(() => data.value?.projects ?? []);

// Status value constants.
const STATUS_OPEN = 1;
const STATUS_READY = 2;
const STATUS_APPLIED = 3;
const STATUS_ARCHIVED = 4;

const ENV_NAMES: Record<number, string> = { 1: 'Local', 2: 'Staging', 3: 'Production' };

function envName(env: number): string {
  return ENV_NAMES[env] ?? String(env);
}

// Track which project rows have their environment panel expanded.
const expanded = ref<Set<number>>(new Set());
function toggleExpand(projectId: number) {
  const s = new Set(expanded.value);
  if (s.has(projectId)) {
    s.delete(projectId);
  } else {
    s.add(projectId);
  }
  expanded.value = s;
}

// Build status breakdown for a project or environment row.
type StatusBucket = { value: number; count: number };
function statusBuckets(row: ProfileProject | ProfileEnvironment): StatusBucket[] {
  return [
    { value: STATUS_OPEN,     count: row.open ?? 0 },
    { value: STATUS_READY,    count: row.readyToApply ?? 0 },
    { value: STATUS_APPLIED,  count: row.applied ?? 0 },
    { value: STATUS_ARCHIVED, count: row.archived ?? 0 },
  ];
}

// Build diffstat items for the profile header
const diffstatItems = computed(() => {
  const t_totals = totals.value;
  if (!t_totals) return [];

  return [
    { count: t_totals.projectsInvolved ?? 0, label: t('profile.projects'), severity: undefined as any },
    { count: t_totals.comments ?? 0, label: t('profile.comments'), severity: undefined as any },
    { count: t_totals.replies ?? 0, label: t('profile.replies'), severity: undefined as any },
    { count: t_totals.open ?? 0, label: statusLabel(STATUS_OPEN), severity: 'open' as const },
    { count: t_totals.readyToApply ?? 0, label: statusLabel(STATUS_READY), severity: 'ready' as const },
    { count: t_totals.applied ?? 0, label: statusLabel(STATUS_APPLIED), severity: 'completed' as const },
    { count: t_totals.archived ?? 0, label: statusLabel(STATUS_ARCHIVED), severity: 'archived' as const },
  ];
});

// Get environment names for a project
function getEnvironmentNames(proj: ProfileProject): string {
  return (proj.environments ?? [])
    .map(e => envName(e.environment ?? 0))
    .join(', ');
}
</script>

<template>
  <div class="flex flex-col gap-6">
    <!-- Loading bar -->
    <div v-if="isLoading" class="h-0.5 w-full overflow-hidden rounded bg-muted">
      <div class="h-full w-1/3 animate-pulse bg-brand" />
    </div>

    <!-- Error state -->
    <p v-else-if="isError" class="text-[14px] text-state-danger">
      {{ t('profile.loadError') }}
    </p>

    <template v-else-if="data">
      <!-- API key section — first, because it is the one thing on this page a person comes here to copy.
           Masked by default: it is a bearer credential. -->
      <section class="rounded-lg border border-border bg-card p-4">
        <div class="flex items-start justify-between gap-3">
          <div class="flex items-center gap-2">
            <Key :size="16" class="text-muted-foreground" />
            <h2 class="text-[15px] font-semibold leading-6">{{ t('profile.apiKey') }}</h2>
          </div>
          <Button
            variant="secondary"
            size="sm"
            :disabled="isRegenerating || !apiKeyValue"
            @click="handleRegenerateKey"
            class="shrink-0"
          >
            <Loader2 v-if="isRegenerating" :size="16" class="animate-spin" />
            {{ t('profile.regenerateApiKey') }}
          </Button>
        </div>

        <p class="mt-1 text-[13px] text-muted-foreground">{{ t('profile.apiKeyHint') }}</p>

        <div v-if="apiKeyQuery.isLoading.value" class="mt-3 text-[13px] text-muted-foreground">
          {{ t('profile.loading') }}
        </div>
        <div v-else-if="apiKeyValue" class="mt-3 flex flex-wrap items-center gap-2">
          <code class="flex-1 min-w-[16rem] rounded-md border border-border bg-gutter px-3 py-2 font-mono text-[13px] break-all">
            {{ revealKey ? apiKeyValue : maskedApiKey }}
          </code>

          <Button
            variant="ghost"
            size="sm"
            type="button"
            @click="revealKey = !revealKey"
            class="text-muted-foreground hover:text-foreground"
          >
            <component :is="revealKey ? EyeOff : Eye" :size="16" class="me-2" />
            {{ revealKey ? t('install.wizard.hide') : t('install.wizard.reveal') }}
          </Button>
          <Button
            variant="secondary"
            size="sm"
            @click="copyApiKey"
          >
            <Copy :size="16" class="me-2" />
            {{ t('profile.copyApiKey') }}
          </Button>
        </div>
        <div v-else class="mt-3 text-[13px] text-muted-foreground">
          {{ t('profile.apiKeyUnavailable') }}
        </div>

        <p v-if="apiKeyValue" class="mt-2 text-[12px] text-muted-foreground">
          {{ t('profile.apiKeyLastUsed') }}:
          <span class="font-mono">{{ lastUsedLabel }}</span>
        </p>
      </section>

      <!-- Title row: display name -->
      <div>
        <h1 class="text-[20px] leading-7 font-semibold tracking-[-0.01em]">
          {{ profileUser?.displayName ?? t('profile.unknownUser') }}
        </h1>
        <p class="text-[14px] text-muted-foreground">
          {{ profileUser?.email }}
          <span v-if="profileUser?.roleName" class="ms-2">· {{ profileUser.roleName }}</span>
        </p>
      </div>

      <!-- Diffstat line -->
      <Diffstat v-if="diffstatItems.length > 0" :items="diffstatItems" class="mb-6" />

      <!-- Projects table -->
      <div v-if="projects.length > 0">
        <h2 class="text-[16px] font-semibold leading-6 mb-3">{{ t('overview.projects') }}</h2>

        <div class="rounded-md border border-border overflow-hidden">
          <!-- Table header (§3 grammar) -->
          <div class="h-10 bg-gutter text-[13px] font-medium text-muted-foreground flex items-center border-b border-border-muted">
            <div class="w-10 text-end font-mono text-[12px] text-faint-foreground px-3" />
            <div class="flex-1 min-w-0 px-3">{{ t('overview.name') }}</div>
            <div class="w-40 px-3">{{ t('overview.environments') }}</div>
            <!-- Dynamic status columns from catalog (fixed width) -->
            <div
              v-for="status in statusItems"
              :key="`header-${status.value}`"
              class="w-24 text-end px-3 text-[13px] font-medium"
              :class="toneHeaderClass(statusTone(status.value))"
            >
              {{ statusLabel(status.value) }}
            </div>
          </div>

          <!-- Table body -->
          <div>
            <template v-for="(proj, idx) in projects" :key="proj.projectId">
              <!-- Project row -->
              <button
                type="button"
                class="w-full h-11 border-t border-border-muted hover:bg-gutter/60 transition-colors flex items-center text-start"
                @click="toggleExpand(proj.projectId ?? 0)"
              >
                <!-- Gutter column (row number) -->
                <div class="w-10 text-end font-mono text-[12px] text-faint-foreground px-3">
                  {{ idx + 1 }}
                </div>

                <!-- Name + key chip (min-w-[260px] to prevent overlap at 1440) -->
                <div class="flex-1 min-w-0 px-3 flex items-center gap-2">
                  <component
                    :is="expanded.has(proj.projectId ?? 0) ? ChevronDown : ChevronRight"
                    class="h-4 w-4 flex-shrink-0 text-muted-foreground"
                  />
                  <span class="text-[14px] font-medium">{{ proj.name }}</span>
                  <code class="rounded bg-gutter px-1.5 py-0.5 text-[13px] font-mono text-faint-foreground">
                    {{ proj.key }}
                  </code>
                </div>

                <!-- Environments column (w-40 fixed width) -->
                <div class="w-40 px-3 text-[14px] text-muted-foreground">
                  {{ getEnvironmentNames(proj) || '—' }}
                </div>

                <!-- Count cells per status (w-24 fixed width, text-end) -->
                <template v-for="status in statusItems" :key="`cell-${status.value}`">
                  <div class="w-24 text-end px-3">
                    <CountCell
                      :count="statusBuckets(proj).find(b => b.value === status.value)?.count ?? 0"
                      :severity="status.value === STATUS_OPEN ? 'open' : status.value === STATUS_READY ? 'ready' : status.value === STATUS_APPLIED ? 'completed' : 'archived'"
                      :show-glyph="true"
                    />
                  </div>
                </template>
              </button>

              <!-- Expandable environment rows -->
              <template v-if="expanded.has(proj.projectId ?? 0) && (proj.environments?.length ?? 0) > 0">
                <div
                  v-for="env in proj.environments"
                  :key="`env-${proj.projectId}-${env.environment}`"
                  class="h-11 border-t border-border-muted bg-gutter/30 flex items-center text-[14px]"
                >
                  <!-- Gutter -->
                  <div class="w-10 px-3" />

                  <!-- Environment name (indented, min-w-[260px]) -->
                  <div class="flex-1 min-w-0 px-3 flex items-center gap-2">
                    <span class="text-muted-foreground">↳</span>
                    <span class="text-muted-foreground italic">{{ envName(env.environment ?? 0) }}</span>
                  </div>

                  <!-- Empty environments column (w-40) -->
                  <div class="w-40 px-3" />

                  <!-- Count cells for environment (w-24 fixed width) -->
                  <template v-for="status in statusItems" :key="`env-${status.value}`">
                    <div class="w-24 text-end px-3">
                      <CountCell
                        :count="statusBuckets(env).find(b => b.value === status.value)?.count ?? 0"
                        :severity="status.value === STATUS_OPEN ? 'open' : status.value === STATUS_READY ? 'ready' : status.value === STATUS_APPLIED ? 'completed' : 'archived'"
                        :show-glyph="true"
                      />
                    </div>
                  </template>
                </div>
              </template>
            </template>
          </div>
        </div>
      </div>

      <!-- Empty state (three ghost rows with dashed borders per §3) -->
      <div v-else class="rounded-md border border-border overflow-hidden">
        <!-- Table header -->
        <div class="h-10 bg-gutter text-[13px] font-medium text-muted-foreground flex items-center border-b border-border-muted">
          <div class="w-10 text-end font-mono text-[12px] text-faint-foreground px-3" />
          <div class="flex-1 min-w-0 px-3">{{ t('overview.name') }}</div>
          <div class="w-40 px-3">{{ t('overview.environments') }}</div>
          <!-- Dynamic status columns from catalog -->
          <div
            v-for="status in statusItems"
            :key="`header-${status.value}`"
            class="w-24 text-end px-3 text-[13px] font-medium"
            :class="toneTextClass(statusTone(status.value))"
          >
            {{ statusLabel(status.value) }}
          </div>
        </div>

        <!-- Empty ghost rows (three dashed rows per §3) -->
        <div>
          <div v-for="i in 3" :key="`ghost-${i}`" class="h-11 border-t border-border-muted border-dashed flex">
            <template v-if="i === 1">
              <div class="w-10 px-3" />
              <div class="flex-1 min-w-0 px-3 text-[14px] text-muted-foreground">{{ t('profile.noProjects') }}</div>
            </template>
          </div>
        </div>
      </div>
    </template>
  </div>
</template>
