// react/src/components/shared/RowActionsMenu.tsx
import { MoreVertical } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { cn } from '@/lib/utils';
import type { RowActionItem, Severity } from './types';

/**
 * The single severity → class mapping for menu items. Before this component,
 * every feature page hand-duplicated `className="text-destructive focus:text-destructive"`
 * on its delete items; now severity styling lives in exactly one place. The class is
 * applied to both the item and its icon (the icon inherits the item's currentColor,
 * but the explicit class keeps that true even if the base styles change).
 */
const severityClass: Record<Severity, string> = {
  danger: 'text-destructive focus:text-destructive',
  success: 'text-success focus:text-success',
  warning: 'text-warning focus:text-warning',
  // Primary and neutral keep the default menu-item text color.
  primary: '',
  neutral: '',
};

/**
 * The kebab trigger + item list every table's "Actions" column renders. Pass the
 * row's *already permission/feature-gated* item list — this component only owns
 * menu chrome/styling, never business rules about which items exist. Renders
 * nothing when the caller gates everything out (items.length === 0).
 */
export function RowActionsMenu({
  items,
  ariaLabel = 'Actions',
}: {
  items: RowActionItem[];
  ariaLabel?: string;
}) {
  if (items.length === 0) return null;

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" size="icon" aria-label={ariaLabel}>
          <MoreVertical className="h-4 w-4" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        {items.map((item) => {
          const severity = item.severity ?? 'neutral';
          const cls = severityClass[severity];
          const Icon = item.icon;
          return (
            <DropdownMenuItem
              key={item.label}
              disabled={item.disabled}
              title={item.disabled ? item.tooltip : undefined}
              className={cn(cls)}
              onSelect={() => item.onClick()}
            >
              {Icon && <Icon className={cn('h-4 w-4', cls)} />}
              {item.label}
            </DropdownMenuItem>
          );
        })}
      </DropdownMenuContent>
    </DropdownMenu>
  );
}

// vue/src/components/shared/RowActionsMenu.vue
<script setup lang="ts">
import { MoreVertical } from 'lucide-vue-next';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import type { RowActionItem } from './types';

defineProps<{
  items: RowActionItem[];
  /** Accessible label for the trigger button — supplied (translated) by the caller. */
  ariaLabel: string;
}>();

// The single place severity maps to styling. Applied to the menu item; the icon
// inherits `currentColor`, so item and icon stay in sync from this one mapping.
function severityClass(severity?: RowActionItem['severity']): string {
  switch (severity) {
    case 'danger':
      return 'text-destructive focus:text-destructive';
    case 'success':
      return 'text-success focus:text-success';
    case 'warning':
      return 'text-warning focus:text-warning';
    // 'primary' and 'neutral' keep the default menu-item styling.
    default:
      return '';
  }
}
</script>

<template>
  <!-- No items (e.g. permissions gate said so) → render nothing at all. -->
  <DropdownMenu v-if="items.length > 0">
    <DropdownMenuTrigger as-child>
      <Button variant="ghost" size="icon" :aria-label="ariaLabel">
        <MoreVertical class="h-4 w-4" />
      </Button>
    </DropdownMenuTrigger>
    <DropdownMenuContent align="end">
      <!-- Keyed by index: duplicate labels are plausible and must not crash. -->
      <DropdownMenuItem
        v-for="(item, index) in items"
        :key="index"
        :class="severityClass(item.severity)"
        :disabled="item.disabled"
        :title="item.disabled ? item.tooltip : undefined"
        @select="item.onClick()"
      >
        <component :is="item.icon" v-if="item.icon" class="h-4 w-4" />
        {{ item.label }}
      </DropdownMenuItem>
    </DropdownMenuContent>
  </DropdownMenu>
</template>
