// react/src/components/shared/RowActionsMenu.tsx
import { MoreVertical } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { cn } from '@/lib/utils';
import type { RowActionItem, Severity } from './types';

/**
 * The single severity → class mapping for menu items. Before this component,
 * every feature page hand-duplicated `className="text-destructive focus:text-destructive"`
 * on its delete items; now severity styling lives in exactly one place. The class is
 * applied to both the item and its icon (the icon inherits the item's currentColor,
 * but the explicit class keeps that true even if the base styles change).
 */
const severityClass: Record<Severity, string> = {
  danger: 'text-destructive focus:text-destructive',
  success: 'text-success focus:text-success',
  warning: 'text-warning focus:text-warning',
  // Primary and neutral keep the default menu-item text color.
  primary: '',
  neutral: '',
};

/**
 * The kebab trigger + item list every table's "Actions" column renders. Pass the
 * row's *already permission/feature-gated* item list — this component only owns
 * menu chrome/styling, never business rules about which items exist. Renders
 * nothing when the caller gates everything out (items.length === 0).
 */
export function RowActionsMenu({
  items,
  ariaLabel = 'Actions',
}: {
  items: RowActionItem[];
  ariaLabel?: string;
}) {
  if (items.length === 0) return null;

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" size="icon" aria-label={ariaLabel}>
          <MoreVertical className="h-4 w-4" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        {items.map((item) => {
          const severity = item.severity ?? 'neutral';
          const cls = severityClass[severity];
          const Icon = item.icon;
          return (
            <DropdownMenuItem
              key={item.label}
              disabled={item.disabled}
              title={item.disabled ? item.tooltip : undefined}
              className={cn(cls)}
              onSelect={() => item.onClick()}
            >
              {Icon && <Icon className={cn('h-4 w-4', cls)} />}
              {item.label}
            </DropdownMenuItem>
          );
        })}
      </DropdownMenuContent>
    </DropdownMenu>
  );
}

// angular/src/app/shared/row-actions-menu/row-actions-menu.component.ts
import { Component, input } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule } from '@angular/material/menu';
import { MatTooltipModule } from '@angular/material/tooltip';
import { SeverityDirective } from '../severity.directive';
import type { Severity } from '../severity';

export interface RowActionItem {
  label: string;
  /** Material icon ligature name. */
  icon?: string;
  severity?: Severity;
  disabled?: boolean;
  /** Shown on the item when `disabled` (e.g. "requires the app URL to be set"). */
  tooltip?: string;
  onClick: () => void;
}

/**
 * The kebab-menu trigger + item list every table's "Actions" column renders. Pass the row's
 * *already permission/feature-gated* item list — this component only owns menu chrome/styling,
 * never business rules about which items exist:
 *
 *   <app-row-actions-menu [items]="actionsFor(row)" />
 */
@Component({
  selector: 'app-row-actions-menu',
  standalone: true,
  imports: [MatButtonModule, MatIconModule, MatMenuModule, MatTooltipModule, SeverityDirective],
  template: `
    @if (items().length > 0) {
      <button mat-icon-button [matMenuTriggerFor]="menu" [attr.aria-label]="ariaLabel()">
        <mat-icon>more_vert</mat-icon>
      </button>
      <mat-menu #menu="matMenu">
        @for (item of items(); track item.label) {
          <button
            mat-menu-item
            [appSeverity]="item.severity ?? 'neutral'"
            [disabled]="!!item.disabled"
            [matTooltip]="item.disabled ? (item.tooltip ?? '') : ''"
            (click)="item.onClick()"
          >
            @if (item.icon) {
              <mat-icon [appSeverity]="item.severity ?? 'neutral'">{{ item.icon }}</mat-icon>
            }
            {{ item.label }}
          </button>
        }
      </mat-menu>
    }
  `,
})
export class RowActionsMenuComponent {
  readonly items = input.required<RowActionItem[]>();
  readonly ariaLabel = input('Actions');
}
