// vue/src/components/TourSpotlight.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { Compass, ArrowRight, ArrowLeft, X } from 'lucide-vue-next';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { useTour } from '@/lib/tour';

type TargetRect = {
  top: number;
  left: number;
  width: number;
  height: number;
};

const { t, locale } = useI18n();
const isRtl = computed(() => locale.value === 'ar');

const {
  isOpen,
  promptOpen,
  currentStep,
  currentStepIndex,
  totalSteps,
  nextStep,
  prevStep,
  endTour,
  startTour,
  dismissPrompt,
} = useTour();

const rect = ref<TargetRect | null>(null);

function updateRect() {
  if (!isOpen.value || !currentStep.value) {
    rect.value = null;
    return;
  }

  const el = document.querySelector(currentStep.value.targetSelector);
  if (!el) {
    setTimeout(() => {
      const retryEl = document.querySelector(currentStep.value?.targetSelector ?? '');
      if (retryEl) {
        retryEl.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
        const r = retryEl.getBoundingClientRect();
        rect.value = { top: r.top, left: r.left, width: r.width, height: r.height };
      }
    }, 300);
    return;
  }

  el.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
  const r = el.getBoundingClientRect();
  rect.value = { top: r.top, left: r.left, width: r.width, height: r.height };
}

watch([isOpen, currentStep], () => {
  updateRect();
});

onMounted(() => {
  window.addEventListener('resize', updateRect);
  window.addEventListener('scroll', updateRect, true);
});

onUnmounted(() => {
  window.removeEventListener('resize', updateRect);
  window.removeEventListener('scroll', updateRect, true);
});

const isLastStep = computed(() => currentStepIndex.value === totalSteps - 1);
const pad = 6;

const cardStyle = computed(() => {
  if (!rect.value) {
    return {
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
    };
  }

  const padSize = 12;
  const cardWidth = 360;
  const cardHeight = 220;

  const viewportW = window.innerWidth;
  const viewportH = window.innerHeight;

  let top = rect.value.top + rect.value.height + padSize;
  let left = rect.value.left;

  if (top + cardHeight > viewportH - 20) {
    top = Math.max(20, rect.value.top - cardHeight - padSize);
  }

  if (left + cardWidth > viewportW - 20) {
    left = Math.max(20, viewportW - cardWidth - 20);
  }
  if (left < 20) left = 20;

  return {
    top: `${Math.round(top)}px`,
    left: `${Math.round(left)}px`,
  };
});
</script>

<template>
  <!-- Welcome Prompt Dialog -->
  <Dialog :open="promptOpen" @update:open="(val) => !val && dismissPrompt()">
    <DialogContent class="max-w-md">
      <DialogHeader>
        <DialogTitle class="flex items-center gap-2">
          <Compass class="h-5 w-5 text-brand" />
          {{ t('tour.welcomePromptTitle') }}
        </DialogTitle>
        <DialogDescription class="pt-2 text-sm leading-relaxed text-muted-foreground">
          {{ t('tour.welcomePromptDesc') }}
        </DialogDescription>
      </DialogHeader>
      <DialogFooter class="mt-4 flex gap-2 sm:justify-end">
        <Button variant="outline" @click="dismissPrompt">
          {{ t('tour.skipTour') }}
        </Button>
        <Button class="gap-1.5" @click="startTour">
          <Compass class="h-4 w-4" />
          {{ t('tour.startTour') }}
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>

  <!-- Interactive Spotlight Tour Overlay -->
  <div v-if="isOpen && currentStep" class="fixed inset-0 z-50 overflow-hidden">
    <!-- SVG Dimming Mask -->
    <svg class="absolute inset-0 h-full w-full pointer-events-auto">
      <defs>
        <mask id="vue-tour-spotlight-mask">
          <rect x="0" y="0" width="100%" height="100%" fill="white" />
          <rect
            v-if="rect"
            :x="rect.left - pad"
            :y="rect.top - pad"
            :width="rect.width + pad * 2"
            :height="rect.height + pad * 2"
            rx="8"
            fill="black"
          />
        </mask>
      </defs>
      <rect
        x="0"
        y="0"
        width="100%"
        height="100%"
        fill="rgba(0, 0, 0, 0.72)"
        mask="url(#vue-tour-spotlight-mask)"
      />
    </svg>

    <!-- Highlight ring around target element -->
    <div
      v-if="rect"
      class="pointer-events-none absolute rounded-lg border-2 border-brand shadow-[0_0_15px_rgba(var(--brand-rgb,59,130,246),0.5)] transition-all duration-300"
      :style="{
        top: `${rect.top - pad}px`,
        left: `${rect.left - pad}px`,
        width: `${rect.width + pad * 2}px`,
        height: `${rect.height + pad * 2}px`,
      }"
    />

    <!-- Floating Popover Step Card -->
    <div
      class="absolute z-50 w-[360px] max-w-[calc(100vw-40px)] rounded-xl border border-border bg-card p-4 shadow-2xl transition-all duration-200"
      :style="cardStyle"
    >
      <div class="flex items-center justify-between pb-2 border-b border-border/60">
        <span class="text-[0.75rem] font-semibold uppercase tracking-wider text-brand">
          {{ t('tour.stepCount', { current: currentStepIndex + 1, total: totalSteps }) }}
        </span>
        <button
          type="button"
          class="rounded-md p-1 text-muted-foreground hover:bg-muted hover:text-foreground"
          :aria-label="t('tour.skipTour')"
          @click="endTour"
        >
          <X class="h-4 w-4" />
        </button>
      </div>

      <div class="mt-3">
        <h4 class="text-sm font-semibold text-foreground">
          {{ t(currentStep.titleKey) }}
        </h4>
        <p class="mt-1.5 text-xs leading-relaxed text-muted-foreground">
          {{ t(currentStep.descriptionKey) }}
        </p>
      </div>

      <div class="mt-4 flex items-center justify-between pt-2">
        <Button
          variant="ghost"
          size="sm"
          class="text-xs text-muted-foreground hover:text-foreground"
          @click="endTour"
        >
          {{ t('tour.skipTour') }}
        </Button>

        <div class="flex items-center gap-2">
          <Button
            v-if="currentStepIndex > 0"
            variant="outline"
            size="sm"
            class="h-8 text-xs"
            @click="prevStep"
          >
            <ArrowRight v-if="isRtl" class="h-3.5 w-3.5" />
            <ArrowLeft v-else class="h-3.5 w-3.5" />
            {{ t('tour.back') }}
          </Button>

          <Button size="sm" class="h-8 gap-1.5 text-xs" @click="nextStep">
            <span>{{ isLastStep ? t('tour.finish') : t('tour.next') }}</span>
            <template v-if="!isLastStep">
              <ArrowLeft v-if="isRtl" class="h-3.5 w-3.5" />
              <ArrowRight v-else class="h-3.5 w-3.5" />
            </template>
          </Button>
        </div>
      </div>
    </div>
  </div>
</template>

// angular/src/app/shared/tour/tour-spotlight.component.ts
import {
  Component,
  computed,
  effect,
  inject,
  OnDestroy,
  OnInit,
  signal,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatDialogModule } from '@angular/material/dialog';
import { TranslocoModule } from '@jsverse/transloco';
import { PreferencesService } from '../../core/prefs/preferences.service';
import { TourService } from '../../core/tour/tour.service';

type TargetRect = {
  top: number;
  left: number;
  width: number;
  height: number;
};

@Component({
  selector: 'app-tour-spotlight',
  standalone: true,
  imports: [CommonModule, MatButtonModule, MatIconModule, MatDialogModule, TranslocoModule],
  template: `
    <!-- Welcome Prompt Dialog -->
    @if (tour.promptOpen()) {
      <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4">
        <div class="w-full max-w-md rounded-2xl border border-app-border bg-panel p-6 shadow-2xl">
          <div class="flex items-center gap-2">
            <mat-icon class="text-brand">explore</mat-icon>
            <h3 class="m-0 text-lg font-bold text-ink">
              {{ 'tour.welcomePromptTitle' | transloco }}
            </h3>
          </div>
          <p class="mt-2.5 text-sm leading-relaxed text-muted">
            {{ 'tour.welcomePromptDesc' | transloco }}
          </p>
          <div class="mt-6 flex justify-end gap-2">
            <button mat-button type="button" (click)="tour.dismissPrompt()">
              {{ 'tour.skipTour' | transloco }}
            </button>
            <button mat-flat-button color="primary" type="button" (click)="tour.startTour()">
              <mat-icon class="me-1">explore</mat-icon>
              {{ 'tour.startTour' | transloco }}
            </button>
          </div>
        </div>
      </div>
    }

    <!-- Spotlight Dimming Overlay & Card -->
    @if (tour.isOpen() && tour.currentStep(); as step) {
      <div class="fixed inset-0 z-50 overflow-hidden pointer-events-auto">
        <!-- Dimming Mask SVG -->
        <svg class="absolute inset-0 h-full w-full pointer-events-none">
          <defs>
            <mask id="angular-tour-spotlight-mask">
              <rect x="0" y="0" width="100%" height="100%" fill="white" />
              @if (rect(); as r) {
                <rect
                  [attr.x]="r.left - pad"
                  [attr.y]="r.top - pad"
                  [attr.width]="r.width + pad * 2"
                  [attr.height]="r.height + pad * 2"
                  rx="8"
                  fill="black"
                />
              }
            </mask>
          </defs>
          <rect
            x="0"
            y="0"
            width="100%"
            height="100%"
            fill="rgba(0, 0, 0, 0.72)"
            mask="url(#angular-tour-spotlight-mask)"
          />
        </svg>

        <!-- Highlight Border Ring -->
        @if (rect(); as r) {
          <div
            class="pointer-events-none absolute rounded-lg border-2 border-brand transition-all duration-300 shadow-[0_0_15px_rgba(59,130,246,0.5)]"
            [style.top.px]="r.top - pad"
            [style.left.px]="r.left - pad"
            [style.width.px]="r.width + pad * 2"
            [style.height.px]="r.height + pad * 2"
          ></div>
        }

        <!-- Floating Popover Card -->
        <div
          class="absolute z-50 w-[360px] max-w-[calc(100vw-40px)] rounded-xl border border-app-border bg-panel p-4 shadow-2xl transition-all duration-200"
          [style.top]="cardStyle().top"
          [style.left]="cardStyle().left"
        >
          <div class="flex items-center justify-between border-b border-app-border/60 pb-2">
            <span class="text-[0.75rem] font-semibold uppercase tracking-wider text-brand">
              {{
                'tour.stepCount'
                  | transloco: { current: tour.currentStepIndex() + 1, total: tour.totalSteps() }
              }}
            </span>
            <button
              mat-icon-button
              type="button"
              class="!h-7 !w-7"
              (click)="tour.endTour()"
              [attr.aria-label]="'tour.skipTour' | transloco"
            >
              <mat-icon class="!text-base">close</mat-icon>
            </button>
          </div>

          <div class="mt-3">
            <h4 class="m-0 text-sm font-semibold text-ink">
              {{ step.titleKey | transloco }}
            </h4>
            <p class="mt-1.5 text-xs leading-relaxed text-muted">
              {{ step.descriptionKey | transloco }}
            </p>
          </div>

          <div class="mt-4 flex items-center justify-between pt-2">
            <button
              mat-button
              type="button"
              class="!text-xs text-muted"
              (click)="tour.endTour()"
            >
              {{ 'tour.skipTour' | transloco }}
            </button>

            <div class="flex items-center gap-2">
              @if (tour.currentStepIndex() > 0) {
                <button
                  mat-stroked-button
                  type="button"
                  class="border-app-border !text-xs"
                  (click)="tour.prevStep()"
                >
                  <mat-icon class="!text-sm me-0.5">{{
                    isRtl() ? 'arrow_forward' : 'arrow_back'
                  }}</mat-icon>
                  {{ 'tour.back' | transloco }}
                </button>
              }

              <button
                mat-flat-button
                color="primary"
                type="button"
                class="!text-xs"
                (click)="tour.nextStep()"
              >
                <span>{{
                  (isLastStep() ? 'tour.finish' : 'tour.next') | transloco
                }}</span>
                @if (!isLastStep()) {
                  <mat-icon class="!text-sm ms-0.5">{{
                    isRtl() ? 'arrow_back' : 'arrow_forward'
                  }}</mat-icon>
                }
              </button>
            </div>
          </div>
        </div>
      </div>
    }
  `,
})
export class TourSpotlightComponent implements OnInit, OnDestroy {
  tour = inject(TourService);
  prefs = inject(PreferencesService);

  readonly pad = 6;
  readonly rect = signal<TargetRect | null>(null);
  readonly isRtl = computed(() => this.prefs.language() === 'ar');
  readonly isLastStep = computed(
    () => this.tour.currentStepIndex() === this.tour.totalSteps() - 1,
  );

  readonly cardStyle = computed(() => {
    const r = this.rect();
    if (!r) {
      return { top: '50%', left: '50%' };
    }

    const padSize = 12;
    const cardWidth = 360;
    const cardHeight = 220;

    const viewportW = window.innerWidth;
    const viewportH = window.innerHeight;

    let top = r.top + r.height + padSize;
    let left = r.left;

    if (top + cardHeight > viewportH - 20) {
      top = Math.max(20, r.top - cardHeight - padSize);
    }

    if (left + cardWidth > viewportW - 20) {
      left = Math.max(20, viewportW - cardWidth - 20);
    }
    if (left < 20) left = 20;

    return {
      top: `${Math.round(top)}px`,
      left: `${Math.round(left)}px`,
    };
  });

  private onResizeOrScroll = () => this.updateRect();

  constructor() {
    effect(() => {
      const open = this.tour.isOpen();
      const step = this.tour.currentStep();
      if (open && step) {
        this.updateRect();
      } else {
        this.rect.set(null);
      }
    });
  }

  ngOnInit(): void {
    window.addEventListener('resize', this.onResizeOrScroll);
    window.addEventListener('scroll', this.onResizeOrScroll, true);
  }

  ngOnDestroy(): void {
    window.removeEventListener('resize', this.onResizeOrScroll);
    window.removeEventListener('scroll', this.onResizeOrScroll, true);
  }

  private updateRect(): void {
    const step = this.tour.currentStep();
    if (!this.tour.isOpen() || !step) {
      this.rect.set(null);
      return;
    }

    const el = document.querySelector(step.targetSelector);
    if (!el) {
      setTimeout(() => {
        const retryStep = this.tour.currentStep();
        if (!retryStep) return;
        const retryEl = document.querySelector(retryStep.targetSelector);
        if (retryEl) {
          retryEl.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
          const b = retryEl.getBoundingClientRect();
          this.rect.set({ top: b.top, left: b.left, width: b.width, height: b.height });
        }
      }, 300);
      return;
    }

    el.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    const b = el.getBoundingClientRect();
    this.rect.set({ top: b.top, left: b.left, width: b.width, height: b.height });
  }
}
