// react/src/features/settings/SettingsPage.tsx
// Settings admin page — super-admin only.
// Three-section form: Access, Email, Demo. Loads current settings into local state;
// one "Save changes" button PUTs the whole UpdateSettingsRequest.
// Phase B: Predefined actions section at the bottom (tenant-wide, projectId == null).
import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { useQueryClient } from '@tanstack/react-query';
import {
  useGetApiAdminSettings,
  usePutApiAdminSettings,
  getGetApiAdminSettingsQueryKey,
  useGetApiAdminPredefinedActions,
  getGetApiAdminPredefinedActionsQueryKey,
  usePostApiAdminPredefinedActions,
  usePatchApiAdminPredefinedActionsId,
  useDeleteApiAdminPredefinedActionsId,
  type PredefinedActionResponse,
} from '@moamen-ui/pointer-react';
import { Plus, Trash2 } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useToast } from '@/components/ui/toast';
import { extractMessage } from '@/lib/error';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnySettings = any;


export function SettingsPage() {
  const { t } = useTranslation();
  const { toast } = useToast();
  const qc = useQueryClient();

  const { data, isLoading, isError } = useGetApiAdminSettings();

  // Unwrap data — the hook may return { data: SettingsResponse } or SettingsResponse directly
  const settings: AnySettings =
    (data as unknown as { data?: AnySettings })?.data ?? (data as AnySettings | undefined);

  // ---- Local form state ----
  const [scopedAdminSignupEnabled, setScopedAdminSignupEnabled] = useState(false);
  const [emailEnabled, setEmailEnabled] = useState(false);
  const [emailFromEmail, setEmailFromEmail] = useState('');
  const [emailFromName, setEmailFromName] = useState('');
  const [emailDailyCap, setEmailDailyCap] = useState(1);
  const [demoMaxActive, setDemoMaxActive] = useState(1);
  const [demoTtlHours, setDemoTtlHours] = useState(1);
  const [demoPerEmailPerDay, setDemoPerEmailPerDay] = useState(1);
  const [demoCommentCap, setDemoCommentCap] = useState(1);

  // Seed local state whenever settings loads / refreshes
  useEffect(() => {
    if (!settings) return;
    setScopedAdminSignupEnabled(settings.scopedAdminSignupEnabled ?? false);
    setEmailEnabled(settings.emailEnabled ?? false);
    setEmailFromEmail(settings.emailFromEmail ?? '');
    setEmailFromName(settings.emailFromName ?? '');
    setEmailDailyCap(settings.emailDailyCap ?? 1);
    setDemoMaxActive(settings.demoMaxActive ?? 1);
    setDemoTtlHours(settings.demoTtlHours ?? 1);
    setDemoPerEmailPerDay(settings.demoPerEmailPerDay ?? 1);
    setDemoCommentCap(settings.demoCommentCap ?? 1);
  }, [settings]);

  const reload = () =>
    void qc.invalidateQueries({ queryKey: getGetApiAdminSettingsQueryKey() });

  // ---- Predefined actions (tenant-wide, projectId == null) ----
  const [localEdits, setLocalEdits] = useState<
    Record<number, { text: string; prompt: string; dirty: boolean }>
  >({});
  const [newActionText, setNewActionText] = useState('');
  const [newActionPrompt, setNewActionPrompt] = useState('');

  const reloadPredefined = () =>
    void qc.invalidateQueries({ queryKey: getGetApiAdminPredefinedActionsQueryKey() });

  const { data: rawPredefined = [], isLoading: predefinedLoading } =
    useGetApiAdminPredefinedActions();
  const predefinedActions = rawPredefined.filter((a) => a.projectId == null);

  // Seed local edit state when server data arrives (only for items not already edited)
  useEffect(() => {
    setLocalEdits((prev) => {
      const next = { ...prev };
      for (const a of predefinedActions) {
        if (a.id != null && !(a.id in next)) {
          next[a.id] = { text: a.text ?? '', prompt: a.prompt ?? '', dirty: false };
        }
      }
      return next;
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [rawPredefined]);

  function updateLocalAction(id: number, field: 'text' | 'prompt', value: string) {
    setLocalEdits((prev) => ({
      ...prev,
      [id]: { ...prev[id], [field]: value, dirty: true },
    }));
  }

  const patchActionMut = usePatchApiAdminPredefinedActionsId({
    mutation: {
      onSuccess: (_data, vars) => {
        setLocalEdits((prev) => ({
          ...prev,
          [vars.id]: { ...prev[vars.id], dirty: false },
        }));
        reloadPredefined();
      },
      onError: (e: unknown) => toast(extractMessage(e), 'error'),
    },
  });

  function saveAction(action: PredefinedActionResponse) {
    const edit = localEdits[action.id!];
    if (!edit) return;
    patchActionMut.mutate({
      id: action.id!,
      data: {
        text: edit.text,
        prompt: edit.prompt,
        isActive: action.isActive,
      },
    });
  }

  const deleteActionMut = useDeleteApiAdminPredefinedActionsId({
    mutation: {
      onSuccess: (_data, vars) => {
        setLocalEdits((prev) => {
          const next = { ...prev };
          delete next[vars.id];
          return next;
        });
        reloadPredefined();
      },
      onError: (e: unknown) => toast(extractMessage(e), 'error'),
    },
  });

  const addActionMut = usePostApiAdminPredefinedActions({
    mutation: {
      onSuccess: () => {
        setNewActionText('');
        setNewActionPrompt('');
        reloadPredefined();
      },
      onError: (e: unknown) => toast(extractMessage(e), 'error'),
    },
  });

  function addAction() {
    if (!newActionText.trim()) return;
    addActionMut.mutate({
      data: {
        text: newActionText.trim(),
        prompt: newActionPrompt.trim(),
        isActive: true,
        sortOrder: predefinedActions.length,
      },
    });
  }

  const updateMut = usePutApiAdminSettings({
    mutation: {
      onSuccess: () => {
        toast(t('settings.saved'));
        reload();
      },
      onError: (e: unknown) => toast(extractMessage(e), 'error'),
    },
  });

  function save() {
    updateMut.mutate({
      data: {
        scopedAdminSignupEnabled,
        emailEnabled,
        emailFromEmail,
        emailFromName,
        emailDailyCap,
        demoMaxActive,
        demoTtlHours,
        demoPerEmailPerDay,
        demoCommentCap,
      },
    });
  }

  if (isLoading && !data) {
    return (
      <div className="flex h-40 items-center justify-center text-sm text-muted-foreground">
        {t('settings.loading')}
      </div>
    );
  }

  if (isError) {
    return (
      <div className="flex h-40 items-center justify-center text-sm text-destructive">
        {t('settings.loadError')}
      </div>
    );
  }

  const apiKeyConfigured: boolean = settings?.emailApiKeyConfigured ?? false;

  return (
    <div className="flex flex-col gap-6">
      <h2 className="text-lg font-semibold">{t('settings.title')}</h2>

      {/* ── Section 1: Access ── */}
      <Card>
        <CardContent className="flex flex-col gap-4 p-6">
          <h3 className="text-sm font-semibold">{t('settings.accessSection')}</h3>

          <div className="flex items-center justify-between gap-4">
            <div className="flex flex-col gap-1">
              <Label htmlFor="signup-enabled" className="text-sm font-medium">
                {t('settings.signupEnabled')}
              </Label>
              <p className="text-xs text-muted-foreground">{t('settings.signupEnabledHint')}</p>
            </div>
            <input
              id="signup-enabled"
              type="checkbox"
              checked={scopedAdminSignupEnabled}
              onChange={(e) => setScopedAdminSignupEnabled(e.target.checked)}
              className="h-4 w-4 cursor-pointer"
            />
          </div>
        </CardContent>
      </Card>

      {/* ── Section 2: Email ── */}
      <Card>
        <CardContent className="flex flex-col gap-4 p-6">
          <h3 className="text-sm font-semibold">{t('settings.emailSection')}</h3>

          {/* emailEnabled */}
          <div className="flex items-center justify-between gap-4">
            <div className="flex flex-col gap-1">
              <Label htmlFor="email-enabled" className="text-sm font-medium">
                {t('settings.emailEnabled')}
              </Label>
              <p className="text-xs text-muted-foreground">{t('settings.emailEnabledHint')}</p>
            </div>
            <input
              id="email-enabled"
              type="checkbox"
              checked={emailEnabled}
              onChange={(e) => setEmailEnabled(e.target.checked)}
              className="h-4 w-4 cursor-pointer"
            />
          </div>

          {/* emailFromEmail */}
          <div className="flex flex-col gap-1">
            <Label htmlFor="email-from" className="text-sm font-medium">
              {t('settings.emailFrom')}
            </Label>
            <p className="text-xs text-muted-foreground">{t('settings.emailFromHint')}</p>
            <Input
              id="email-from"
              type="email"
              value={emailFromEmail}
              onChange={(e) => setEmailFromEmail(e.target.value)}
            />
          </div>

          {/* emailFromName */}
          <div className="flex flex-col gap-1">
            <Label htmlFor="email-from-name" className="text-sm font-medium">
              {t('settings.emailFromName')}
            </Label>
            <p className="text-xs text-muted-foreground">{t('settings.emailFromNameHint')}</p>
            <Input
              id="email-from-name"
              value={emailFromName}
              onChange={(e) => setEmailFromName(e.target.value)}
            />
          </div>

          {/* emailDailyCap */}
          <div className="flex flex-col gap-1">
            <Label htmlFor="email-daily-cap" className="text-sm font-medium">
              {t('settings.emailDailyCap')}
            </Label>
            <p className="text-xs text-muted-foreground">{t('settings.emailDailyCapHint')}</p>
            <Input
              id="email-daily-cap"
              type="number"
              min={1}
              value={emailDailyCap}
              onChange={(e) => setEmailDailyCap(Number(e.target.value))}
              className="max-w-[12rem]"
            />
          </div>

          {/* API key — read-only status line */}
          <div className="flex flex-col gap-1">
            <p className="text-sm font-medium">{t('settings.emailApiKey')}</p>
            <p className="text-xs text-muted-foreground">{t('settings.emailApiKeyHint')}</p>
            <p className="text-sm font-medium">
              {apiKeyConfigured ? (
                <span className="text-green-600 dark:text-green-400">
                  ✓ {t('settings.emailApiKeyConfigured')}
                </span>
              ) : (
                <span className="text-destructive">
                  ✗ {t('settings.emailApiKeyMissing')}
                </span>
              )}
            </p>
          </div>
        </CardContent>
      </Card>

      {/* ── Section 3: Demo ── */}
      <Card>
        <CardContent className="flex flex-col gap-4 p-6">
          <h3 className="text-sm font-semibold">{t('settings.demoSection')}</h3>

          {/* demoMaxActive */}
          <div className="flex flex-col gap-1">
            <Label htmlFor="demo-max-active" className="text-sm font-medium">
              {t('settings.demoMaxActive')}
            </Label>
            <p className="text-xs text-muted-foreground">{t('settings.demoMaxActiveHint')}</p>
            <Input
              id="demo-max-active"
              type="number"
              min={1}
              value={demoMaxActive}
              onChange={(e) => setDemoMaxActive(Number(e.target.value))}
              className="max-w-[12rem]"
            />
          </div>

          {/* demoTtlHours */}
          <div className="flex flex-col gap-1">
            <Label htmlFor="demo-ttl-hours" className="text-sm font-medium">
              {t('settings.demoTtlHours')}
            </Label>
            <p className="text-xs text-muted-foreground">{t('settings.demoTtlHoursHint')}</p>
            <Input
              id="demo-ttl-hours"
              type="number"
              min={1}
              value={demoTtlHours}
              onChange={(e) => setDemoTtlHours(Number(e.target.value))}
              className="max-w-[12rem]"
            />
          </div>

          {/* demoPerEmailPerDay */}
          <div className="flex flex-col gap-1">
            <Label htmlFor="demo-per-email" className="text-sm font-medium">
              {t('settings.demoPerEmailPerDay')}
            </Label>
            <p className="text-xs text-muted-foreground">{t('settings.demoPerEmailPerDayHint')}</p>
            <Input
              id="demo-per-email"
              type="number"
              min={1}
              value={demoPerEmailPerDay}
              onChange={(e) => setDemoPerEmailPerDay(Number(e.target.value))}
              className="max-w-[12rem]"
            />
          </div>

          {/* demoCommentCap */}
          <div className="flex flex-col gap-1">
            <Label htmlFor="demo-comment-cap" className="text-sm font-medium">
              {t('settings.demoCommentCap')}
            </Label>
            <p className="text-xs text-muted-foreground">{t('settings.demoCommentCapHint')}</p>
            <Input
              id="demo-comment-cap"
              type="number"
              min={1}
              value={demoCommentCap}
              onChange={(e) => setDemoCommentCap(Number(e.target.value))}
              className="max-w-[12rem]"
            />
          </div>
        </CardContent>
      </Card>

      {/* ── Save button ── */}
      <div className="flex justify-end">
        <Button disabled={updateMut.isPending} onClick={save}>
          {t('settings.save')}
        </Button>
      </div>

      {/* ── Section 4: Predefined actions (tenant-wide) ── */}
      <Card>
        <CardContent className="flex flex-col gap-4 p-6">
          <h3 className="text-sm font-semibold">{t('predefined.section')}</h3>
          <p className="text-xs text-muted-foreground">{t('predefined.tenantHelp')}</p>

          {predefinedLoading && (
            <p className="text-sm text-muted-foreground">{t('settings.loading')}</p>
          )}

          {!predefinedLoading && predefinedActions.length === 0 && (
            <p className="text-sm text-muted-foreground">{t('predefined.empty')}</p>
          )}

          {predefinedActions.map((action) => {
            const edit = localEdits[action.id!] ?? {
              text: action.text ?? '',
              prompt: action.prompt ?? '',
              dirty: false,
            };
            const isSaving =
              patchActionMut.isPending &&
              (patchActionMut.variables as { id?: number } | undefined)?.id === action.id;
            return (
              <div
                key={action.id}
                className="flex flex-col gap-2 rounded-md border border-border p-3"
              >
                <div className="flex items-start gap-2">
                  <div className="flex flex-1 flex-col gap-1">
                    <Label className="text-xs">{t('predefined.text')}</Label>
                    <Input
                      value={edit.text}
                      onChange={(e) => updateLocalAction(action.id!, 'text', e.target.value)}
                    />
                  </div>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="mt-5 h-7 w-7 shrink-0 text-destructive"
                    onClick={() => deleteActionMut.mutate({ id: action.id! })}
                    disabled={deleteActionMut.isPending}
                    type="button"
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
                <div className="flex flex-col gap-1">
                  <Label className="text-xs">{t('predefined.prompt')}</Label>
                  <textarea
                    value={edit.prompt}
                    onChange={(e) => updateLocalAction(action.id!, 'prompt', e.target.value)}
                    rows={2}
                    className="w-full resize-none rounded-md border border-input bg-background px-3 py-1.5 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                  />
                </div>
                {edit.dirty && (
                  <div className="flex justify-end">
                    <Button
                      size="sm"
                      disabled={isSaving}
                      onClick={() => saveAction(action)}
                    >
                      {t('common.save')}
                    </Button>
                  </div>
                )}
              </div>
            );
          })}

          {/* Add new action */}
          <div className="flex flex-col gap-2 rounded-md border border-dashed border-border p-3">
            <div className="flex flex-col gap-1">
              <Label className="text-xs">{t('predefined.text')}</Label>
              <Input
                value={newActionText}
                onChange={(e) => setNewActionText(e.target.value)}
                placeholder={t('predefined.text')}
              />
            </div>
            <div className="flex flex-col gap-1">
              <Label className="text-xs">{t('predefined.prompt')}</Label>
              <textarea
                value={newActionPrompt}
                onChange={(e) => setNewActionPrompt(e.target.value)}
                rows={2}
                placeholder={t('predefined.prompt')}
                className="w-full resize-none rounded-md border border-input bg-background px-3 py-1.5 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
              />
            </div>
            <div className="flex justify-end">
              <Button
                size="sm"
                variant="outline"
                disabled={!newActionText.trim() || addActionMut.isPending}
                onClick={addAction}
                type="button"
              >
                <Plus className="h-4 w-4" />
                {t('predefined.add')}
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

// vue/src/features/settings/SettingsPage.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { useQueryClient } from '@tanstack/vue-query';
import {
  useGetApiAdminSettings,
  usePutApiAdminSettings,
  getGetApiAdminSettingsQueryKey,
  useGetApiAdminPredefinedActions,
  usePostApiAdminPredefinedActions,
  usePatchApiAdminPredefinedActionsId,
  useDeleteApiAdminPredefinedActionsId,
  getGetApiAdminPredefinedActionsQueryKey,
  type SettingsResponse,
  type PredefinedActionResponse,
} from '@moamen-ui/pointer-vue';
import { Card, CardContent } from '@/components/ui/card';
import { Switch } from '@/components/ui/switch';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { PlusCircle, Trash2 } from 'lucide-vue-next';
import { extractMessage } from '@/lib/error';
import { toast } from '@/composables/useToast';

const { t } = useI18n();
const queryClient = useQueryClient();

const { data, isError } = useGetApiAdminSettings();
// The interceptor unwraps the envelope at runtime; data.value IS SettingsResponse.
// Bridge the TS type mismatch with a cast (mirrors the React dashboard pattern).
const settings = computed(() => data.value as unknown as SettingsResponse | undefined);

const updateSettings = usePutApiAdminSettings();

// Local reactive form state seeded from server data.
const signupEnabled = ref(false);
const emailEnabled = ref(false);
const emailFromEmail = ref('');
const emailFromName = ref('');
const emailDailyCap = ref<number>(300);
const demoMaxActive = ref<number>(10);
const demoTtlHours = ref<number>(48);
const demoPerEmailPerDay = ref<number>(3);
const demoCommentCap = ref<number>(20);

watch(
  settings,
  (s) => {
    if (!s) return;
    signupEnabled.value = (s as any).scopedAdminSignupEnabled ?? false;
    emailEnabled.value = (s as any).emailEnabled ?? false;
    emailFromEmail.value = (s as any).emailFromEmail ?? '';
    emailFromName.value = (s as any).emailFromName ?? '';
    emailDailyCap.value = (s as any).emailDailyCap ?? 300;
    demoMaxActive.value = (s as any).demoMaxActive ?? 10;
    demoTtlHours.value = (s as any).demoTtlHours ?? 48;
    demoPerEmailPerDay.value = (s as any).demoPerEmailPerDay ?? 3;
    demoCommentCap.value = (s as any).demoCommentCap ?? 20;
  },
  { immediate: true },
);

async function saveSettings() {
  try {
    await updateSettings.mutateAsync({
      data: {
        scopedAdminSignupEnabled: signupEnabled.value,
        emailEnabled: emailEnabled.value,
        emailFromEmail: emailFromEmail.value,
        emailFromName: emailFromName.value,
        emailDailyCap: emailDailyCap.value,
        demoMaxActive: demoMaxActive.value,
        demoTtlHours: demoTtlHours.value,
        demoPerEmailPerDay: demoPerEmailPerDay.value,
        demoCommentCap: demoCommentCap.value,
      } as any,
    });
    toast(t('settings.saved'));
    void queryClient.invalidateQueries({ queryKey: getGetApiAdminSettingsQueryKey() });
  } catch (e) {
    toast(extractMessage(e));
  }
}

// ── Predefined actions (tenant-wide) ──────────────────────────────────
const predefinedActionsQuery = useGetApiAdminPredefinedActions();
const tenantActions = computed<PredefinedActionResponse[]>(
  () => (predefinedActionsQuery.data.value ?? []).filter((a: PredefinedActionResponse) => a.projectId == null),
);

interface EditableAction {
  id?: number;
  text: string;
  prompt: string;
  isNew?: boolean;
}
const editableActions = ref<EditableAction[]>([]);

watch(
  tenantActions,
  (actions) => {
    editableActions.value = actions.map((a) => ({
      id: a.id,
      text: a.text ?? '',
      prompt: a.prompt ?? '',
    }));
  },
  { immediate: true },
);

const createPredefined = usePostApiAdminPredefinedActions();
const updatePredefined = usePatchApiAdminPredefinedActionsId();
const deletePredefined = useDeleteApiAdminPredefinedActionsId();

function reloadPredefined() {
  void queryClient.invalidateQueries({ queryKey: getGetApiAdminPredefinedActionsQueryKey() });
}

function addTenantAction() {
  editableActions.value.push({ text: '', prompt: '', isNew: true });
}

async function saveTenantAction(action: EditableAction, index: number) {
  try {
    if (action.isNew || action.id == null) {
      await createPredefined.mutateAsync({
        data: {
          text: action.text,
          prompt: action.prompt,
          isActive: true,
          sortOrder: index,
        },
      });
    } else {
      await updatePredefined.mutateAsync({
        id: action.id,
        data: {
          text: action.text,
          prompt: action.prompt,
        },
      });
    }
    reloadPredefined();
  } catch (e) {
    toast(extractMessage(e));
  }
}

async function deleteTenantAction(action: EditableAction, index: number) {
  if (action.isNew || action.id == null) {
    editableActions.value.splice(index, 1);
    return;
  }
  try {
    await deletePredefined.mutateAsync({ id: action.id });
    reloadPredefined();
  } catch (e) {
    toast(extractMessage(e));
  }
}
</script>

<template>
  <div class="flex flex-col gap-4">
    <h2 class="text-lg font-semibold">{{ t('settings.title') }}</h2>

    <p v-if="isError" class="text-sm text-destructive">{{ t('settings.loadError') }}</p>

    <template v-if="settings || !isError">
      <!-- Section: Access -->
      <Card>
        <CardContent class="flex flex-col gap-6 p-6">
          <h3 class="text-sm font-semibold">{{ t('settings.accessSection') }}</h3>
          <!-- Signup toggle -->
          <div class="flex items-center justify-between gap-4">
            <div class="flex flex-col gap-1">
              <Label class="text-sm font-medium">{{ t('settings.signupEnabled') }}</Label>
              <p class="text-xs text-muted-foreground">{{ t('settings.signupEnabledDesc') }}</p>
            </div>
            <Switch
              :model-value="signupEnabled"
              :disabled="updateSettings.isPending.value"
              @update:model-value="(v: boolean) => { signupEnabled = v; }"
            />
          </div>
        </CardContent>
      </Card>

      <!-- Section: Email -->
      <Card>
        <CardContent class="flex flex-col gap-6 p-6">
          <h3 class="text-sm font-semibold">{{ t('settings.emailSection') }}</h3>

          <!-- emailEnabled -->
          <div class="flex items-center justify-between gap-4">
            <div class="flex flex-col gap-1">
              <Label class="text-sm font-medium">{{ t('settings.emailEnabled') }}</Label>
              <p class="text-xs text-muted-foreground">{{ t('settings.emailEnabledHint') }}</p>
            </div>
            <Switch
              :model-value="emailEnabled"
              :disabled="updateSettings.isPending.value"
              @update:model-value="(v: boolean) => { emailEnabled = v; }"
            />
          </div>

          <!-- emailFromEmail -->
          <div class="flex flex-col gap-2">
            <Label for="email-from" class="text-sm font-medium">{{ t('settings.emailFrom') }}</Label>
            <p class="text-xs text-muted-foreground">{{ t('settings.emailFromHint') }}</p>
            <Input id="email-from" v-model="emailFromEmail" type="email" />
          </div>

          <!-- emailFromName -->
          <div class="flex flex-col gap-2">
            <Label for="email-from-name" class="text-sm font-medium">{{ t('settings.emailFromName') }}</Label>
            <p class="text-xs text-muted-foreground">{{ t('settings.emailFromNameHint') }}</p>
            <Input id="email-from-name" v-model="emailFromName" />
          </div>

          <!-- emailDailyCap -->
          <div class="flex flex-col gap-2">
            <Label for="email-daily-cap" class="text-sm font-medium">{{ t('settings.emailDailyCap') }}</Label>
            <p class="text-xs text-muted-foreground">{{ t('settings.emailDailyCapHint') }}</p>
            <Input id="email-daily-cap" v-model.number="emailDailyCap" type="number" :min="1" />
          </div>

          <!-- API key status (read-only) -->
          <div class="flex flex-col gap-1">
            <Label class="text-sm font-medium">{{ t('settings.emailApiKey') }}</Label>
            <p class="text-xs text-muted-foreground">{{ t('settings.emailApiKeyHint') }}</p>
            <p class="text-sm mt-1">
              <span v-if="(settings as any)?.emailApiKeyConfigured" class="text-green-600 font-medium">
                ✓ {{ t('settings.emailApiKeyConfigured') }}
              </span>
              <span v-else class="text-destructive font-medium">
                ✗ {{ t('settings.emailApiKeyMissing') }}
              </span>
            </p>
          </div>
        </CardContent>
      </Card>

      <!-- Section: Demo -->
      <Card>
        <CardContent class="flex flex-col gap-6 p-6">
          <h3 class="text-sm font-semibold">{{ t('settings.demoSection') }}</h3>

          <!-- demoMaxActive -->
          <div class="flex flex-col gap-2">
            <Label for="demo-max-active" class="text-sm font-medium">{{ t('settings.demoMaxActive') }}</Label>
            <p class="text-xs text-muted-foreground">{{ t('settings.demoMaxActiveHint') }}</p>
            <Input id="demo-max-active" v-model.number="demoMaxActive" type="number" :min="1" />
          </div>

          <!-- demoTtlHours -->
          <div class="flex flex-col gap-2">
            <Label for="demo-ttl-hours" class="text-sm font-medium">{{ t('settings.demoTtlHours') }}</Label>
            <p class="text-xs text-muted-foreground">{{ t('settings.demoTtlHoursHint') }}</p>
            <Input id="demo-ttl-hours" v-model.number="demoTtlHours" type="number" :min="1" />
          </div>

          <!-- demoPerEmailPerDay -->
          <div class="flex flex-col gap-2">
            <Label for="demo-per-email" class="text-sm font-medium">{{ t('settings.demoPerEmailPerDay') }}</Label>
            <p class="text-xs text-muted-foreground">{{ t('settings.demoPerEmailPerDayHint') }}</p>
            <Input id="demo-per-email" v-model.number="demoPerEmailPerDay" type="number" :min="1" />
          </div>

          <!-- demoCommentCap -->
          <div class="flex flex-col gap-2">
            <Label for="demo-comment-cap" class="text-sm font-medium">{{ t('settings.demoCommentCap') }}</Label>
            <p class="text-xs text-muted-foreground">{{ t('settings.demoCommentCapHint') }}</p>
            <Input id="demo-comment-cap" v-model.number="demoCommentCap" type="number" :min="1" />
          </div>
        </CardContent>
      </Card>

      <!-- Section: Predefined actions -->
      <Card>
        <CardContent class="flex flex-col gap-4 p-6">
          <div class="flex items-center justify-between">
            <h3 class="text-sm font-semibold">{{ t('predefined.section') }}</h3>
            <Button type="button" variant="outline" size="sm" @click="addTenantAction">
              <PlusCircle class="h-4 w-4" /> {{ t('predefined.add') }}
            </Button>
          </div>
          <p class="text-xs text-muted-foreground">{{ t('predefined.tenantHelp') }}</p>
          <p v-if="editableActions.length === 0" class="text-sm text-muted-foreground italic">
            {{ t('predefined.empty') }}
          </p>
          <div
            v-for="(action, idx) in editableActions"
            :key="idx"
            class="flex flex-col gap-2 rounded-md border p-3"
          >
            <div class="flex flex-col gap-1">
              <Label :for="'pa-text-' + idx">{{ t('predefined.text') }}</Label>
              <Input :id="'pa-text-' + idx" v-model="action.text" />
            </div>
            <div class="flex flex-col gap-1">
              <Label :for="'pa-prompt-' + idx">{{ t('predefined.prompt') }}</Label>
              <textarea
                :id="'pa-prompt-' + idx"
                v-model="action.prompt"
                rows="2"
                class="flex w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm resize-none"
              />
            </div>
            <div class="flex justify-end gap-2">
              <Button
                type="button"
                variant="ghost"
                size="sm"
                @click="deleteTenantAction(action, idx)"
              >
                <Trash2 class="h-4 w-4 text-destructive" />
                {{ t('common.delete') }}
              </Button>
              <Button
                type="button"
                size="sm"
                @click="saveTenantAction(action, idx)"
              >
                {{ t('common.save') }}
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      <!-- Save button -->
      <div class="flex justify-end">
        <Button :disabled="updateSettings.isPending.value" @click="saveSettings">
          {{ t('settings.save') }}
        </Button>
      </div>
    </template>
  </div>
</template>
