// react/src/components/InstallGuide.tsx
// InstallGuide — the Pointer installation steps in one shared dialog (React
// port of the Angular InstallGuideComponent). Opened from the header rocket
// icon (any signed-in user, any time) and automatically for a workspace admin
// who is new here or has no feedback yet — see lib/install-guide.ts for that
// policy. The demo banner's "View installation steps" button opens it too, so
// the steps have one source of truth.
import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from 'react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Rocket, Copy, Download } from 'lucide-react';
import { useGetApiAdminProjects, type ProjectResponse } from '@moamen-ui/pointer-react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { TabsContent } from '@/components/ui/tabs';
import { AppTabs } from '@/components/shared/Tabs';
import { useToast } from '@/components/ui/toast';
import { useAuth } from '@/lib/auth';
import {
  EXTENSION_ZIP_URL,
  isSuppressed,
  markShown,
  readDemoSession,
  shouldAutoOpen,
  suppress,
  unsuppress,
  type DemoSession,
} from '@/lib/install-guide';

/** One step in the guide. `code` is optional — instruction-only steps omit it. */
export interface SetupStep {
  titleKey: string;
  hintKey: string;
  code?: string;
  /** Renders the step's action as a download anchor instead of a code block. */
  download?: boolean;
}

/** Rendered in the snippet until the user actually has a project to point at. */
export const PROJECT_KEY_PLACEHOLDER = '<your-project-key>';
/** Placeholder inside the credentials snippet. Deliberately not translated — it
 *  is pasted into .pointer/credentials.env, where English reads correctly either way. */
export const PASSWORD_PLACEHOLDER = '<your password>';

/** What the dialog renders: the agent-driven path, plus the hand-wiring fallback. */
export interface GuideSteps {
  /** The recommended path, in order. */
  primary: SetupStep[];
  /** Hand-wiring the widget — only needed if you skip the agent prompt. */
  manual: SetupStep[];
}

/**
 * Builds the install steps. Pure so the branching (demo credentials vs. the
 * signed-in user's own, and the placeholder when there is no project yet) is
 * unit-testable.
 *
 * Shape of the flow: install.sh drops in two skills — pointer-init and
 * pointer-feedback — so wiring the widget is a prompt, not two snippets pasted
 * into index.html. pointer-init detects the host stack (Vite / Angular / Next /
 * CRA / static / Swagger) and wires the loader and env vars the way that stack
 * expects, which the raw snippets cannot do. They stay available as the manual
 * fallback.
 */
export function buildSteps(input: {
  server: string;
  projectKey: string | null;
  userEmail: string | null;
  demo: DemoSession | null;
  credsEmailedText: string;
}): GuideSteps {
  const { server, demo } = input;
  const projectKey = input.projectKey || PROJECT_KEY_PLACEHOLDER;
  const credentials = demo
    ? demo.emailSent
      ? input.credsEmailedText
      : `POINTER_EMAIL=${demo.email ?? ''}\nPOINTER_PASSWORD=${demo.password ?? ''}`
    : `POINTER_EMAIL=${input.userEmail ?? ''}\nPOINTER_PASSWORD=${PASSWORD_PLACEHOLDER}`;

  return {
    primary: [
      // Installs pointer-init + pointer-feedback and scaffolds .pointer/credentials.env.
      { titleKey: 'demo.step3Title', hintKey: 'demo.step3Hint', code: `curl -fsSL ${server}/install.sh | sh` },
      { titleKey: 'demo.step4Title', hintKey: 'demo.step4Hint', code: credentials },
      // Names the skill and supplies its three variables, so the agent wires the
      // widget straight away instead of stopping to ask for them.
      {
        titleKey: 'install.stepAgentTitle',
        hintKey: 'install.stepAgentHint',
        code: `Add the Pointer feedback widget to this app using the pointer-init skill — project key: ${projectKey}, Pointer server URL: ${server}, environment: local`,
      },
      { titleKey: 'demo.step5Title', hintKey: 'demo.step5Hint' },
      // Kept English on purpose — the pointer-feedback skill triggers on this phrasing.
      { titleKey: 'demo.step6Title', hintKey: 'demo.step6Hint', code: 'What are the new Pointer comments?' },
    ],
    manual: [
      { titleKey: 'demo.step1Title', hintKey: 'demo.step1Hint', code: `<script src="${server}/pointer.js" defer></script>` },
      { titleKey: 'demo.step2Title', hintKey: 'demo.step2Hint', code: `<pointer-feedback project="${projectKey}" server="${server}"></pointer-feedback>` },
    ],
  };
}

/**
 * Steps for the Chrome-extension install tab. Mirrors buildSteps' credentials
 * branch: the demo session's email/password when one is active (the emailed
 * notice once the creds have been sent), otherwise the signed-in user's email
 * with a password placeholder.
 */
export function buildExtensionSteps(input: {
  server: string;
  userEmail: string | null;
  demo: DemoSession | null;
  credsEmailedText: string;
}): SetupStep[] {
  const { server, demo } = input;
  const credentials = demo
    ? demo.emailSent
      ? input.credsEmailedText
      : `${demo.email ?? ''}\n${demo.password ?? ''}`
    : `${input.userEmail ?? ''}\n${PASSWORD_PLACEHOLDER}`;

  return [
    {
      titleKey: 'install.extDownloadTitle',
      hintKey: 'install.extDownloadHint',
      download: true,
    },
    { titleKey: 'install.extUnzipTitle', hintKey: 'install.extUnzipHint' },
    { titleKey: 'install.extLoadTitle', hintKey: 'install.extLoadHint', code: 'chrome://extensions' },
    {
      titleKey: 'install.extSignInTitle',
      hintKey: 'install.extSignInHint',
      code: `${server}\n${credentials}`,
    },
  ];
}

interface InstallGuideValue {
  open: () => void;
  /** The user's own projects (only ones with a key are pickable). */
  projects: ProjectResponse[];
  /** True once the project list has loaded and no comment exists anywhere. */
  nothingCollectedYet: boolean;
}

const InstallGuideContext = createContext<InstallGuideValue | null>(null);

export function useInstallGuide(): InstallGuideValue {
  const ctx = useContext(InstallGuideContext);
  if (!ctx) throw new Error('useInstallGuide must be used within InstallGuideProvider');
  return ctx;
}

/**
 * Owns the install guide: how it opens, and whether it opens by itself. The
 * project list lives here (rather than in the dialog) so the header (which
 * shows a hint dot while nothing has been collected yet), the dialog's project
 * picker and the auto-open gate share a single fetch.
 */
export function InstallGuideProvider({ children }: { children: ReactNode }) {
  const { user, isAdmin } = useAuth();
  const userId = user?.id ?? null;
  const [open, setOpen] = useState(false);

  // GET /api/admin/projects is plain [Authorize], so every signed-in user —
  // stakeholders included — gets their own list.
  const projectsQuery = useGetApiAdminProjects();
  const projects = useMemo(
    () => (projectsQuery.data ?? []).filter((p) => p.key),
    [projectsQuery.data],
  );

  /** Total comments across visible projects; 0 means nothing has been collected yet. */
  const commentsCount = useMemo(
    () => (projectsQuery.data ?? []).reduce((sum, p) => sum + (p.commentsCount ?? 0), 0),
    [projectsQuery.data],
  );

  const nothingCollectedYet = !projectsQuery.isLoading && commentsCount === 0;

  const openGuide = useCallback(() => {
    // Opening it counts as seen, however it was opened.
    markShown(userId);
    setOpen(true);
  }, [userId]);

  // A workspace admin who is new here — or whose workspace has collected
  // nothing yet — gets the guide opened for them, once. The effect waits for
  // the project list so commentsCount is real rather than a loading 0.
  useEffect(() => {
    if (projectsQuery.isLoading) return;
    if (!userId) return;
    if (shouldAutoOpen({ isAdmin, userId, commentsCount })) openGuide();
  }, [projectsQuery.isLoading, userId, isAdmin, commentsCount, openGuide]);

  const value = useMemo<InstallGuideValue>(
    () => ({ open: openGuide, projects, nothingCollectedYet }),
    [openGuide, projects, nothingCollectedYet],
  );

  return (
    <InstallGuideContext.Provider value={value}>
      {children}
      {open && <InstallGuideDialog projects={projects} onClose={() => setOpen(false)} />}
    </InstallGuideContext.Provider>
  );
}

/** One ordered list of steps — shared by the code tab and the extension tab. */
function StepList({ steps, copy }: { steps: SetupStep[]; copy: (text: string) => void }) {
  const { t } = useTranslation();
  return (
    <ol className="m-0 flex list-none flex-col gap-3 p-0">
      {steps.map((st, i) => (
        <li key={st.titleKey} className="rounded-lg border border-border bg-app/40 p-3">
          <div className="text-[0.85rem] font-semibold">
            {i + 1}. {t(st.titleKey)}
          </div>
          <div className="mt-0.5 text-[0.78rem] text-muted-foreground">{t(st.hintKey)}</div>
          {st.download ? (
            <Button asChild size="sm" className="mt-2">
              <a href={EXTENSION_ZIP_URL} download>
                <Download className="h-3.5 w-3.5" />
                {t('install.extDownloadButton')}
              </a>
            </Button>
          ) : (
            st.code && (
              <div className="mt-2 flex items-start gap-2">
                <pre className="m-0 flex-1 overflow-x-auto whitespace-pre-wrap rounded bg-app px-2 py-1.5 text-[0.78rem]">
                  <code>{st.code}</code>
                </pre>
                <Button
                  variant="outline"
                  size="sm"
                  className="shrink-0"
                  onClick={() => copy(st.code!)}
                >
                  <Copy className="h-3.5 w-3.5" />
                  {t('demo.copy')}
                </Button>
              </div>
            )
          )}
        </li>
      ))}
    </ol>
  );
}

function InstallGuideDialog({
  projects,
  onClose,
}: {
  projects: ProjectResponse[];
  onClose: () => void;
}) {
  const { t } = useTranslation();
  const { toast } = useToast();
  const { user } = useAuth();
  const userId = user?.id ?? null;

  const demo = useMemo(() => readDemoSession(), []);
  /** Selected project key; defaults to the demo project, else the first one. */
  const [projectKey, setProjectKey] = useState<string | null>(demo?.projectKey ?? null);
  const [suppressed, setSuppressed] = useState(() => isSuppressed(userId));
  /** Which install method the dialog shows. Deliberately not persisted — every open starts on Code. */
  const [tab, setTab] = useState('code');

  const server = demo?.serverUrl || import.meta.env.VITE_API_BASE;
  const effectiveKey =
    projectKey && projects.some((p) => p.key === projectKey)
      ? projectKey
      : projects[0]?.key ?? null;

  // Recomputed every render, so a language switch re-resolves the emailed-creds
  // notice alongside the translated titles/hints.
  const steps = buildSteps({
    server,
    projectKey: effectiveKey,
    userEmail: user?.email ?? null,
    demo,
    credsEmailedText: t('demo.credsEmailed'),
  });

  const extensionSteps = buildExtensionSteps({
    server,
    userEmail: user?.email ?? null,
    demo,
    credsEmailedText: t('demo.credsEmailed'),
  });

  function onSuppressedChange(checked: boolean) {
    setSuppressed(checked);
    if (checked) suppress(userId);
    else unsuppress(userId);
  }

  async function copy(text: string) {
    try {
      await navigator.clipboard.writeText(text);
      toast(t('demo.copied'));
    } catch {
      toast(t('demo.copyFailed'), 'error');
    }
  }

  return (
    <Dialog
      open
      onOpenChange={(o) => {
        if (!o) onClose();
      }}
    >
      <DialogContent className="max-h-[85vh] max-w-2xl overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Rocket className="h-5 w-5 text-brand" />
            {t('install.title')}
          </DialogTitle>
        </DialogHeader>

        <p className="m-0 text-[0.85rem] text-muted-foreground">{t('install.intro')}</p>

        {/* Two install paths: the code-based guide and the Chrome extension.
             Tab choice is deliberately not persisted — every open starts on Code. */}
        <AppTabs
          tabs={[
            { value: 'code', label: t('install.tabCode') },
            { value: 'extension', label: t('install.tabExtension') },
          ]}
          value={tab}
          onValueChange={setTab}
          className="mt-3"
        >
          <TabsContent value="code">
        {/* Which project the snippet points at */}
        {projects.length > 0 ? (
          <div className="flex flex-col gap-1.5">
            <span className="text-sm font-medium">{t('install.project')}</span>
            <Select value={effectiveKey ?? undefined} onValueChange={setProjectKey}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {projects.map((p) => (
                  <SelectItem key={p.id ?? p.key!} value={p.key!}>
                    {p.name} ({p.key})
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        ) : !demo ? (
          <p className="m-0 rounded-lg border border-border bg-app/40 p-3 text-[0.85rem]">
            {t('install.noProjects')}{' '}
            <DialogClose asChild>
              <Link to="/projects" className="text-brand underline">
                {t('nav.projects')}
              </Link>
            </DialogClose>
          </p>
        ) : null}

        {/* The recommended path: install the skills, then let the agent wire the widget */}
        <StepList steps={steps.primary} copy={copy} />

        {/* Hand-wiring, for anyone not using an agent. Collapsed: the prompt above
             does this per-stack, so these snippets are the fallback, not the path. */}
        <details className="mt-4 rounded-lg border border-border p-3">
          <summary className="cursor-pointer text-[0.85rem] font-semibold">
            {t('install.manualTitle')}
          </summary>
          <p className="mb-2 mt-1 text-[0.78rem] text-muted-foreground">{t('install.manualHint')}</p>
          <div className="flex flex-col gap-3">
            {steps.manual.map((st) => (
              <div key={st.titleKey}>
                <div className="text-[0.8rem] font-medium">{t(st.titleKey)}</div>
                <div className="mt-0.5 text-[0.75rem] text-muted-foreground">{t(st.hintKey)}</div>
                {st.code && (
                  <div className="mt-1.5 flex items-start gap-2">
                    <pre className="m-0 flex-1 overflow-x-auto whitespace-pre-wrap rounded bg-app px-2 py-1.5 text-[0.78rem]">
                      <code>{st.code}</code>
                    </pre>
                    <Button
                      variant="outline"
                      size="sm"
                      className="shrink-0"
                      onClick={() => copy(st.code!)}
                    >
                      <Copy className="h-3.5 w-3.5" />
                      {t('demo.copy')}
                    </Button>
                  </div>
                )}
              </div>
            ))}
          </div>
        </details>
          </TabsContent>

          <TabsContent value="extension">
            <StepList steps={extensionSteps} copy={copy} />
          </TabsContent>
        </AppTabs>

        <div className="flex flex-wrap items-center justify-between gap-3">
          <label className="flex cursor-pointer items-center gap-2">
            <input
              type="checkbox"
              className="h-4 w-4 accent-brand"
              checked={suppressed}
              onChange={(e) => onSuppressedChange(e.target.checked)}
            />
            <span className="text-[0.8rem]">{t('install.dontShowAgain')}</span>
          </label>
          <Button onClick={onClose}>{t('install.done')}</Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

// angular/src/app/shared/install-guide/install-guide.component.ts
import { Component, computed, inject, signal } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { MatButtonModule } from '@angular/material/button';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatDialogModule } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatButtonToggleModule } from '@angular/material/button-toggle';
import { MatIconModule } from '@angular/material/icon';
import { MatSelectModule } from '@angular/material/select';
import { MatSnackBar } from '@angular/material/snack-bar';
import { RouterLink } from '@angular/router';
import { TranslocoModule, TranslocoService } from '@jsverse/transloco';
import { environment } from '../../../environments/environment';
import { AuthService } from '../../core/auth/auth.service';
import { InstallGuideService } from './install-guide.service';

/** One step in the guide. `code`/`downloadUrl` are optional — instruction-only steps omit both. */
export interface SetupStep {
  titleKey: string;
  hintKey: string;
  code?: string;
  /** Renders the step as a download anchor instead of a code block. */
  downloadUrl?: string;
}

/** Demo session written by the demo provisioning flow (sessionStorage). */
interface DemoSession {
  email?: string | null;
  password?: string | null;
  projectKey?: string | null;
  serverUrl?: string | null;
  emailSent?: boolean;
}

const DEMO_SESSION_KEY = 'pointer_demo';
/** The extension zip is a landing-domain artifact served by Caddy — deliberately
 *  not derived from the API base, which points at a different origin. */
export const EXTENSION_ZIP_URL = 'https://pointer.moamen.work/pointer-extension.zip';
/** Rendered in the snippet until the user actually has a project to point at. */
export const PROJECT_KEY_PLACEHOLDER = '<your-project-key>';
/** Placeholder inside the credentials snippet. Deliberately not translated — it is
 *  pasted into .pointer/credentials.env, where English reads correctly either way. */
export const PASSWORD_PLACEHOLDER = '<your password>';

/** What the dialog renders: the agent-driven path, plus the hand-wiring fallback. */
export interface GuideSteps {
  /** The recommended path, in order. */
  primary: SetupStep[];
  /** Hand-wiring the widget — only needed if you skip the agent prompt. */
  manual: SetupStep[];
}

/**
 * Builds the install steps. Pure so the branching (demo credentials vs. the signed-in
 * user's own, and the placeholder when there is no project yet) is unit-testable.
 *
 * Shape of the flow: install.sh drops in two skills — pointer-init and
 * pointer-feedback — so wiring the widget is a prompt, not two snippets pasted into
 * index.html. pointer-init detects the host stack (Vite / Angular / Next / CRA /
 * static / Swagger) and wires the loader and env vars the way that stack expects,
 * which the raw snippets cannot do. They stay available as the manual fallback.
 */
export function buildSteps(input: {
  server: string;
  projectKey: string | null;
  userEmail: string | null;
  demo: DemoSession | null;
  credsEmailedText: string;
}): GuideSteps {
  const { server, demo } = input;
  const projectKey = input.projectKey || PROJECT_KEY_PLACEHOLDER;
  const credentials = credentialsSnippet(input);

  return {
    primary: [
      // Installs pointer-init + pointer-feedback and scaffolds .pointer/credentials.env.
      { titleKey: 'demo.step3Title', hintKey: 'demo.step3Hint', code: `curl -fsSL ${server}/install.sh | sh` },
      { titleKey: 'demo.step4Title', hintKey: 'demo.step4Hint', code: credentials },
      // Names the skill and supplies its three variables, so the agent wires the
      // widget straight away instead of stopping to ask for them.
      {
        titleKey: 'install.stepAgentTitle',
        hintKey: 'install.stepAgentHint',
        code: `Add the Pointer feedback widget to this app using the pointer-init skill — project key: ${projectKey}, Pointer server URL: ${server}, environment: local`,
      },
      { titleKey: 'demo.step5Title', hintKey: 'demo.step5Hint' },
      // Kept English on purpose — the pointer-feedback skill triggers on this phrasing.
      { titleKey: 'demo.step6Title', hintKey: 'demo.step6Hint', code: 'What are the new Pointer comments?' },
    ],
    manual: [
      { titleKey: 'demo.step1Title', hintKey: 'demo.step1Hint', code: `<script src="${server}/pointer.js" defer></script>` },
      { titleKey: 'demo.step2Title', hintKey: 'demo.step2Hint', code: `<pointer-feedback project="${projectKey}" server="${server}"></pointer-feedback>` },
    ],
  };
}

/** The credentials snippet, shared by the code guide and the extension sign-in step:
 *  demo widget login during a demo session, the signed-in user's email otherwise. */
function credentialsSnippet(input: {
  server: string;
  userEmail: string | null;
  demo: DemoSession | null;
  credsEmailedText: string;
}): string {
  const { demo } = input;
  return demo
    ? demo.emailSent
      ? input.credsEmailedText
      : `POINTER_EMAIL=${demo.email ?? ''}\nPOINTER_PASSWORD=${demo.password ?? ''}`
    : `POINTER_EMAIL=${input.userEmail ?? ''}\nPOINTER_PASSWORD=${PASSWORD_PLACEHOLDER}`;
}

/**
 * Builds the Chrome-extension install steps. Pure, like buildSteps, so the
 * credentials branching is unit-testable the same way.
 */
export function buildExtensionSteps(input: {
  server: string;
  userEmail: string | null;
  demo: DemoSession | null;
  credsEmailedText: string;
}): SetupStep[] {
  const { server } = input;
  return [
    {
      titleKey: 'install.extStep1Title',
      hintKey: 'install.extStep1Hint',
      downloadUrl: EXTENSION_ZIP_URL,
    },
    { titleKey: 'install.extStep2Title', hintKey: 'install.extStep2Hint' },
    { titleKey: 'install.extStep3Title', hintKey: 'install.extStep3Hint', code: 'chrome://extensions' },
    {
      titleKey: 'install.extStep4Title',
      hintKey: 'install.extStep4Hint',
      code: `${server}\n${credentialsSnippet(input)}`,
    },
  ];
}

/**
 * The installation steps, in a dialog. Opened from the header icon (any signed-in
 * user, any time) and automatically for a workspace admin who is new here or has
 * no feedback yet — see InstallGuideService for that policy.
 */
@Component({
  selector: 'app-install-guide',
  standalone: true,
  imports: [
    MatDialogModule,
    MatButtonModule,
    MatIconModule,
    MatSelectModule,
    MatFormFieldModule,
    MatCheckboxModule,
    MatButtonToggleModule,
    RouterLink,
    TranslocoModule,
  ],
  template: `
    <h2 mat-dialog-title class="flex items-center gap-2">
      <mat-icon class="text-brand">rocket_launch</mat-icon>
      {{ 'install.title' | transloco }}
    </h2>

    <mat-dialog-content>
      <!-- Top-level install method. Not persisted: "Code" is the default every time. -->
      <mat-button-toggle-group class="mb-4" [value]="tab()" (change)="tab.set($event.value)">
        <mat-button-toggle value="code">{{ 'install.tabCode' | transloco }}</mat-button-toggle>
        <mat-button-toggle value="extension">{{ 'install.tabExtension' | transloco }}</mat-button-toggle>
      </mat-button-toggle-group>

      @if (tab() === 'extension') {
        <!-- Chrome extension: download, unzip, load unpacked, sign in -->
        <ol class="mt-0 mb-0 flex list-none flex-col gap-3 p-0">
          @for (st of extensionSteps(); track st.titleKey; let i = $index) {
            <li class="rounded-lg border border-app-border bg-app/40 p-3">
              <div class="text-[0.85rem] font-semibold">{{ i + 1 }}. {{ st.titleKey | transloco }}</div>
              <div class="mt-0.5 text-[0.78rem] text-muted">{{ st.hintKey | transloco }}</div>
              @if (st.downloadUrl; as url) {
                <a mat-flat-button color="primary" class="mt-2" [href]="url" download>
                  <mat-icon>download</mat-icon> {{ 'install.extDownload' | transloco }}
                </a>
              } @else if (st.code; as code) {
                <div class="mt-2 flex items-start gap-2">
                  <pre class="m-0 flex-1 overflow-x-auto whitespace-pre-wrap rounded bg-app px-2 py-1.5 text-[0.78rem]"><code>{{ code }}</code></pre>
                  <button mat-stroked-button class="border-app-border" type="button" (click)="copy(code)">
                    <mat-icon>content_copy</mat-icon> {{ 'demo.copy' | transloco }}
                  </button>
                </div>
              }
            </li>
          }
        </ol>
      } @else {
      <p class="mt-0 mb-4 text-[0.85rem] text-muted">{{ 'install.intro' | transloco }}</p>

      <!-- Which project the snippet points at -->
      @if (projects().length > 0) {
        <mat-form-field appearance="outline" subscriptSizing="dynamic" class="w-full">
          <mat-label>{{ 'install.project' | transloco }}</mat-label>
          <mat-select [value]="projectKey()" (selectionChange)="projectKey.set($event.value)">
            @for (p of projects(); track p.id) {
              <mat-option [value]="p.key">{{ p.name }} ({{ p.key }})</mat-option>
            }
          </mat-select>
        </mat-form-field>
      } @else if (!demo()) {
        <p class="my-0 rounded-lg border border-app-border bg-app/40 p-3 text-[0.85rem]">
          {{ 'install.noProjects' | transloco }}
          <a routerLink="/projects" mat-dialog-close class="text-brand underline">
            {{ 'nav.projects' | transloco }}
          </a>
        </p>
      }

      <!-- The recommended path: install the skills, then let the agent wire the widget -->
      <ol class="mt-4 mb-0 flex list-none flex-col gap-3 p-0">
        @for (st of steps().primary; track st.titleKey; let i = $index) {
          <li class="rounded-lg border border-app-border bg-app/40 p-3">
            <div class="text-[0.85rem] font-semibold">{{ i + 1 }}. {{ st.titleKey | transloco }}</div>
            <div class="mt-0.5 text-[0.78rem] text-muted">{{ st.hintKey | transloco }}</div>
            @if (st.code; as code) {
              <div class="mt-2 flex items-start gap-2">
                <pre class="m-0 flex-1 overflow-x-auto whitespace-pre-wrap rounded bg-app px-2 py-1.5 text-[0.78rem]"><code>{{ code }}</code></pre>
                <button mat-stroked-button class="border-app-border" type="button" (click)="copy(code)">
                  <mat-icon>content_copy</mat-icon> {{ 'demo.copy' | transloco }}
                </button>
              </div>
            }
          </li>
        }
      </ol>

      <!-- Hand-wiring, for anyone not using an agent. Collapsed: the prompt above
           does this per-stack, so these snippets are the fallback, not the path. -->
      <details class="mt-4 rounded-lg border border-app-border p-3">
        <summary class="cursor-pointer text-[0.85rem] font-semibold">
          {{ 'install.manualTitle' | transloco }}
        </summary>
        <p class="mb-2 mt-1 text-[0.78rem] text-muted">{{ 'install.manualHint' | transloco }}</p>
        <div class="flex flex-col gap-3">
          @for (st of steps().manual; track st.titleKey) {
            <div>
              <div class="text-[0.8rem] font-medium">{{ st.titleKey | transloco }}</div>
              <div class="mt-0.5 text-[0.75rem] text-muted">{{ st.hintKey | transloco }}</div>
              @if (st.code; as code) {
                <div class="mt-1.5 flex items-start gap-2">
                  <pre class="m-0 flex-1 overflow-x-auto whitespace-pre-wrap rounded bg-app px-2 py-1.5 text-[0.78rem]"><code>{{ code }}</code></pre>
                  <button mat-stroked-button class="border-app-border" type="button" (click)="copy(code)">
                    <mat-icon>content_copy</mat-icon> {{ 'demo.copy' | transloco }}
                  </button>
                </div>
              }
            </div>
          }
        </div>
      </details>
      }
    </mat-dialog-content>

    <mat-dialog-actions class="justify-between gap-3">
      <mat-checkbox [checked]="suppressed()" (change)="setSuppressed($event.checked)">
        <span class="text-[0.8rem]">{{ 'install.dontShowAgain' | transloco }}</span>
      </mat-checkbox>
      <button mat-flat-button color="primary" mat-dialog-close>{{ 'install.done' | transloco }}</button>
    </mat-dialog-actions>
  `,
})
export class InstallGuideComponent {
  private snack = inject(MatSnackBar);
  private transloco = inject(TranslocoService);
  private auth = inject(AuthService);
  private guide = inject(InstallGuideService);

  // Transloco loads its language file over HTTP, so a translate() call made while
  // building the steps can land before the file arrives and echo the key back. This
  // signal makes the computed below re-run once a load event fires.
  private translationEvents = toSignal(this.transloco.events$, { initialValue: null });

  readonly demo = signal<DemoSession | null>(this.readDemoSession());
  readonly projects = computed(() => this.guide.projects().filter((p) => p.key));

  /** Selected project key; defaults to the demo project, else the first one. */
  readonly projectKey = signal<string | null>(
    this.readDemoSession()?.projectKey ?? null,
  );

  readonly suppressed = signal(this.guide.isSuppressed(this.auth.user()?.id ?? null));

  /** Which install method the dialog shows. Component state only — not persisted. */
  readonly tab = signal<'code' | 'extension'>('code');

  private readonly stepsInput = () => ({
    server: this.demo()?.serverUrl || environment.apiBase,
    userEmail: this.auth.user()?.email ?? null,
    demo: this.demo(),
    credsEmailedText: this.translatedCredsEmailed(),
  });

  readonly steps = computed(() =>
    buildSteps({
      ...this.stepsInput(),
      projectKey: this.projectKey() ?? this.projects()[0]?.key ?? null,
    }),
  );

  readonly extensionSteps = computed(() => buildExtensionSteps(this.stepsInput()));

  /** Re-resolves whenever transloco emits (initial load, language switch). */
  private readonly translatedCredsEmailed = computed(() => {
    this.translationEvents();
    return this.transloco.translate('demo.credsEmailed');
  });

  constructor() {
    // Opening it counts as seen, however it was opened.
    this.guide.markShown(this.auth.user()?.id ?? null);
  }

  setSuppressed(checked: boolean): void {
    this.suppressed.set(checked);
    const userId = this.auth.user()?.id ?? null;
    if (checked) this.guide.suppress(userId);
    else this.guide.unsuppress(userId);
  }

  copy(text: string): void {
    navigator.clipboard?.writeText(text).then(
      () => this.snack.open(this.transloco.translate('demo.copied'), 'OK', { duration: 2000 }),
      () => this.snack.open(this.transloco.translate('demo.copyFailed'), 'OK', { duration: 3000 }),
    );
  }

  private readDemoSession(): DemoSession | null {
    try {
      return JSON.parse(sessionStorage.getItem(DEMO_SESSION_KEY) || 'null');
    } catch {
      return null;
    }
  }
}
