// angular/src/app/features/shell/demo-panel.component.ts
import { Component, computed, inject, OnDestroy, signal } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatSnackBar } from '@angular/material/snack-bar';
import { TranslocoModule, TranslocoService } from '@jsverse/transloco';

interface DemoSession {
  email?: string | null;
  password?: string | null;
  projectKey?: string | null;
  serverUrl?: string | null;
  expiresAt?: string;
  emailSent?: boolean;
}

/** One setup step in the guide slider. `code` is optional — instruction-only steps omit it. */
interface SetupStep {
  titleKey: string;
  hintKey: string;
  code?: string;
}

const DEMO_SESSION_KEY = 'pointer_demo';

/**
 * Dismissible banner shown in the shell while a demo session (stored in
 * sessionStorage under `pointer_demo`) is active. Surfaces the demo project key,
 * the widget login, a live countdown, and a step-by-step setup guide shown one
 * step at a time (Back / Next slider).
 */
@Component({
  selector: 'app-demo-panel',
  standalone: true,
  imports: [MatIconModule, MatButtonModule, TranslocoModule],
  template: `
    @if (session(); as s) {
      <div class="mb-4 rounded-xl border border-brand/40 bg-brand-tint p-4 text-ink">
        <div class="flex items-start gap-2">
          <mat-icon class="text-brand">science</mat-icon>
          <div class="flex-1">
            <div class="flex items-center gap-2">
              <span class="text-[1rem] font-bold">{{ 'demo.panelTitle' | transloco }}</span>
              <span class="ms-auto text-[0.85rem] text-muted">{{ countdownLabel() }}</span>
            </div>
            <p class="mt-1 mb-3 text-[0.85rem] text-muted">{{ 'demo.panelIntro' | transloco }}</p>

            <div class="grid gap-3 md:grid-cols-2">
              <div>
                <div class="text-[0.75rem] font-semibold uppercase text-muted">{{ 'demo.projectKey' | transloco }}</div>
                <code class="mt-1 inline-block rounded bg-app px-2 py-1 text-[0.85rem]">{{ s.projectKey }}</code>
              </div>
              <div>
                <div class="text-[0.75rem] font-semibold uppercase text-muted">{{ 'demo.widgetLogin' | transloco }}</div>
                <div class="mt-1 text-[0.85rem]">
                  <span class="font-medium">{{ s.email }}</span>
                  <span class="text-muted"> · </span>
                  <code class="rounded bg-app px-1.5 py-0.5">{{ s.password }}</code>
                </div>
              </div>
            </div>

            <!-- Setup guide: one step at a time, Back / Next -->
            <div class="mt-4 rounded-lg border border-app-border bg-app/40 p-3">
              @if (steps()[step() - 1]; as st) {
                <div>
                  <div class="text-[0.8rem] font-semibold">{{ st.titleKey | transloco }}</div>
                  <div class="text-[0.75rem] text-muted">{{ st.hintKey | transloco }}</div>
                  @if (st.code; as code) {
                    <div class="mt-1 flex items-start gap-2">
                      <pre class="m-0 flex-1 overflow-x-auto rounded bg-app px-2 py-1.5 text-[0.8rem]"><code>{{ code }}</code></pre>
                      <button mat-stroked-button class="border-app-border" type="button" (click)="copy(code)">
                        <mat-icon>content_copy</mat-icon> {{ 'demo.copy' | transloco }}
                      </button>
                    </div>
                  }
                </div>
              }

              <div class="mt-3 flex items-center gap-2">
                <button mat-stroked-button class="border-app-border" type="button" [disabled]="step() === 1" (click)="prev()">
                  <mat-icon>chevron_left</mat-icon> {{ 'demo.back' | transloco }}
                </button>
                <span class="text-[0.8rem] text-muted">{{ step() }} / {{ steps().length }}</span>
                <button mat-stroked-button class="ms-auto border-app-border" type="button" [disabled]="step() === steps().length" (click)="next()">
                  {{ 'demo.next' | transloco }} <mat-icon>chevron_right</mat-icon>
                </button>
              </div>
            </div>
          </div>
          <button mat-icon-button type="button" [attr.aria-label]="'demo.dismiss' | transloco" (click)="dismiss()">
            <mat-icon>close</mat-icon>
          </button>
        </div>
      </div>
    }
  `,
})
export class DemoPanelComponent implements OnDestroy {
  private snack = inject(MatSnackBar);
  private transloco = inject(TranslocoService);

  private now = signal(Date.now());
  private timer = setInterval(() => this.now.set(Date.now()), 1000);
  session = signal<DemoSession | null>(this.read());

  // The setup guide, derived from the demo session. Add/remove entries here to
  // change the guide — the slider count follows the array length.
  steps = computed<SetupStep[]>(() => {
    const s = this.session();
    if (!s) return [];
    const srv = s.serverUrl ?? '';
    return [
      { titleKey: 'demo.step1Title', hintKey: 'demo.step1Hint', code: `<script src="${srv}/pointer.js" defer></script>` },
      { titleKey: 'demo.step2Title', hintKey: 'demo.step2Hint', code: `<pointer-feedback project="${s.projectKey ?? ''}" server="${srv}"></pointer-feedback>` },
      { titleKey: 'demo.step3Title', hintKey: 'demo.step3Hint', code: `curl -fsSL ${srv}/install.sh | sh` },
      {
        titleKey: 'demo.step4Title',
        hintKey: 'demo.step4Hint',
        code: s.emailSent
          ? this.transloco.translate('demo.credsEmailed')
          : `POINTER_EMAIL=${s.email ?? ''}\nPOINTER_PASSWORD=${s.password ?? ''}`,
      },
      { titleKey: 'demo.step5Title', hintKey: 'demo.step5Hint' },
      // Example prompt kept English — the pointer-feedback skill triggers on it.
      { titleKey: 'demo.step6Title', hintKey: 'demo.step6Hint', code: 'What are the new Pointer comments?' },
    ];
  });

  step = signal(1);
  next(): void { this.step.update((n) => Math.min(this.steps().length, n + 1)); }
  prev(): void { this.step.update((n) => Math.max(1, n - 1)); }

  countdownLabel = computed(() => {
    const s = this.session();
    if (!s?.expiresAt) return '';
    const remaining = new Date(s.expiresAt).getTime() - this.now();
    if (remaining <= 0) return this.transloco.translate('demo.expired');
    const totalMinutes = Math.floor(remaining / 60000);
    const hours = Math.floor(totalMinutes / 60);
    const minutes = totalMinutes % 60;
    return this.transloco.translate('demo.expiresIn', { hours, minutes });
  });

  private read(): DemoSession | null {
    try {
      return JSON.parse(sessionStorage.getItem(DEMO_SESSION_KEY) || 'null');
    } catch {
      return null;
    }
  }

  copy(text: string): void {
    navigator.clipboard?.writeText(text).then(
      () => this.snack.open(this.transloco.translate('demo.copied'), 'OK', { duration: 2000 }),
      () => this.snack.open(this.transloco.translate('demo.copyFailed'), 'OK', { duration: 3000 })
    );
  }

  dismiss(): void {
    sessionStorage.removeItem(DEMO_SESSION_KEY);
    this.session.set(null);
  }

  ngOnDestroy(): void {
    clearInterval(this.timer);
  }
}

// react/src/components/DemoPanel.tsx
// DemoPanel — shown inside the shell whenever a pointer_demo sessionStorage
// entry exists. Displays project key, widget login, a live countdown to expiry,
// and a 6-step data-driven setup guide shown one step at a time (Back / Next slider).
// Dismissible for the current session only.
import { useEffect, useState, useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import { Copy, Check, X, ChevronLeft, ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/button';

const DEMO_SESSION_KEY = 'pointer_demo';

interface DemoSession {
  email: string | null;
  password: string | null;
  projectKey: string | null;
  serverUrl: string | null;
  expiresAt: string | undefined;
}

/** One setup step in the guide slider. `code` is optional — instruction-only steps omit it. */
interface SetupStep {
  titleKey: string;
  hintKey: string;
  code?: string;
}

function readDemoSession(): DemoSession | null {
  try {
    const raw = sessionStorage.getItem(DEMO_SESSION_KEY);
    if (!raw) return null;
    return JSON.parse(raw) as DemoSession;
  } catch {
    return null;
  }
}

function formatCountdown(ms: number): string {
  if (ms <= 0) return '0:00';
  const totalSec = Math.floor(ms / 1000);
  const h = Math.floor(totalSec / 3600);
  const m = Math.floor((totalSec % 3600) / 60);
  const s = totalSec % 60;
  if (h > 0) return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
  return `${m}:${String(s).padStart(2, '0')}`;
}

function buildSteps(session: DemoSession): SetupStep[] {
  const srv = session.serverUrl ?? '';
  const proj = session.projectKey ?? '';
  const email = session.email ?? '';
  const password = session.password ?? '';
  return [
    {
      titleKey: 'demo.step1Title',
      hintKey: 'demo.step1Hint',
      code: `<script src="${srv}/pointer.js" defer></script>`,
    },
    {
      titleKey: 'demo.step2Title',
      hintKey: 'demo.step2Hint',
      code: `<pointer-feedback project="${proj}" server="${srv}"></pointer-feedback>`,
    },
    {
      titleKey: 'demo.step3Title',
      hintKey: 'demo.step3Hint',
      code: `curl -fsSL ${srv}/install.sh | sh`,
    },
    {
      titleKey: 'demo.step4Title',
      hintKey: 'demo.step4Hint',
      code: `POINTER_EMAIL=${email}\nPOINTER_PASSWORD=${password}`,
    },
    {
      titleKey: 'demo.step5Title',
      hintKey: 'demo.step5Hint',
      // no code — instruction-only step
    },
    {
      titleKey: 'demo.step6Title',
      hintKey: 'demo.step6Hint',
      // Fixed English literal — do NOT translate.
      code: 'What are the new Pointer comments?',
    },
  ];
}

export function DemoPanel() {
  const { t } = useTranslation();
  const [session, setSession] = useState<DemoSession | null>(() => readDemoSession());
  const [dismissed, setDismissed] = useState(false);
  const [copiedStep, setCopiedStep] = useState<number | null>(null);
  const [countdown, setCountdown] = useState<string>('');
  const [step, setStep] = useState(1);

  const refreshCountdown = useCallback(() => {
    if (!session?.expiresAt) return;
    const ms = new Date(session.expiresAt).getTime() - Date.now();
    setCountdown(formatCountdown(ms));
    if (ms <= 0) {
      sessionStorage.removeItem(DEMO_SESSION_KEY);
      setSession(null);
    }
  }, [session]);

  useEffect(() => {
    refreshCountdown();
    const id = setInterval(refreshCountdown, 1000);
    return () => clearInterval(id);
  }, [refreshCountdown]);

  if (!session || dismissed) return null;

  const { projectKey, serverUrl, email, password, expiresAt } = session;

  const isExpiringSoon = expiresAt
    ? new Date(expiresAt).getTime() - Date.now() < 5 * 60 * 1000
    : false;

  const steps = buildSteps(session);
  const currentStep = steps[step - 1];

  async function copyText(text: string, stepIndex: number) {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedStep(stepIndex);
      setTimeout(() => setCopiedStep(null), 2000);
    } catch {
      // clipboard not available — silently ignore
    }
  }

  return (
    <div className="border-b border-border bg-brand-tint px-4 py-3">
      <div className="mx-auto max-w-5xl">
        {/* Header row: banner badge + project key + countdown + dismiss */}
        <div className="mb-3 flex items-center gap-2">
          <span className="text-xs font-semibold uppercase tracking-wide text-brand">
            {t('demo.banner')}
          </span>
          <span className="rounded bg-brand px-1.5 py-0.5 text-xs font-mono text-white">
            {projectKey}
          </span>
          {expiresAt && (
            <span
              className={`ms-auto text-xs font-mono ${isExpiringSoon ? 'text-destructive' : 'text-muted-foreground'}`}
            >
              {t('demo.expires')} {countdown}
            </span>
          )}
          <Button
            variant="ghost"
            size="icon"
            className="h-6 w-6 shrink-0"
            onClick={() => setDismissed(true)}
            aria-label={t('demo.dismiss')}
          >
            <X className="h-4 w-4" />
          </Button>
        </div>

        {/* Widget login credentials */}
        <div className="mb-3 grid gap-3 md:grid-cols-2">
          <div>
            <div className="text-[0.75rem] font-semibold uppercase text-muted-foreground">
              {t('demo.widgetLogin')}
            </div>
            <div className="mt-1 text-xs">
              <span className="font-medium">{email}</span>
              <span className="text-muted-foreground"> · </span>
              <code className="rounded bg-background px-1.5 py-0.5 border border-border">{password}</code>
            </div>
          </div>
        </div>

        {/* Setup guide slider */}
        <div className="rounded-lg border border-border bg-background/40 p-3">
          {/* Current step content */}
          <div className="mb-3">
            <div className="text-xs font-semibold">{t(currentStep.titleKey)}</div>
            <div className="text-xs text-muted-foreground">{t(currentStep.hintKey)}</div>
            {currentStep.code !== undefined && (
              <div className="mt-1 flex items-start gap-2">
                <pre className="m-0 flex-1 overflow-x-auto rounded-md border border-border bg-background px-3 py-1.5 text-xs">
                  <code>{currentStep.code}</code>
                </pre>
                <Button
                  variant="outline"
                  size="sm"
                  className="shrink-0"
                  onClick={() => copyText(currentStep.code!, step)}
                  aria-label={t('demo.copy')}
                >
                  {copiedStep === step ? (
                    <Check className="me-1 h-3.5 w-3.5 text-green-500" />
                  ) : (
                    <Copy className="me-1 h-3.5 w-3.5" />
                  )}
                  {copiedStep === step ? t('demo.copied') : t('demo.copy')}
                </Button>
              </div>
            )}
          </div>

          {/* Navigation row: Back · counter · Next */}
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => setStep((s) => Math.max(1, s - 1))}
              disabled={step === 1}
              aria-label={t('demo.back')}
            >
              <ChevronLeft className="me-1 h-3.5 w-3.5" />
              {t('demo.back')}
            </Button>
            <span className="text-xs text-muted-foreground">
              {step} / {steps.length}
            </span>
            <Button
              variant="outline"
              size="sm"
              className="ms-auto"
              onClick={() => setStep((s) => Math.min(steps.length, s + 1))}
              disabled={step === steps.length}
              aria-label={t('demo.next')}
            >
              {t('demo.next')}
              <ChevronRight className="ms-1 h-3.5 w-3.5" />
            </Button>
          </div>
        </div>

        {/* Server URL reference */}
        {serverUrl && (
          <div className="mt-2 text-[0.7rem] text-muted-foreground">
            {serverUrl}
          </div>
        )}
      </div>
    </div>
  );
}
