// react/src/features/users/UsersPage.tsx
// Users admin page. React port of angular/.../users/users.component.ts.
// list with Approved/Pending/Rejected filters; add user; approve pending
// (choose role); reject (confirmed); enable/disable (disable confirmed);
// change role inline for approved users.
import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { useQueryClient } from '@tanstack/react-query';
import {
  useGetApiAdminUsers,
  useGetApiAdminRoles,
  usePostApiAdminUsers,
  usePatchApiAdminUsersId,
  usePostApiAdminUsersIdApprove,
  usePostApiAdminUsersIdReject,
  getGetApiAdminUsersQueryKey,
  type UserResponse,
  type RoleResponse,
  useGetApiAdminInvites,
  usePostApiAdminInvites,
  useDeleteApiAdminInvitesId,
  getGetApiAdminInvitesQueryKey,
  type InviteResponse,
} from '@moamen-ui/pointer-react';
import type { ColumnDef } from '@tanstack/react-table';
import { Plus, Ban, CheckCircle2, UserCheck, User, Users, Link, Copy, MailCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { PasswordInput } from '@/components/ui/password-input';
import { DataTable } from '@/components/shared/data-table/DataTable';
import type { RowActionItem } from '@/components/shared/types';
import { FormField } from '@/components/shared/FormField';
import { EmptyState } from '@/components/EmptyState';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { ConfirmDialog } from '@/components/ConfirmDialog';
import { useToast } from '@/components/ui/toast';
import { cn } from '@/lib/utils';
import { extractMessage } from '@/lib/error';
import { formatRequestedAt } from '@/lib/format';

type FilterStatus = 'Approved' | 'Pending' | 'Rejected';

// A union row type (real users + pending invites) with per-kind columns/actions --
// none of it forced into DataTable's core API, per this page's deliberate escape hatch.
type Row = ({ kind: 'user' } & UserResponse) | ({ kind: 'invite' } & InviteResponse);

export function UsersPage() {
  const { t } = useTranslation();
  const { toast } = useToast();
  const qc = useQueryClient();
  const navigate = useNavigate();

  const [filter, setFilter] = useState<FilterStatus>('Approved');

  const { data: users = [], isFetching } = useGetApiAdminUsers({
    status: filter.toLowerCase(),
  });

  // Separate count for the Pending badge regardless of the active filter.
  const { data: pending = [] } = useGetApiAdminUsers({ status: 'pending' });

  const { data: roles = [] } = useGetApiAdminRoles();

  // Pending invites render as rows in the Pending view too — they're "not a
  // member yet" just like a pending user, until accepted (then they become an
  // Approved user directly and drop out of this list).
  const { data: invitesRaw } = useGetApiAdminInvites();
  const invites = useMemo(() => (invitesRaw as InviteResponse[] | undefined) ?? [], [invitesRaw]);

  const activeRoles = useMemo(() => roles.filter((r) => r.isActive), [roles]);
  const nonAdminActiveRoles = useMemo(
    () => activeRoles.filter((r) => !r.grantsAdmin),
    [activeRoles],
  );
  const pendingCount = pending.length + invites.length;

  // Invalidate every users list (any status filter) by matching the shared
  // prefix the generated key helper produces without params.
  function reload() {
    qc.invalidateQueries({ queryKey: getGetApiAdminUsersQueryKey() });
  }
  const onError = (e: unknown) => toast(extractMessage(e), 'error');

  // For an approved user's inline role select, keep their current role even if
  // it has since been disabled (mirrors angular rolesForUser).
  function rolesForUser(user: UserResponse): RoleResponse[] {
    const current = roles.find((r) => r.id === user.roleId);
    if (current && !current.isActive) return [current, ...activeRoles];
    return activeRoles;
  }

  // ---- Add user: "Send invite" is the default mode, "Create directly" is secondary ----
  const [addOpen, setAddOpen] = useState(false);
  const [addMode, setAddMode] = useState<'invite' | 'direct'>('invite');

  // Direct-creation fields
  const [email, setEmail] = useState('');
  const [displayName, setDisplayName] = useState('');
  const [password, setPassword] = useState('');
  const [roleId, setRoleId] = useState<number>(0);

  const addMut = usePostApiAdminUsers({
    mutation: {
      onSuccess: () => {
        setAddOpen(false);
        reload();
      },
      onError,
    },
  });

  // Invite fields
  const [inviteRoleId, setInviteRoleId] = useState('');
  const [inviteEmail, setInviteEmail] = useState('');
  const [inviteExpiresDays, setInviteExpiresDays] = useState('7');
  const [inviteMaxUses, setInviteMaxUses] = useState('');
  const [createdInvite, setCreatedInvite] = useState<{ url: string; emailSent: string | null } | null>(
    null,
  );

  const inviteMut = usePostApiAdminInvites({
    mutation: {
      onSuccess: (res) => {
        const inv = res as unknown as InviteResponse;
        setCreatedInvite({ url: inv.url ?? '', emailSent: inv.emailSent && inv.email ? inv.email : null });
        toast(t('invite.created'));
        void qc.invalidateQueries({ queryKey: getGetApiAdminInvitesQueryKey() });
      },
      onError,
    },
  });

  function openAdd() {
    setEmail('');
    setDisplayName('');
    setPassword('');
    setRoleId(activeRoles[0]?.id ?? 0);
    setInviteRoleId(String(nonAdminActiveRoles[0]?.id ?? ''));
    setInviteEmail('');
    setInviteExpiresDays('7');
    setInviteMaxUses('');
    setCreatedInvite(null);
    setAddMode('invite');
    setAddOpen(true);
  }
  const addInvalid =
    !email.trim() || !displayName.trim() || !password.trim() || roleId < 1;
  function addUser() {
    if (addInvalid) return;
    addMut.mutate({
      data: {
        email: email.trim(),
        displayName: displayName.trim(),
        password,
        roleId,
      },
    });
  }

  function sendInvite() {
    if (!inviteRoleId) return;
    inviteMut.mutate({
      data: {
        roleId: Number(inviteRoleId),
        email: inviteEmail.trim() || undefined,
        expiresInDays: inviteExpiresDays ? Number(inviteExpiresDays) : undefined,
        maxUses: inviteMaxUses ? Number(inviteMaxUses) : undefined,
      },
    });
  }

  function copyInviteUrl(url: string) {
    void navigator.clipboard.writeText(url).then(() => toast(t('invite.copied')));
  }

  const revokeInviteMut = useDeleteApiAdminInvitesId({
    mutation: {
      onSuccess: () => {
        toast(t('invite.revoked'));
        void qc.invalidateQueries({ queryKey: getGetApiAdminInvitesQueryKey() });
      },
      onError,
    },
  });

  function formatInviteExpiry(iso: string | undefined) {
    if (!iso) return '—';
    try {
      return new Date(iso).toLocaleDateString();
    } catch {
      return iso;
    }
  }

  // ---- Change role / enable-disable (patch) ----
  const patchMut = usePatchApiAdminUsersId({
    mutation: {
      onSuccess: () => reload(),
      onError: (e: unknown) => {
        onError(e);
        reload();
      },
    },
  });

  function changeRole(user: UserResponse, newRoleId: number) {
    patchMut.mutate({ id: user.id!, data: { roleId: newRoleId } });
  }

  const [confirmUser, setConfirmUser] = useState<UserResponse | null>(null);
  function toggleActive(user: UserResponse) {
    if (!user.isActive) {
      patchMut.mutate({ id: user.id!, data: { isActive: true } });
      return;
    }
    setConfirmUser(user);
  }
  function confirmDisable() {
    const u = confirmUser;
    setConfirmUser(null);
    if (u) patchMut.mutate({ id: u.id!, data: { isActive: false } });
  }

  // ---- Approve ----
  const [approveUserState, setApproveUserState] = useState<UserResponse | null>(null);
  const [approveRoleId, setApproveRoleId] = useState<number>(0);

  const approveMut = usePostApiAdminUsersIdApprove({
    mutation: {
      onSuccess: () => {
        setApproveUserState(null);
        reload();
      },
      onError,
    },
  });

  function openApprove(user: UserResponse) {
    setApproveUserState(user);
    setApproveRoleId(user.roleId || activeRoles[0]?.id || 0);
  }
  function approve() {
    if (!approveUserState || approveRoleId < 1) return;
    approveMut.mutate({ id: approveUserState.id!, data: { roleId: approveRoleId } });
  }

  // ---- Reject ----
  const [rejectUser, setRejectUser] = useState<UserResponse | null>(null);
  const rejectMut = usePostApiAdminUsersIdReject({
    mutation: {
      onSuccess: () => {
        setRejectUser(null);
        reload();
      },
      onError,
    },
  });
  function confirmReject() {
    if (rejectUser) rejectMut.mutate({ id: rejectUser.id! });
  }

  const isApproved = filter === 'Approved';
  const filters: FilterStatus[] = ['Approved', 'Pending', 'Rejected'];
  // Under the Pending filter, invite rows are appended after real pending users.
  const totalRows = filter === 'Pending' ? users.length + invites.length : users.length;

  const rows: Row[] = useMemo(() => {
    const userRows: Row[] = users.map((u) => ({ kind: 'user' as const, ...u }));
    if (filter !== 'Pending') return userRows;
    const inviteRows: Row[] = invites.map((i) => ({ kind: 'invite' as const, ...i }));
    return [...userRows, ...inviteRows];
  }, [users, invites, filter]);

  const columns: ColumnDef<Row>[] = [
    {
      accessorKey: 'email',
      enableSorting: false,
      header: t('users.email'),
      cell: ({ row }) =>
        row.original.kind === 'invite'
          ? row.original.email || t('invite.anyone')
          : row.original.email,
    },
    {
      id: 'displayName',
      enableSorting: false,
      header: t('users.name'),
      cell: ({ row }) => (row.original.kind === 'invite' ? '—' : row.original.displayName),
    },
    {
      id: 'role',
      enableSorting: false,
      header: t('users.role'),
      cell: ({ row }) => {
        if (row.original.kind === 'invite') return row.original.roleName ?? '—';
        const user = row.original;
        if (isApproved) {
          return (
            <Select
              value={user.roleId != null ? String(user.roleId) : undefined}
              onValueChange={(v) => changeRole(user, Number(v))}
            >
              <SelectTrigger className="min-w-[140px]">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {rolesForUser(user).map((r) => (
                  <SelectItem key={r.id} value={String(r.id)}>
                    {r.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          );
        }
        return <span>{user.roleName}</span>;
      },
    },
  ];
  if (!isApproved) {
    columns.push({
      id: 'requested',
      enableSorting: false,
      header: t('overview.requested'),
      cell: ({ row }) => {
        if (row.original.kind === 'invite') {
          return `${t('invite.expires')}: ${formatInviteExpiry(row.original.expiresAt)}`;
        }
        // createdAt = when access was requested. The API returns it; the
        // generated client only declares it from the next publish on.
        const requestedAt = (row.original as { createdAt?: string | null }).createdAt ?? null;
        return requestedAt ? formatRequestedAt(requestedAt) : '—';
      },
    });
  }
  columns.push({
    id: 'status',
    enableSorting: false,
    header: t('users.status'),
    cell: ({ row }) => {
      if (row.original.kind === 'invite') {
        return (
          <span className="inline-flex h-6 items-center gap-1 rounded-full border px-2 text-[12px] font-medium leading-none text-state-archived bg-state-archived-tint border-state-archived/30">
            {t('invite.invited')}
          </span>
        );
      }
      return (
        <span className={cn(
          'inline-flex h-6 items-center gap-1 rounded-full border px-2 text-[12px] font-medium leading-none',
          row.original.isActive
            ? 'text-state-completed bg-state-completed-tint border-state-completed/30'
            : 'text-state-danger bg-state-danger-tint border-state-danger/30'
        )}>
          {row.original.isActive ? (
            <>
              <CheckCircle2 className="h-3 w-3" />
              {t('common.active')}
            </>
          ) : (
            <>
              <Ban className="h-3 w-3" />
              {t('common.disabled')}
            </>
          )}
        </span>
      );
    },
  });

  function actionsFor(row: Row): RowActionItem[] {
    if (row.kind === 'invite') {
      return [
        { label: t('invite.copy'), icon: Copy, disabled: !row.url, onClick: () => copyInviteUrl(row.url ?? '') },
        {
          label: t('invite.revoke'),
          severity: 'danger',
          disabled: revokeInviteMut.isPending,
          onClick: () => revokeInviteMut.mutate({ id: row.id! }),
        },
      ];
    }
    const user = row;
    const items: RowActionItem[] = [];
    if (isApproved) {
      items.push({
        label: t(user.isActive ? 'common.disable' : 'common.enable'),
        icon: user.isActive ? Ban : CheckCircle2,
        severity: user.isActive ? 'danger' : 'neutral',
        disabled: patchMut.isPending,
        onClick: () => toggleActive(user),
      });
    } else {
      items.push({ label: t('users.approve'), icon: UserCheck, onClick: () => openApprove(user) });
      if (filter === 'Pending') {
        items.push({ label: t('users.reject'), icon: Ban, severity: 'danger', onClick: () => setRejectUser(user) });
      }
    }
    items.push({ label: t('profile.viewProfile'), icon: User, onClick: () => navigate(`/users/${user.id}/profile`) });
    return items;
  }

  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-center justify-between">
        <h1 className="text-[20px] font-semibold leading-7 tracking-[-0.01em]">{t('users.title')}</h1>
        <Button onClick={openAdd}>
          <Plus className="h-4 w-4" />
          {t('users.addUser')}
        </Button>
      </div>

      {/* Filter bar — label + segmented control */}
      <div className="flex items-center gap-3">
        <span className="text-[13px] text-muted-foreground">{t('common.show')}</span>
        <div className="inline-flex gap-0.5 rounded-md border border-border bg-gutter p-0.5">
          {filters.map((f) => (
            <button
              key={f}
              type="button"
              onClick={() => setFilter(f)}
              className={cn(
                'h-7 px-3 rounded-[4px] text-[13px] font-medium transition-colors',
                filter === f
                  ? 'bg-background text-foreground border border-border'
                  : 'text-muted-foreground hover:text-foreground',
              )}
            >
              {t(
                f === 'Approved'
                  ? 'users.filterApproved'
                  : f === 'Pending'
                    ? 'users.filterPending'
                    : 'users.filterRejected',
              )}
              {f === 'Pending' && pendingCount > 0 && (
                <span className="ms-1 inline-flex h-5 items-center justify-center rounded-full bg-state-ready px-1.5 text-[10px] font-medium text-white">
                  {pendingCount}
                </span>
              )}
            </button>
          ))}
        </div>
      </div>

      {totalRows === 0 && !isFetching ? (
        <EmptyState
          icon={Users}
          message={t('users.empty')}
          hint={t('users.emptyHint')}
        >
          <Button onClick={openAdd}>
            <Plus className="h-4 w-4" />
            {t('users.addUser')}
          </Button>
        </EmptyState>
      ) : (
        <DataTable
          data={rows}
          columns={columns}
          actions={actionsFor}
          actionsAriaLabel={t('users.actions')}
          actionsHeader={t('users.actions')}
          gutter
        />
      )}

      {/* Add user dialog — "Send invite" (default) or "Create directly" (secondary) */}
      <Dialog open={addOpen} onOpenChange={setAddOpen}>
        <DialogContent className="w-[min(520px,calc(100vw-32px))] rounded-lg border border-border bg-background shadow-dialog">
          <DialogHeader>
            <DialogTitle className="text-base font-semibold leading-6">{t('users.addUser')}</DialogTitle>
          </DialogHeader>

          {!createdInvite && (
            <div className="inline-flex gap-0.5 rounded-md border border-border bg-gutter p-0.5">
              <button
                type="button"
                onClick={() => setAddMode('invite')}
                className={cn(
                  'h-7 px-3 rounded-[4px] text-[13px] font-medium transition-colors',
                  addMode === 'invite'
                    ? 'bg-background text-foreground border border-border'
                    : 'text-muted-foreground hover:text-foreground',
                )}
              >
                {t('users.modeInvite')}
              </button>
              <button
                type="button"
                onClick={() => setAddMode('direct')}
                className={cn(
                  'h-7 px-3 rounded-[4px] text-[13px] font-medium transition-colors',
                  addMode === 'direct'
                    ? 'bg-background text-foreground border border-border'
                    : 'text-muted-foreground hover:text-foreground',
                )}
              >
                {t('users.modeDirect')}
              </button>
            </div>
          )}

          {addMode === 'invite' ? (
            createdInvite ? (
              <div className="flex flex-col gap-3 pt-1">
                {createdInvite.emailSent && (
                  <div className="flex items-center gap-2 rounded-md border border-state-completed/30 bg-state-completed-tint px-3 py-2 text-sm text-state-completed">
                    <MailCheck className="h-4 w-4 shrink-0" />
                    <span>{t('invite.emailSent', { email: createdInvite.emailSent })}</span>
                  </div>
                )}
                <div className="flex items-center gap-2 rounded-md border border-border bg-muted/40 px-3 py-2">
                  <p className="flex-1 truncate text-xs font-mono">{createdInvite.url}</p>
                  <Button size="sm" variant="ghost" onClick={() => copyInviteUrl(createdInvite.url)} type="button">
                    <Copy className="h-4 w-4" />
                    {t('invite.copy')}
                  </Button>
                </div>
              </div>
            ) : (
              <div className="flex flex-col gap-3 pt-1">
                <p className="text-xs text-muted-foreground">{t('invite.sectionHint')}</p>
                <FormField label={t('invite.role')} htmlFor="invite-role">
                  <Select value={inviteRoleId} onValueChange={setInviteRoleId}>
                    <SelectTrigger id="invite-role">
                      <SelectValue placeholder={t('invite.role')} />
                    </SelectTrigger>
                    <SelectContent>
                      {nonAdminActiveRoles.map((r) => (
                        <SelectItem key={r.id} value={String(r.id)}>
                          {r.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </FormField>
                <FormField label={t('invite.email')} htmlFor="invite-email">
                  <Input
                    id="invite-email"
                    type="email"
                    value={inviteEmail}
                    onChange={(e) => setInviteEmail(e.target.value)}
                    placeholder="teammate@example.com"
                  />
                </FormField>
                <div className="flex gap-3">
                  <div className="flex-1">
                    <FormField label={t('invite.expiresDays')} htmlFor="invite-expires-days">
                      <Input
                        id="invite-expires-days"
                        type="number"
                        min={1}
                        value={inviteExpiresDays}
                        onChange={(e) => setInviteExpiresDays(e.target.value)}
                      />
                    </FormField>
                  </div>
                  <div className="flex-1">
                    <FormField label={t('invite.maxUses')} htmlFor="invite-max-uses">
                      <Input
                        id="invite-max-uses"
                        type="number"
                        min={1}
                        value={inviteMaxUses}
                        onChange={(e) => setInviteMaxUses(e.target.value)}
                        placeholder="∞"
                      />
                    </FormField>
                  </div>
                </div>
              </div>
            )
          ) : (
            <div className="flex flex-col gap-3 pt-1">
              <FormField label={t('users.email')} htmlFor="u-email">
                <Input
                  id="u-email"
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  autoFocus
                />
              </FormField>
              <FormField label={t('users.displayName')} htmlFor="u-name">
                <Input
                  id="u-name"
                  value={displayName}
                  onChange={(e) => setDisplayName(e.target.value)}
                />
              </FormField>
              <FormField label={t('users.password')} htmlFor="u-pass">
                <PasswordInput
                  id="u-pass"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                />
              </FormField>
              <FormField label={t('users.role')} htmlFor="u-role">
                <Select
                  value={roleId ? String(roleId) : undefined}
                  onValueChange={(v) => setRoleId(Number(v))}
                >
                  <SelectTrigger id="u-role">
                    <SelectValue placeholder={t('users.role')} />
                  </SelectTrigger>
                  <SelectContent>
                    {activeRoles.map((r) => (
                      <SelectItem key={r.id} value={String(r.id)}>
                        {r.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </FormField>
            </div>
          )}

          <DialogFooter className="gap-2">
            {addMode === 'invite' ? (
              createdInvite ? (
                <Button onClick={() => setAddOpen(false)}>{t('invite.done')}</Button>
              ) : (
                <>
                  <Button variant="outline" onClick={() => setAddOpen(false)}>
                    {t('common.cancel')}
                  </Button>
                  <Button disabled={!inviteRoleId || inviteMut.isPending} onClick={sendInvite}>
                    <Link className="h-4 w-4" />
                    {t('invite.create')}
                  </Button>
                </>
              )
            ) : (
              <>
                <Button variant="outline" onClick={() => setAddOpen(false)}>
                  {t('common.cancel')}
                </Button>
                <Button disabled={addInvalid || addMut.isPending} onClick={addUser}>
                  <Plus className="h-4 w-4" />
                  {t('users.addUser')}
                </Button>
              </>
            )}
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Approve dialog */}
      <Dialog open={!!approveUserState} onOpenChange={(o) => !o && setApproveUserState(null)}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>{t('users.approve')}</DialogTitle>
          </DialogHeader>
          <div className="pt-1">
            <FormField label={t('users.approveAs')} htmlFor="approve-user-role">
              <Select
                value={approveRoleId ? String(approveRoleId) : undefined}
                onValueChange={(v) => setApproveRoleId(Number(v))}
              >
                <SelectTrigger id="approve-user-role">
                  <SelectValue placeholder={t('users.approveAs')} />
                </SelectTrigger>
                <SelectContent>
                  {activeRoles.map((r) => (
                    <SelectItem key={r.id} value={String(r.id)}>
                      {r.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </FormField>
          </div>
          <DialogFooter className="gap-2">
            <Button variant="outline" onClick={() => setApproveUserState(null)}>
              {t('common.cancel')}
            </Button>
            <Button disabled={approveRoleId < 1 || approveMut.isPending} onClick={approve}>
              {t('users.confirm')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Reject confirmation */}
      <ConfirmDialog
        open={!!rejectUser}
        message={t('users.confirmReject', { name: rejectUser?.email })}
        confirmLabel={t('users.reject')}
        confirmColor="warn"
        onConfirm={confirmReject}
        onCancel={() => setRejectUser(null)}
      />

      {/* Disable confirmation */}
      <ConfirmDialog
        open={!!confirmUser}
        message={t('common.confirmDisable', { name: confirmUser?.email })}
        confirmLabel={t('common.disable')}
        confirmColor="warn"
        onConfirm={confirmDisable}
        onCancel={() => setConfirmUser(null)}
      />
    </div>
  );
}

// vue/src/features/users/UsersPage.vue
<script setup lang="ts">
import { computed, reactive, ref } from 'vue';
import { useI18n } from 'vue-i18n';
import { useRouter } from 'vue-router';
import { useQueryClient } from '@tanstack/vue-query';
import type { ColumnDef } from '@tanstack/vue-table';
import {
  useGetApiAdminUsers,
  useGetApiAdminRoles,
  usePostApiAdminUsers,
  usePatchApiAdminUsersId,
  usePostApiAdminUsersIdApprove,
  usePostApiAdminUsersIdReject,
  getGetApiAdminUsersQueryKey,
  useGetApiAdminInvites,
  usePostApiAdminInvites,
  useDeleteApiAdminInvitesId,
  getGetApiAdminInvitesQueryKey,
  type UserResponse,
  type RoleResponse,
  type InviteResponse,
} from '@moamen-ui/pointer-vue';
import {
  Plus,
  Ban,
  CheckCircle2,
  UserCheck,
  UserRound,
  Users,
  Copy,
  Link2Off,
  MailCheck,
} from 'lucide-vue-next';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { PasswordInput } from '@/components/ui/password-input';
import { Label } from '@/components/ui/label';
import { DataTable, dataTableFeatures } from '@/components/shared/data-table';
import type { RowActionItem } from '@/components/shared/types';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { extractMessage } from '@/lib/error';
import { formatRequestedAt } from '@/lib/formatRequestedAt';
import { cn } from '@/lib/utils';
import { confirm } from '@/composables/useConfirm';
import { toast } from '@/composables/useToast';
import EmptyState from '@/shared/EmptyState.vue';

type FilterStatus = 'Approved' | 'Pending' | 'Rejected';

// A union row type (real users + pending invites) with per-kind columns/actions --
// none of it forced into DataTable's core API, per this page's deliberate escape hatch.
type Row = ({ kind: 'user' } & UserResponse) | ({ kind: 'invite' } & InviteResponse);

const { t } = useI18n();
const router = useRouter();

const filter = ref<FilterStatus>('Approved');
const busy = ref(false);

const queryClient = useQueryClient();

// Main users query — driven by a reactive param so it re-fetches (and re-keys)
// whenever the filter changes.
const usersParams = computed(() => ({ status: filter.value.toLowerCase() || undefined }));
const usersQuery = useGetApiAdminUsers(usersParams);
// Separate query for the Pending badge count.
const pendingQuery = useGetApiAdminUsers({ status: 'pending' });
const rolesQuery = useGetApiAdminRoles();

const users = computed<UserResponse[]>(() => usersQuery.data.value ?? []);
const roles = computed<RoleResponse[]>(() => rolesQuery.data.value ?? []);
const loading = computed(() => usersQuery.isLoading.value || busy.value);

// ── Pending invites — rendered as rows in the Pending view, right alongside
// real pending users; created via "Send invite" in the Add User dialog below.
// Once accepted, an invite becomes an Approved user directly and drops out here.
const invitesQuery = useGetApiAdminInvites();
const inviteList = computed<InviteResponse[]>(
  () => (invitesQuery.data.value ?? []) as InviteResponse[],
);
const pendingCount = computed(() => (pendingQuery.data.value?.length ?? 0) + inviteList.value.length);

const createUser = usePostApiAdminUsers();
const updateUser = usePatchApiAdminUsersId();
const approveUser = usePostApiAdminUsersIdApprove();
const rejectUser = usePostApiAdminUsersIdReject();

const FILTERS: FilterStatus[] = ['Approved', 'Pending', 'Rejected'];

function activeRoles(): RoleResponse[] {
  return roles.value.filter((r) => r.isActive);
}

function rolesForUser(user: UserResponse): RoleResponse[] {
  const active = activeRoles();
  const current = roles.value.find((r) => r.id === user.roleId);
  if (current && !current.isActive) return [current, ...active];
  return active;
}

function setFilter(status: FilterStatus) {
  filter.value = status;
}

function fail(e: unknown) {
  busy.value = false;
  toast(extractMessage(e));
}
// The base ["api","admin","users"] key prefix-matches every users query
// (filtered list + pending-count), so one invalidation refreshes both.
function reloadUsers() {
  void queryClient.invalidateQueries({ queryKey: getGetApiAdminUsersQueryKey() });
}

// ── Add user: "Send invite" is the default mode, "Create directly" is secondary ──
const addOpen = ref(false);
const addMode = ref<'invite' | 'direct'>('invite');
const addForm = reactive({ email: '', displayName: '', password: '', roleId: 0 });

const addInvalid = computed(
  () =>
    !addForm.email ||
    !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(addForm.email) ||
    !addForm.displayName ||
    !addForm.password ||
    !addForm.roleId,
);

const nonAdminActiveRoles = computed<RoleResponse[]>(
  () => roles.value.filter((r) => !r.grantsAdmin && r.isActive),
);

const inviteRoleId = ref<number | null>(null);
const inviteEmail = ref('');
const inviteExpiresDays = ref<number | undefined>(7);
const inviteMaxUses = ref<number | undefined>(undefined);
const createdInvite = ref<{ url: string; emailSent: string | null } | null>(null);

const createInvite = usePostApiAdminInvites();

function openAdd() {
  addForm.email = '';
  addForm.displayName = '';
  addForm.password = '';
  addForm.roleId = activeRoles()[0]?.id ?? 0;
  inviteRoleId.value = nonAdminActiveRoles.value[0]?.id ?? null;
  inviteEmail.value = '';
  inviteExpiresDays.value = 7;
  inviteMaxUses.value = undefined;
  createdInvite.value = null;
  addMode.value = 'invite';
  addOpen.value = true;
}

async function addUser() {
  if (addInvalid.value) return;
  busy.value = true;
  try {
    await createUser.mutateAsync({ data: { ...addForm } });
    addOpen.value = false;
    busy.value = false;
    reloadUsers();
  } catch (e) {
    fail(e);
  }
}

async function sendInvite() {
  if (!inviteRoleId.value) return;
  try {
    const res = (await createInvite.mutateAsync({
      data: {
        roleId: inviteRoleId.value ?? undefined,
        email: inviteEmail.value || undefined,
        expiresInDays: inviteExpiresDays.value ?? undefined,
        maxUses: inviteMaxUses.value ?? undefined,
      },
    })) as unknown as InviteResponse;
    createdInvite.value = {
      url: res.url ?? '',
      emailSent: res.emailSent && res.email ? res.email : null,
    };
    toast(t('invite.created'));
    void queryClient.invalidateQueries({ queryKey: getGetApiAdminInvitesQueryKey() });
  } catch (e) {
    toast(extractMessage(e));
  }
}

async function copyUrl(url: string) {
  try {
    await navigator.clipboard.writeText(url);
    toast(t('invite.copied'));
  } catch {
    toast(url);
  }
}

// ── Change role (approved view) ───────────────────────────────────────
function reloadCurrentList() {
  void queryClient.invalidateQueries({
    queryKey: getGetApiAdminUsersQueryKey(usersParams.value),
  });
}

async function changeRole(user: UserResponse, roleId: number) {
  busy.value = true;
  try {
    await updateUser.mutateAsync({ id: user.id!, data: { roleId } });
    busy.value = false;
    reloadCurrentList();
  } catch (e) {
    fail(e);
    reloadCurrentList();
  }
}

// ── Active toggle ─────────────────────────────────────────────────────
async function toggleActive(user: UserResponse) {
  if (!user.isActive) {
    await patchActive(user, true);
    return;
  }
  const ok = await confirm({
    message: t('common.confirmDisable', { name: user.email }),
    confirmLabel: t('common.disable'),
    confirmVariant: 'destructive',
  });
  if (ok) await patchActive(user, false);
}

async function patchActive(user: UserResponse, isActive: boolean) {
  busy.value = true;
  try {
    await updateUser.mutateAsync({ id: user.id!, data: { isActive } });
    busy.value = false;
    reloadCurrentList();
  } catch (e) {
    fail(e);
  }
}

// ── Approve (with role selection) ─────────────────────────────────────
const approveSelection = reactive<Record<number, number>>({});
const approveOpenFor = ref<number | null>(null);

function openApprove(user: UserResponse) {
  approveSelection[user.id!] = user.roleId ?? activeRoles()[0]?.id ?? 0;
  approveOpenFor.value = user.id!;
}

async function approve(user: UserResponse) {
  const roleId = approveSelection[user.id!] ?? user.roleId;
  busy.value = true;
  try {
    await approveUser.mutateAsync({ id: user.id!, data: { roleId } });
    approveOpenFor.value = null;
    busy.value = false;
    reloadUsers();
  } catch (e) {
    fail(e);
  }
}

// ── Reject ────────────────────────────────────────────────────────────
async function reject(user: UserResponse) {
  const ok = await confirm({
    message: t('users.confirmReject', { name: user.email }),
    confirmLabel: t('users.reject'),
    confirmVariant: 'destructive',
  });
  if (!ok) return;
  busy.value = true;
  try {
    await rejectUser.mutateAsync({ id: user.id! });
    busy.value = false;
    reloadUsers();
  } catch (e) {
    fail(e);
  }
}

function requestedAt(user: UserResponse): string | null {
  // createdAt lands in UserResponse with the next client publish; narrow cast until then
  return (user as { createdAt?: string | null }).createdAt ?? null;
}

const revokeInvite = useDeleteApiAdminInvitesId();

async function onRevoke(id: number) {
  try {
    await revokeInvite.mutateAsync({ id });
    toast(t('invite.revoked'));
    void queryClient.invalidateQueries({ queryKey: getGetApiAdminInvitesQueryKey() });
  } catch (e) {
    toast(extractMessage(e));
  }
}

function formatInviteDate(iso: string | undefined): string {
  if (!iso) return '—';
  return new Date(iso).toLocaleDateString();
}

const rows = computed<Row[]>(() => {
  const userRows: Row[] = users.value.map((u) => ({ kind: 'user' as const, ...u }));
  if (filter.value !== 'Pending') return userRows;
  const invRows: Row[] = inviteList.value.map((i) => ({ kind: 'invite' as const, ...i }));
  return [...userRows, ...invRows];
});

// A computed so headers follow live language switches, and the conditional
// "requested" column follows the active filter.
const columns = computed<ColumnDef<typeof dataTableFeatures, Row>[]>(() => {
  const cols: ColumnDef<typeof dataTableFeatures, Row>[] = [
    { accessorKey: 'email', header: t('users.email'), enableSorting: false },
    { id: 'displayName', header: t('users.name'), enableSorting: false },
    { id: 'role', header: t('users.role'), enableSorting: false },
  ];
  if (filter.value !== 'Approved') {
    cols.push({ id: 'requested', header: t('overview.requested'), enableSorting: false });
  }
  cols.push({ id: 'status', header: t('users.status'), enableSorting: false });
  return cols;
});

function actionsFor(row: Row): RowActionItem[] {
  if (row.kind === 'invite') {
    const items: RowActionItem[] = [];
    if (row.url) {
      items.push({ label: t('invite.copy'), icon: Copy, onClick: () => void copyUrl(row.url!) });
    }
    items.push({ label: t('invite.revoke'), icon: Link2Off, severity: 'danger', onClick: () => void onRevoke(row.id!) });
    return items;
  }
  const user = row;
  const items: RowActionItem[] = [];
  if (filter.value === 'Approved') {
    items.push({
      label: t(user.isActive ? 'common.disable' : 'common.enable'),
      icon: user.isActive ? Ban : CheckCircle2,
      severity: user.isActive ? 'danger' : 'neutral',
      disabled: loading.value,
      onClick: () => void toggleActive(user),
    });
  } else {
    items.push({ label: t('users.approve'), icon: UserCheck, disabled: loading.value, onClick: () => openApprove(user) });
    if (filter.value === 'Pending') {
      items.push({ label: t('users.reject'), icon: Ban, severity: 'danger', disabled: loading.value, onClick: () => void reject(user) });
    }
  }
  // View profile link — always shown for approved users (matches this page's
  // pre-existing convention, kept as-is).
  if (filter.value === 'Approved') {
    items.push({ label: t('profile.viewProfile'), icon: UserRound, onClick: () => router.push(`/users/${user.id}/profile`) });
  }
  return items;
}
</script>

<template>
  <div class="flex flex-col gap-4">
    <div class="flex items-center justify-between">
      <h1 class="text-[20px] font-semibold leading-7 tracking-[-0.01em]">{{ t('users.title') }}</h1>
      <Button @click="openAdd">
        <Plus class="h-4 w-4" /> {{ t('users.addUser') }}
      </Button>
    </div>

    <!-- Filter bar — segmented control -->
    <div class="flex items-center gap-3 mb-3">
      <span class="text-[13px] text-muted-foreground">{{ t('common.show') }}</span>
      <div class="inline-flex gap-0.5 rounded-md border border-border bg-gutter p-0.5">
        <button
          v-for="f in FILTERS"
          :key="f"
          type="button"
          :class="
            cn(
              'h-7 px-3 rounded-[4px] text-[13px] font-medium transition-colors',
              filter === f
                ? 'bg-background text-foreground border border-border'
                : 'text-muted-foreground hover:text-foreground',
            )
          "
          @click="setFilter(f)"
        >
          {{ t('users.filter' + f) }}
          <span
            v-if="f === 'Pending' && pendingCount"
            class="ms-1 inline-flex h-5 items-center justify-center rounded-full bg-state-ready px-1.5 text-[10px] font-medium text-white"
          >
            {{ pendingCount }}
          </span>
        </button>
      </div>
    </div>

    <EmptyState
      v-if="(filter === 'Pending' ? users.length + inviteList.length : users.length) === 0 && !loading"
      :icon="Users"
      :message="t('users.empty')"
      :hint="t('users.emptyHint')"
    >
      <Button @click="openAdd">
        <Plus class="h-4 w-4" /> {{ t('users.addUser') }}
      </Button>
    </EmptyState>

    <!-- Escape hatch: rows are a union type (real users + pending invites) with
         per-kind columns/actions, none of which fit a homogeneous DataTable
         row shape -- every custom column renders through a scoped slot. -->
    <DataTable
      v-else
      :data="rows"
      :columns="columns"
      :actions="actionsFor"
      :actions-aria-label="t('users.actions')"
      :actions-header="t('users.actions')"
      :loading="loading"
      gutter
    >
      <template #cell-email="{ row }">
        {{ row.kind === 'invite' ? (row.email ?? t('invite.anyone')) : row.email }}
      </template>
      <template #cell-displayName="{ row }">
        {{ row.kind === 'invite' ? '—' : row.displayName }}
      </template>
      <template #cell-role="{ row }">
        <template v-if="row.kind === 'invite'">{{ row.roleName ?? '—' }}</template>
        <template v-else>
          <Select
            v-if="filter === 'Approved'"
            :model-value="row.roleId != null ? String(row.roleId) : undefined"
            @update:model-value="(v: any) => v != null && changeRole(row, Number(v))"
          >
            <SelectTrigger class="min-w-[140px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem v-for="role in rolesForUser(row)" :key="role.id" :value="String(role.id)">
                {{ role.name }}
              </SelectItem>
            </SelectContent>
          </Select>
          <span v-else>{{ row.roleName }}</span>
        </template>
      </template>
      <template #cell-requested="{ row }">
        {{ row.kind === 'invite' ? `${t('invite.expires')}: ${formatInviteDate(row.expiresAt)}` : formatRequestedAt(requestedAt(row)) }}
      </template>
      <template #cell-status="{ row }">
        <span
          v-if="row.kind === 'invite'"
          class="inline-flex h-6 items-center gap-1 rounded-full border px-2 text-[12px] font-medium leading-none text-state-archived bg-state-archived-tint border-state-archived/30"
        >
          {{ t('invite.invited') }}
        </span>
        <span
          v-else
          :class="
            cn(
              'inline-flex h-6 items-center gap-1 rounded-full border px-2 text-[12px] font-medium leading-none',
              row.isActive
                ? 'text-state-completed bg-state-completed-tint border-state-completed/30'
                : 'text-state-danger bg-state-danger-tint border-state-danger/30'
            )
          "
        >
          <CheckCircle2 v-if="row.isActive" class="h-3 w-3" />
          <Ban v-else class="h-3 w-3" />
          {{ t(row.isActive ? 'common.active' : 'common.disabled') }}
        </span>
      </template>
    </DataTable>
  </div>

  <!-- Add user dialog — "Send invite" (default) or "Create directly" (secondary) -->
  <Dialog v-model:open="addOpen">
    <DialogContent class="w-[min(520px,calc(100vw-32px))] rounded-lg border border-border bg-background shadow-dialog">
      <DialogHeader>
        <DialogTitle class="text-base font-semibold leading-6">{{ t('users.addUser') }}</DialogTitle>
      </DialogHeader>

      <div
        v-if="!createdInvite"
        class="inline-flex gap-0.5 rounded-md border border-border bg-gutter p-0.5"
      >
        <button
          type="button"
          :class="
            cn(
              'h-7 px-3 rounded-[4px] text-[13px] font-medium transition-colors',
              addMode === 'invite'
                ? 'bg-background text-foreground border border-border'
                : 'text-muted-foreground hover:text-foreground',
            )
          "
          @click="addMode = 'invite'"
        >
          {{ t('users.modeInvite') }}
        </button>
        <button
          type="button"
          :class="
            cn(
              'h-7 px-3 rounded-[4px] text-[13px] font-medium transition-colors',
              addMode === 'direct'
                ? 'bg-background text-foreground border border-border'
                : 'text-muted-foreground hover:text-foreground',
            )
          "
          @click="addMode = 'direct'"
        >
          {{ t('users.modeDirect') }}
        </button>
      </div>

      <template v-if="addMode === 'invite'">
        <div v-if="createdInvite" class="flex flex-col gap-3 py-2">
          <div
            v-if="createdInvite.emailSent"
            class="flex items-center gap-2 rounded-md border border-state-completed/30 bg-state-completed-tint p-3 text-sm text-state-completed"
          >
            <MailCheck class="h-4 w-4 shrink-0" />
            <span>{{ t('invite.emailSent', { email: createdInvite.emailSent }) }}</span>
          </div>
          <div class="flex items-center gap-2 rounded-md bg-gutter p-3">
            <span class="flex-1 truncate text-sm font-mono">{{ createdInvite.url }}</span>
            <Button type="button" size="sm" variant="secondary" @click="copyUrl(createdInvite.url)">
              <Copy class="h-4 w-4" />{{ t('invite.copy') }}
            </Button>
          </div>
        </div>
        <form v-else class="flex flex-col gap-4 py-2 space-y-4" @submit.prevent="sendInvite">
          <p class="text-xs text-muted-foreground">{{ t('invite.sectionHint') }}</p>
          <div class="flex flex-col gap-1.5">
            <Label for="invite-role" class="text-[13px] font-medium">{{ t('invite.role') }}</Label>
            <Select
              :model-value="inviteRoleId != null ? String(inviteRoleId) : undefined"
              @update:model-value="(v) => (inviteRoleId = v ? Number(v) : null)"
            >
              <SelectTrigger id="invite-role">
                <SelectValue :placeholder="t('invite.role')" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem v-for="r in nonAdminActiveRoles" :key="r.id" :value="String(r.id)">
                  {{ r.name }}
                </SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div class="flex flex-col gap-1.5">
            <Label for="invite-email" class="text-[13px] font-medium">{{ t('invite.email') }}</Label>
            <Input id="invite-email" v-model="inviteEmail" type="email" placeholder="teammate@example.com" />
          </div>
          <div class="flex gap-3">
            <div class="flex flex-1 flex-col gap-1.5">
              <Label for="invite-expires" class="text-[13px] font-medium">{{ t('invite.expiresDays') }}</Label>
              <Input id="invite-expires" v-model.number="inviteExpiresDays" type="number" :min="1" />
            </div>
            <div class="flex flex-1 flex-col gap-1.5">
              <Label for="invite-maxuses" class="text-[13px] font-medium">{{ t('invite.maxUses') }}</Label>
              <Input id="invite-maxuses" v-model.number="inviteMaxUses" type="number" :min="1" placeholder="∞" />
            </div>
          </div>
        </form>
      </template>

      <form v-else class="flex flex-col gap-4 py-2 space-y-4" @submit.prevent="addUser">
        <div class="flex flex-col gap-1.5">
          <Label for="u-email" class="text-[13px] font-medium">{{ t('users.email') }}</Label>
          <Input id="u-email" v-model="addForm.email" type="email" />
        </div>
        <div class="flex flex-col gap-1.5">
          <Label for="u-name" class="text-[13px] font-medium">{{ t('users.displayName') }}</Label>
          <Input id="u-name" v-model="addForm.displayName" />
        </div>
        <div class="flex flex-col gap-1.5">
          <Label for="u-pass" class="text-[13px] font-medium">{{ t('users.password') }}</Label>
          <PasswordInput id="u-pass" v-model="addForm.password" />
        </div>
        <div class="flex flex-col gap-1.5">
          <Label class="text-[13px] font-medium">{{ t('users.role') }}</Label>
          <Select
            :model-value="addForm.roleId ? String(addForm.roleId) : undefined"
            @update:model-value="(v: any) => (addForm.roleId = v != null ? Number(v) : 0)"
          >
            <SelectTrigger>
              <SelectValue :placeholder="t('users.role')" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem v-for="role in activeRoles()" :key="role.id" :value="String(role.id)">
                {{ role.name }}
              </SelectItem>
            </SelectContent>
          </Select>
        </div>
      </form>

      <DialogFooter>
        <template v-if="addMode === 'invite'">
          <Button v-if="createdInvite" @click="addOpen = false">{{ t('invite.done') }}</Button>
          <template v-else>
            <Button variant="outline" @click="addOpen = false">{{ t('common.cancel') }}</Button>
            <Button :disabled="!inviteRoleId || createInvite.isPending.value" @click="sendInvite">
              {{ t('invite.create') }}
            </Button>
          </template>
        </template>
        <template v-else>
          <Button variant="outline" @click="addOpen = false">{{ t('common.cancel') }}</Button>
          <Button :disabled="addInvalid || loading" @click="addUser">
            <Plus class="h-4 w-4" /> {{ t('users.addUser') }}
          </Button>
        </template>
      </DialogFooter>
    </DialogContent>
  </Dialog>

  <!-- Approve-as dialog -->
  <Dialog
    :open="approveOpenFor !== null"
    @update:open="(o: boolean) => { if (!o) approveOpenFor = null; }"
  >
    <DialogContent class="w-[min(520px,calc(100vw-32px))] rounded-lg border border-border bg-background shadow-dialog">
      <DialogHeader>
        <DialogTitle class="text-base font-semibold leading-6">{{ t('users.approveAs') }}</DialogTitle>
      </DialogHeader>
      <template v-for="user in users" :key="'ap-' + user.id">
        <div v-if="approveOpenFor === user.id" class="flex flex-col gap-4 py-2 space-y-4">
          <div class="flex flex-col gap-1.5">
            <Label class="text-[13px] font-medium">{{ t('users.role') }}</Label>
            <Select
              :model-value="approveSelection[user.id!] ? String(approveSelection[user.id!]) : undefined"
              @update:model-value="(v: any) => v != null && (approveSelection[user.id!] = Number(v))"
            >
              <SelectTrigger>
                <SelectValue :placeholder="t('users.approveAs')" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem v-for="r in activeRoles()" :key="r.id" :value="String(r.id)">
                  {{ r.name }}
                </SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
      </template>
      <DialogFooter>
        <Button variant="secondary" @click="approveOpenFor = null">{{ t('common.cancel') }}</Button>
        <template v-for="user in users" :key="'ap-confirm-' + user.id">
          <Button v-if="approveOpenFor === user.id" :disabled="loading" @click="approve(user)">
            {{ t('users.confirm') }}
          </Button>
        </template>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>
