// vue/src/features/tenants/TenantsPage.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { useQueryClient } from '@tanstack/vue-query';
import {
  useGetApiAdminTenants,
  usePostApiAdminTenants,
  usePatchApiAdminTenantsId,
  useDeleteApiAdminTenantsId,
  getGetApiAdminTenantsQueryKey,
  type TenantResponse,
} from '@moamen-ui/pointer-vue';
import {
  usePostApiAdminTenantsIdExtend,
  usePatchApiAdminTenantsIdDemoConfig,
  useGetApiAdminPlans,
  usePatchApiAdminTenantsIdPlan,
} from '@moamen-ui/pointer-vue';
import { Plus, Trash2, CheckCircle2, Ban, ShieldCheck, Clock, Settings2, CreditCard, Building2, EllipsisVertical } from 'lucide-vue-next';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { PasswordInput } from '@/components/ui/password-input';
import { Label } from '@/components/ui/label';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { extractMessage } from '@/lib/error';
import { cn } from '@/lib/utils';
import { confirm } from '@/composables/useConfirm';
import { toast } from '@/composables/useToast';
import EmptyState from '@/shared/EmptyState.vue';

const { t } = useI18n();
const queryClient = useQueryClient();

const { data, isFetching, isError } = useGetApiAdminTenants();
// The interceptor unwraps the envelope at runtime; data.value IS TenantResponse[].
// Bridge the TS type mismatch with a cast (mirrors the React dashboard pattern).
const tenants = computed<TenantResponse[]>(() => (data.value as unknown as TenantResponse[] | undefined) ?? []);

const createTenant = usePostApiAdminTenants();
const patchTenant = usePatchApiAdminTenantsId();
const deleteTenant = useDeleteApiAdminTenantsId();
const extendTenant = usePostApiAdminTenantsIdExtend();
const patchDemoConfig = usePatchApiAdminTenantsIdDemoConfig();
const changePlanMut = usePatchApiAdminTenantsIdPlan();

// ── Plans list (for change-plan dropdown) ─────────────────────────────────────
interface PlanOption { id: number; name: string; }
const { data: plansData } = useGetApiAdminPlans();
const planOptions = computed<PlanOption[]>(
  () => ((plansData.value as unknown as PlanOption[] | undefined) ?? []).map((p: PlanOption) => ({ id: p.id, name: p.name })),
);

function reload() {
  void queryClient.invalidateQueries({ queryKey: getGetApiAdminTenantsQueryKey() });
}
function fail(e: unknown) {
  toast(extractMessage(e));
}

// ── Create tenant ──────────────────────────────────────────────────────
const addOpen = ref(false);
const newEmail = ref('');
const newPassword = ref('');
const newDisplayName = ref('');

function openAdd() {
  newEmail.value = '';
  newPassword.value = '';
  newDisplayName.value = '';
  addOpen.value = true;
}

async function doCreate() {
  const email = newEmail.value.trim();
  const password = newPassword.value;
  const displayName = newDisplayName.value.trim();
  if (!email || !password || !displayName) return;
  try {
    await createTenant.mutateAsync({ data: { email, password, displayName } });
    addOpen.value = false;
    toast(t('tenants.created'));
    reload();
  } catch (e) {
    fail(e);
  }
}

// ── Status actions ────────────────────────────────────────────────────
async function patchStatus(tenant: TenantResponse, action: string) {
  try {
    await patchTenant.mutateAsync({ id: tenant.id!, data: { action } });
    reload();
  } catch (e) {
    fail(e);
  }
}

async function approveTenant(tenant: TenantResponse) {
  await patchStatus(tenant, 'approve');
}

async function enableTenant(tenant: TenantResponse) {
  await patchStatus(tenant, 'enable');
}

async function disableTenant(tenant: TenantResponse) {
  const ok = await confirm({
    message: t('tenants.confirmDisable', { name: tenant.displayName ?? tenant.email }),
    confirmLabel: t('common.disable'),
    confirmVariant: 'destructive',
  });
  if (ok) await patchStatus(tenant, 'disable');
}

// ── Delete ────────────────────────────────────────────────────────────
async function doDelete(tenant: TenantResponse) {
  const ok = await confirm({
    message: t('tenants.confirmDelete', { name: tenant.displayName ?? tenant.email }),
    confirmLabel: t('common.delete'),
    confirmVariant: 'destructive',
  });
  if (!ok) return;
  try {
    await deleteTenant.mutateAsync({ id: tenant.id! });
    toast(t('tenants.deleted'));
    reload();
  } catch (e) {
    fail(e);
  }
}

// ── Extend demo ────────────────────────────────────────────────────────
async function doExtend(tenant: TenantResponse) {
  try {
    await extendTenant.mutateAsync({ id: tenant.id! });
    toast(t('tenants.extended'));
    reload();
  } catch (e) {
    fail(e);
  }
}

// ── Demo config dialog ────────────────────────────────────────────────
const demoConfigOpen = ref(false);
const demoConfigTenant = ref<TenantResponse | null>(null);
const demoCapInput = ref('');
const demoTtlInput = ref('');

function openDemoConfig(tenant: TenantResponse) {
  demoConfigTenant.value = tenant;
  const cap = (tenant as any).demoCommentCapOverride;
  const ttl = (tenant as any).demoTtlHoursOverride;
  demoCapInput.value = cap != null ? String(cap) : '';
  demoTtlInput.value = ttl != null ? String(ttl) : '';
  demoConfigOpen.value = true;
}

async function saveDemoConfig() {
  if (!demoConfigTenant.value) return;
  try {
    await patchDemoConfig.mutateAsync({
      id: demoConfigTenant.value.id!,
      data: {
        commentCapOverride: demoCapInput.value === '' ? null : Number(demoCapInput.value),
        ttlHoursOverride: demoTtlInput.value === '' ? null : Number(demoTtlInput.value),
      },
    });
    demoConfigOpen.value = false;
    toast(t('tenants.demoConfigSaved'));
    reload();
  } catch (e) {
    fail(e);
  }
}

// ── Helper: format ISO expiry ─────────────────────────────────────────
function formatExpiry(iso: string | null | undefined): string {
  if (!iso) return '—';
  try {
    return new Date(iso).toLocaleString();
  } catch {
    return iso;
  }
}

// ── Local edit state (seeded via watch, never mutates cache) ──────────
interface EditState {
  email: string;
  displayName: string;
}
const editMap = ref<Record<number, EditState>>({});

watch(
  tenants,
  (list) => {
    const next: Record<number, EditState> = {};
    for (const t of list) {
      const id = t.id!;
      // Preserve any in-flight edits; seed missing entries from fresh data.
      next[id] = editMap.value[id] ?? {
        email: t.email ?? '',
        displayName: t.displayName ?? '',
      };
    }
    editMap.value = next;
  },
  { immediate: true },
);

function approvalChip(status: string | null | undefined) {
  if (!status) return 'chip-neutral';
  if (status === 'approved') return 'chip-active';
  if (status === 'pending') return 'chip-pending';
  return 'chip-disabled';
}

// ── Change plan dialog ────────────────────────────────────────────────────────
const changePlanOpen = ref(false);
const changePlanTenant = ref<TenantResponse | null>(null);
const selectedPlanId = ref<string>('');

function openChangePlan(tenant: TenantResponse) {
  changePlanTenant.value = tenant;
  selectedPlanId.value = '';
  changePlanOpen.value = true;
}

async function saveChangePlan() {
  if (!changePlanTenant.value || !selectedPlanId.value) return;
  try {
    await changePlanMut.mutateAsync({
      id: changePlanTenant.value.id!,
      data: { planId: Number(selectedPlanId.value) },
    });
    changePlanOpen.value = false;
    toast(t('tenants.planChanged'));
    reload();
  } catch (e) {
    fail(e);
  }
}
</script>

<template>
  <div class="flex flex-col gap-4">
    <div class="flex items-center justify-between gap-3">
      <h2 class="text-lg font-semibold">{{ t('tenants.title') }}</h2>
      <Button @click="openAdd">
        <Plus class="h-4 w-4" /> {{ t('tenants.addTenant') }}
      </Button>
    </div>

    <p v-if="isError" class="text-sm text-destructive">{{ t('tenants.loadError') }}</p>

    <Card v-if="tenants.length > 0 || isFetching">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>{{ t('tenants.email') }}</TableHead>
            <TableHead>{{ t('tenants.displayName') }}</TableHead>
            <TableHead>{{ t('tenants.approval') }}</TableHead>
            <TableHead>{{ t('tenants.status') }}</TableHead>
            <TableHead>{{ t('tenants.projects') }}</TableHead>
            <TableHead>{{ t('tenants.comments') }}</TableHead>
            <TableHead>{{ t('tenants.demoExpiry') }}</TableHead>
            <TableHead>{{ t('tenants.plan') }}</TableHead>
            <TableHead>{{ t('tenants.actions') }}</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          <TableRow v-for="tenant in tenants" :key="tenant.id">
            <TableCell class="text-sm">{{ tenant.email }}</TableCell>
            <TableCell class="text-sm">{{ tenant.displayName }}</TableCell>
            <TableCell>
              <span :class="cn('chip', approvalChip(tenant.approvalStatus))">
                {{ tenant.approvalStatus ?? 'pending' }}
              </span>
            </TableCell>
            <TableCell>
              <span :class="cn('chip', tenant.isActive ? 'chip-active' : 'chip-disabled')">
                {{ t(tenant.isActive ? 'common.active' : 'common.disabled') }}
              </span>
            </TableCell>
            <TableCell>{{ tenant.projects ?? 0 }}</TableCell>
            <TableCell>{{ tenant.comments ?? 0 }}</TableCell>
            <!-- Demo expiry column -->
            <TableCell class="text-sm">
              <template v-if="(tenant as any).isDemo">
                {{ formatExpiry((tenant as any).expiresAt) }}
              </template>
              <template v-else>—</template>
            </TableCell>
            <!-- Plan column -->
            <TableCell class="text-sm">
              <div class="flex flex-col gap-0.5">
                <span>{{ (tenant as any).planName ?? t('tenants.freePlan') }}</span>
                <span v-if="(tenant as any).subscriptionStatus" class="chip chip-neutral text-[10px]">
                  {{ (tenant as any).subscriptionStatus }}
                </span>
              </div>
            </TableCell>
            <TableCell>
              <DropdownMenu>
                <DropdownMenuTrigger as-child>
                  <Button variant="ghost" size="icon">
                    <span class="sr-only">{{ t('tenants.actions') }}</span>
                    <EllipsisVertical class="h-4 w-4" />
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <DropdownMenuItem
                    v-if="tenant.approvalStatus !== 'approved'"
                    @select="approveTenant(tenant)"
                  >
                    <ShieldCheck class="h-4 w-4" /> {{ t('tenants.approve') }}
                  </DropdownMenuItem>
                  <DropdownMenuItem
                    v-if="tenant.isActive"
                    class="text-destructive focus:text-destructive"
                    @select="disableTenant(tenant)"
                  >
                    <Ban class="h-4 w-4" /> {{ t('common.disable') }}
                  </DropdownMenuItem>
                  <DropdownMenuItem v-else @select="enableTenant(tenant)">
                    <CheckCircle2 class="h-4 w-4" /> {{ t('common.enable') }}
                  </DropdownMenuItem>
                  <DropdownMenuItem
                    class="text-destructive focus:text-destructive"
                    @select="doDelete(tenant)"
                  >
                    <Trash2 class="h-4 w-4" /> {{ t('common.delete') }}
                  </DropdownMenuItem>
                  <DropdownMenuItem @select="openChangePlan(tenant)">
                    <CreditCard class="h-4 w-4" /> {{ t('tenants.changePlan') }}
                  </DropdownMenuItem>
                  <!-- Demo-only actions -->
                  <template v-if="(tenant as any).isDemo">
                    <DropdownMenuItem
                      :disabled="(tenant as any).demoExtended"
                      :title="(tenant as any).demoExtended ? t('tenants.extendOnce') : undefined"
                      @select="doExtend(tenant)"
                    >
                      <Clock class="h-4 w-4" /> {{ t('tenants.extend') }}
                    </DropdownMenuItem>
                    <DropdownMenuItem @select="openDemoConfig(tenant)">
                      <Settings2 class="h-4 w-4" /> {{ t('tenants.editDemoConfig') }}
                    </DropdownMenuItem>
                  </template>
                </DropdownMenuContent>
              </DropdownMenu>
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </Card>

    <EmptyState
      v-if="!isFetching && tenants.length === 0 && !isError"
      :icon="Building2"
      :message="t('tenants.empty')"
      :hint="t('tenants.emptyHint')"
    />
  </div>

  <!-- Create tenant dialog -->
  <Dialog v-model:open="addOpen">
    <DialogContent class="max-w-[440px]">
      <DialogHeader>
        <DialogTitle>{{ t('tenants.addTenant') }}</DialogTitle>
      </DialogHeader>
      <div class="flex flex-col gap-4 pt-2">
        <div class="flex flex-col gap-2">
          <Label for="tenant-email">{{ t('tenants.email') }}</Label>
          <Input id="tenant-email" v-model="newEmail" type="email" />
        </div>
        <div class="flex flex-col gap-2">
          <Label for="tenant-name">{{ t('tenants.displayName') }}</Label>
          <Input id="tenant-name" v-model="newDisplayName" />
        </div>
        <div class="flex flex-col gap-2">
          <Label for="tenant-password">{{ t('tenants.password') }}</Label>
          <PasswordInput id="tenant-password" v-model="newPassword" />
        </div>
      </div>
      <DialogFooter>
        <Button variant="outline" @click="addOpen = false">{{ t('common.cancel') }}</Button>
        <Button
          :disabled="!newEmail.trim() || !newPassword || !newDisplayName.trim()"
          @click="doCreate"
        >
          <Plus class="h-4 w-4" /> {{ t('tenants.addTenant') }}
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>

  <!-- Demo config dialog -->
  <Dialog v-model:open="demoConfigOpen">
    <DialogContent class="max-w-[440px]">
      <DialogHeader>
        <DialogTitle>{{ t('tenants.editDemoConfig') }}</DialogTitle>
      </DialogHeader>
      <div class="flex flex-col gap-4 pt-2">
        <p class="text-xs text-muted-foreground">{{ t('tenants.demoConfigHint') }}</p>
        <div class="flex flex-col gap-2">
          <Label for="demo-cap-override">{{ t('tenants.commentCapOverride') }}</Label>
          <Input
            id="demo-cap-override"
            v-model="demoCapInput"
            type="number"
            :min="1"
            :placeholder="t('tenants.overridePlaceholder')"
          />
        </div>
        <div class="flex flex-col gap-2">
          <Label for="demo-ttl-override">{{ t('tenants.ttlHoursOverride') }}</Label>
          <Input
            id="demo-ttl-override"
            v-model="demoTtlInput"
            type="number"
            :min="1"
            :placeholder="t('tenants.overridePlaceholder')"
          />
        </div>
      </div>
      <DialogFooter>
        <Button variant="outline" @click="demoConfigOpen = false">{{ t('common.cancel') }}</Button>
        <Button :disabled="patchDemoConfig.isPending.value" @click="saveDemoConfig">
          {{ t('common.save') }}
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>

  <!-- Change plan dialog -->
  <Dialog v-model:open="changePlanOpen">
    <DialogContent class="max-w-[440px]">
      <DialogHeader>
        <DialogTitle>{{ t('tenants.changePlan') }}</DialogTitle>
      </DialogHeader>
      <div class="flex flex-col gap-4 pt-2">
        <p class="text-sm text-muted-foreground">
          {{ t('tenants.changePlanFor', { name: changePlanTenant?.displayName ?? changePlanTenant?.email }) }}
        </p>
        <div class="flex flex-col gap-2">
          <Label for="change-plan-select">{{ t('tenants.plan') }}</Label>
          <Select v-model="selectedPlanId">
            <SelectTrigger id="change-plan-select">
              <SelectValue :placeholder="t('tenants.selectPlan')" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem v-for="plan in planOptions" :key="plan.id" :value="String(plan.id)">
                {{ plan.name }}
              </SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>
      <DialogFooter>
        <Button variant="outline" @click="changePlanOpen = false">{{ t('common.cancel') }}</Button>
        <Button
          :disabled="!selectedPlanId || changePlanMut.isPending.value"
          @click="saveChangePlan"
        >
          {{ t('common.save') }}
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>

// react/src/features/tenants/TenantsPage.tsx
// Tenants admin page — super-admin only.
// List all tenants; create; approve / enable / disable; delete with cascade warning.
// Demo tenants: show expiry column, Extend demo button, Demo config dialog.
// v2: Plan column (planName + subscriptionStatus) + Change plan action.
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useQueryClient } from '@tanstack/react-query';
import {
  useGetApiAdminTenants,
  usePostApiAdminTenants,
  usePatchApiAdminTenantsId,
  useDeleteApiAdminTenantsId,
  usePostApiAdminTenantsIdExtend,
  usePatchApiAdminTenantsIdDemoConfig,
  usePatchApiAdminTenantsIdPlan,
  useGetApiAdminPlans,
  getGetApiAdminTenantsQueryKey,
  type TenantResponse,
  type PlanAdminResponse,
} from '@moamen-ui/pointer-react';
import { Plus, Trash2, CheckCircle2, Ban, ShieldCheck, Clock, Settings2, CreditCard, EllipsisVertical, Building2 } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { PasswordInput } from '@/components/ui/password-input';
import { Label } from '@/components/ui/label';
import { EmptyState } from '@/components/EmptyState';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { ConfirmDialog } from '@/components/ConfirmDialog';
import { useToast } from '@/components/ui/toast';
import { cn } from '@/lib/utils';
import { extractMessage } from '@/lib/error';

// The new TenantResponse fields are not in ^1.0.7 yet — cast via this helper type.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyTenant = TenantResponse & Record<string, any>;

export function TenantsPage() {
  const { t } = useTranslation();
  const { toast } = useToast();
  const qc = useQueryClient();

  const { data, isLoading, isError, isFetching } = useGetApiAdminTenants();
  const tenants: AnyTenant[] = (data as unknown as { data?: AnyTenant[] })?.data
    ?? (Array.isArray(data) ? (data as AnyTenant[]) : []);

  // Fetch all plans for the change-plan dropdown
  const { data: plansData } = useGetApiAdminPlans();
  const allPlans: PlanAdminResponse[] =
    (plansData as unknown as { data?: PlanAdminResponse[] })?.data ??
    (Array.isArray(plansData) ? (plansData as PlanAdminResponse[]) : []);

  const reload = () =>
    void qc.invalidateQueries({ queryKey: getGetApiAdminTenantsQueryKey() });
  const onError = (e: unknown) => toast(extractMessage(e), 'error');

  // ---- Create ----
  const [addOpen, setAddOpen] = useState(false);
  const [newEmail, setNewEmail] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [newDisplayName, setNewDisplayName] = useState('');

  const createMut = usePostApiAdminTenants({
    mutation: {
      onSuccess: () => {
        setAddOpen(false);
        setNewEmail('');
        setNewPassword('');
        setNewDisplayName('');
        toast(t('tenants.created'));
        reload();
      },
      onError,
    },
  });

  function openAdd() {
    setNewEmail('');
    setNewPassword('');
    setNewDisplayName('');
    setAddOpen(true);
  }
  function addTenant() {
    if (!newEmail.trim() || !newPassword.trim() || !newDisplayName.trim()) return;
    createMut.mutate({
      data: {
        email: newEmail.trim(),
        password: newPassword,
        displayName: newDisplayName.trim(),
      },
    });
  }

  // ---- Status mutations (approve / enable / disable) ----
  const patchMut = usePatchApiAdminTenantsId({
    mutation: {
      onSuccess: () => {
        toast(t('tenants.updated'));
        reload();
      },
      onError,
    },
  });

  function setStatus(tenant: AnyTenant, action: string) {
    patchMut.mutate({ id: tenant.id!, data: { action } });
  }

  // ---- Delete with cascade warning ----
  const [deleteTarget, setDeleteTarget] = useState<AnyTenant | null>(null);

  const deleteMut = useDeleteApiAdminTenantsId({
    mutation: {
      onSuccess: () => {
        setDeleteTarget(null);
        toast(t('tenants.deleted'));
        reload();
      },
      onError: (e) => {
        setDeleteTarget(null);
        onError(e);
      },
    },
  });

  function confirmDelete() {
    if (deleteTarget?.id == null) return;
    deleteMut.mutate({ id: deleteTarget.id });
  }

  // ---- Extend demo ----
  const extendMut = usePostApiAdminTenantsIdExtend({
    mutation: {
      onSuccess: () => {
        toast(t('tenants.extended'));
        reload();
      },
      onError,
    },
  });

  // ---- Demo config dialog ----
  const [demoConfigTarget, setDemoConfigTarget] = useState<AnyTenant | null>(null);
  const [capInput, setCapInput] = useState('');
  const [ttlInput, setTtlInput] = useState('');

  function openDemoConfig(tenant: AnyTenant) {
    setCapInput(tenant.demoCommentCapOverride != null ? String(tenant.demoCommentCapOverride) : '');
    setTtlInput(tenant.demoTtlHoursOverride != null ? String(tenant.demoTtlHoursOverride) : '');
    setDemoConfigTarget(tenant);
  }

  const demoConfigMut = usePatchApiAdminTenantsIdDemoConfig({
    mutation: {
      onSuccess: () => {
        setDemoConfigTarget(null);
        toast(t('tenants.demoConfigSaved'));
        reload();
      },
      onError: (e) => {
        setDemoConfigTarget(null);
        onError(e);
      },
    },
  });

  function saveDemoConfig() {
    if (demoConfigTarget?.id == null) return;
    demoConfigMut.mutate({
      id: demoConfigTarget.id,
      data: {
        commentCapOverride: capInput === '' ? null : Number(capInput),
        ttlHoursOverride: ttlInput === '' ? null : Number(ttlInput),
      },
    });
  }

  // ---- Change plan ----
  const [changePlanTarget, setChangePlanTarget] = useState<AnyTenant | null>(null);
  const [selectedPlanId, setSelectedPlanId] = useState<string>('');

  function openChangePlan(tenant: AnyTenant) {
    setChangePlanTarget(tenant);
    // pre-select current plan if resolvable
    setSelectedPlanId('');
  }

  const changePlanMut = usePatchApiAdminTenantsIdPlan({
    mutation: {
      onSuccess: () => {
        setChangePlanTarget(null);
        toast(t('tenants.planChanged'));
        reload();
      },
      onError: (e) => {
        setChangePlanTarget(null);
        onError(e);
      },
    },
  });

  function saveChangePlan() {
    if (changePlanTarget?.id == null || !selectedPlanId) return;
    changePlanMut.mutate({
      id: changePlanTarget.id,
      data: { planId: Number(selectedPlanId) },
    });
  }

  // ---- Helpers ----
  function formatExpiry(expiresAt: string | null | undefined): string {
    if (!expiresAt) return '—';
    try {
      return new Date(expiresAt).toLocaleString();
    } catch {
      return expiresAt;
    }
  }

  // ---- Render ----
  if (isLoading && !data) {
    return (
      <div className="flex h-40 items-center justify-center text-sm text-muted-foreground">
        {t('tenants.loading')}
      </div>
    );
  }

  if (isError) {
    return (
      <div className="flex h-40 items-center justify-center text-sm text-destructive">
        {t('tenants.loadError')}
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-center justify-between gap-3">
        <h2 className="text-lg font-semibold">
          {t('tenants.title')}
          {isFetching && (
            <span className="ms-2 text-xs font-normal text-muted-foreground">
              {t('common.refresh')}…
            </span>
          )}
        </h2>
        <Button onClick={openAdd}>
          <Plus className="h-4 w-4" />
          {t('tenants.addTenant')}
        </Button>
      </div>

      {tenants.length === 0 ? (
        <EmptyState
          icon={Building2}
          message={t('tenants.empty')}
          hint={t('tenants.emptyHint')}
        />
      ) : (
        <Card>
          <Table>
          <TableHeader>
            <TableRow>
              <TableHead>{t('tenants.email')}</TableHead>
              <TableHead>{t('tenants.displayName')}</TableHead>
              <TableHead>{t('tenants.approval')}</TableHead>
              <TableHead>{t('tenants.statusCol')}</TableHead>
              <TableHead>{t('tenants.planCol')}</TableHead>
              <TableHead>{t('tenants.projects')}</TableHead>
              <TableHead>{t('tenants.comments')}</TableHead>
              <TableHead>{t('tenants.demoExpiry')}</TableHead>
              <TableHead>{t('tenants.actions')}</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {tenants.map((tenant) => (
              <TableRow key={tenant.id}>
                <TableCell className="font-medium">{tenant.email}</TableCell>
                <TableCell>{tenant.displayName ?? '—'}</TableCell>
                <TableCell>
                  <span
                    className={cn(
                      'chip',
                      tenant.approvalStatus === 'approved'
                        ? 'chip-active'
                        : tenant.approvalStatus === 'pending'
                          ? 'chip-neutral'
                          : 'chip-disabled',
                    )}
                  >
                    {tenant.approvalStatus ?? '—'}
                  </span>
                </TableCell>
                <TableCell>
                  <span className={cn('chip', tenant.isActive ? 'chip-active' : 'chip-disabled')}>
                    {t(tenant.isActive ? 'common.active' : 'common.disabled')}
                  </span>
                </TableCell>
                <TableCell>
                  <div className="flex flex-col gap-0.5">
                    <span className="text-sm font-medium">{tenant.planName ?? t('tenants.freePlan')}</span>
                    {tenant.subscriptionStatus && (
                      <span className="chip chip-neutral text-[10px]">{tenant.subscriptionStatus}</span>
                    )}
                  </div>
                </TableCell>
                <TableCell>{tenant.projects ?? 0}</TableCell>
                <TableCell>{tenant.comments ?? 0}</TableCell>
                <TableCell className="text-sm text-muted-foreground">
                  {tenant.isDemo ? formatExpiry(tenant.expiresAt) : '—'}
                </TableCell>
                <TableCell>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button variant="ghost" size="sm">
                        <EllipsisVertical className="h-4 w-4" />
                        <span className="sr-only">{t('tenants.actions')}</span>
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                      {tenant.approvalStatus === 'pending' && (
                        <DropdownMenuItem
                          disabled={patchMut.isPending}
                          onSelect={() => setStatus(tenant, 'approve')}
                        >
                          <ShieldCheck className="h-4 w-4" />
                          {t('tenants.approve')}
                        </DropdownMenuItem>
                      )}
                      {tenant.isActive ? (
                        <DropdownMenuItem
                          disabled={patchMut.isPending}
                          onSelect={() => setStatus(tenant, 'disable')}
                          className="text-destructive focus:text-destructive"
                        >
                          <Ban className="h-4 w-4" />
                          {t('common.disable')}
                        </DropdownMenuItem>
                      ) : (
                        <DropdownMenuItem
                          disabled={patchMut.isPending}
                          onSelect={() => setStatus(tenant, 'enable')}
                        >
                          <CheckCircle2 className="h-4 w-4" />
                          {t('common.enable')}
                        </DropdownMenuItem>
                      )}
                      {tenant.isDemo && (
                        <>
                          <DropdownMenuItem
                            disabled={extendMut.isPending || tenant.demoExtended === true}
                            title={tenant.demoExtended ? t('tenants.extendOnce') : undefined}
                            className={cn(
                              // Radix still blocks selection when disabled; keep pointer
                              // events so the extend-once tooltip remains visible.
                              tenant.demoExtended === true && 'data-[disabled]:pointer-events-auto',
                            )}
                            onSelect={() => extendMut.mutate({ id: tenant.id! })}
                          >
                            <Clock className="h-4 w-4" />
                            {t('tenants.extend')}
                          </DropdownMenuItem>
                          <DropdownMenuItem onSelect={() => openDemoConfig(tenant)}>
                            <Settings2 className="h-4 w-4" />
                            {t('tenants.editDemoConfig')}
                          </DropdownMenuItem>
                        </>
                      )}
                      <DropdownMenuItem onSelect={() => openChangePlan(tenant)}>
                        <CreditCard className="h-4 w-4" />
                        {t('tenants.changePlan')}
                      </DropdownMenuItem>
                      <DropdownMenuItem
                        disabled={deleteMut.isPending}
                        onSelect={() => setDeleteTarget(tenant)}
                        className="text-destructive focus:text-destructive"
                      >
                        <Trash2 className="h-4 w-4" />
                        {t('tenants.delete')}
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </Card>
      )}

      {/* Change plan dialog */}
      <Dialog open={!!changePlanTarget} onOpenChange={(open) => { if (!open) setChangePlanTarget(null); }}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>{t('tenants.changePlan')}</DialogTitle>
          </DialogHeader>
          <div className="flex flex-col gap-4 pt-1">
            <p className="text-sm text-muted-foreground">
              {changePlanTarget?.email ?? changePlanTarget?.displayName ?? ''}
            </p>
            <div className="flex flex-col gap-2">
              <Label>{t('tenants.selectPlan')}</Label>
              <Select value={selectedPlanId} onValueChange={setSelectedPlanId}>
                <SelectTrigger>
                  <SelectValue placeholder={t('tenants.selectPlanPlaceholder')} />
                </SelectTrigger>
                <SelectContent>
                  {allPlans.map((p) => (
                    <SelectItem key={p.id} value={String(p.id)}>
                      {p.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
          <DialogFooter className="gap-2">
            <Button variant="outline" onClick={() => setChangePlanTarget(null)}>
              {t('common.cancel')}
            </Button>
            <Button
              disabled={!selectedPlanId || changePlanMut.isPending}
              onClick={saveChangePlan}
            >
              {t('common.save')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Create tenant dialog */}
      <Dialog open={addOpen} onOpenChange={setAddOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>{t('tenants.addTenant')}</DialogTitle>
          </DialogHeader>
          <div className="flex flex-col gap-4 pt-1">
            <div className="flex flex-col gap-2">
              <Label htmlFor="tenant-email">{t('tenants.email')}</Label>
              <Input
                id="tenant-email"
                type="email"
                value={newEmail}
                onChange={(e) => setNewEmail(e.target.value)}
                autoFocus
              />
            </div>
            <div className="flex flex-col gap-2">
              <Label htmlFor="tenant-password">{t('tenants.password')}</Label>
              <PasswordInput
                id="tenant-password"
                value={newPassword}
                onChange={(e) => setNewPassword(e.target.value)}
              />
            </div>
            <div className="flex flex-col gap-2">
              <Label htmlFor="tenant-name">{t('tenants.displayName')}</Label>
              <Input
                id="tenant-name"
                value={newDisplayName}
                onChange={(e) => setNewDisplayName(e.target.value)}
              />
            </div>
          </div>
          <DialogFooter className="gap-2">
            <Button variant="outline" onClick={() => setAddOpen(false)}>
              {t('common.cancel')}
            </Button>
            <Button
              disabled={!newEmail.trim() || !newPassword.trim() || !newDisplayName.trim() || createMut.isPending}
              onClick={addTenant}
            >
              <Plus className="h-4 w-4" />
              {t('tenants.addTenant')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Demo config dialog */}
      <Dialog open={!!demoConfigTarget} onOpenChange={(open) => { if (!open) setDemoConfigTarget(null); }}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>{t('tenants.editDemoConfig')}</DialogTitle>
          </DialogHeader>
          <div className="flex flex-col gap-4 pt-1">
            <p className="text-xs text-muted-foreground">{t('tenants.demoConfigHint')}</p>
            <div className="flex flex-col gap-2">
              <Label htmlFor="demo-cap-override">{t('tenants.commentCapOverride')}</Label>
              <Input
                id="demo-cap-override"
                type="number"
                min={1}
                value={capInput}
                placeholder={t('tenants.overridePlaceholder')}
                onChange={(e) => setCapInput(e.target.value)}
              />
            </div>
            <div className="flex flex-col gap-2">
              <Label htmlFor="demo-ttl-override">{t('tenants.ttlHoursOverride')}</Label>
              <Input
                id="demo-ttl-override"
                type="number"
                min={1}
                value={ttlInput}
                placeholder={t('tenants.overridePlaceholder')}
                onChange={(e) => setTtlInput(e.target.value)}
              />
            </div>
          </div>
          <DialogFooter className="gap-2">
            <Button variant="outline" onClick={() => setDemoConfigTarget(null)}>
              {t('common.cancel')}
            </Button>
            <Button
              disabled={demoConfigMut.isPending}
              onClick={saveDemoConfig}
            >
              {t('common.save')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete with cascade warning */}
      <ConfirmDialog
        open={!!deleteTarget}
        message={t('tenants.deleteConfirm', {
          email: deleteTarget?.email ?? deleteTarget?.displayName ?? String(deleteTarget?.id),
        })}
        confirmLabel={t('tenants.delete')}
        confirmColor="warn"
        onConfirm={confirmDelete}
        onCancel={() => setDeleteTarget(null)}
      />
    </div>
  );
}
